# -*- coding: utf-8 -*-
"""Wave E / TaskCreate #22 / WS8-T2 — Partner SDK calculation golden-test helpers.

CTO doc §19.1 acceptance:

    "Two design partners have completed at least one calculation flow using
     the SDK and have signed off on usability."

This module exposes the shared scaffolding used by the two partner golden
tests:

    * :mod:`tests.factors.v0_1_alpha.test_partner_in_export_calc`
    * :mod:`tests.factors.v0_1_alpha.test_partner_eu_mfg_calc`

The partner profiles live at:

    * ``docs/factors/design-partners/partner-IN-EXPORT-01.md``
    * ``docs/factors/design-partners/partner-EU-MFG-01.md``

For each partner we:

    1. Pick the relevant subset of factors from the v0.1 catalog seeds at
       ``greenlang/factors/data/catalog_seed_v0_1/<source_id>/v1.json``.
       This is :func:`seed_partner_catalog`. The selection is keyed on
       the partner profile's allow-listed sources.
    2. Boot ``create_factors_app()`` under
       ``GL_FACTORS_RELEASE_PROFILE=alpha-v0.1`` with the alpha-only
       middleware stack and a deterministic test API key (one per
       partner). This is :func:`boot_alpha_app_for_partner`.
    3. Wire a typed :class:`FactorsClient` to the in-process app via the
       same :class:`httpx.MockTransport` bridge the IPCC E2E test uses.
       This is :func:`make_partner_client`.

Note on the "allow-listed sources" partner-profile contract:

    The alpha API surface itself does NOT enforce per-partner allowlists
    (that is a Beta/GA feature — runtime tenant policy). Under v0.1
    alpha the allow-list is a docs/contract artifact that constrains
    which sources the partner is *expected* to query and which the
    GreenLang team commits to keeping green for the partner's pilot.
    The partner golden tests therefore pre-load only the partner's
    allow-listed sources into the in-process catalog — so the SDK
    surface naturally returns only those, even though the runtime is
    not technically gating them.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Mapping

import httpx

# ---------------------------------------------------------------------------
# Partner profile catalog — keep in sync with the markdown profile files
# under docs/factors/design-partners/.
# ---------------------------------------------------------------------------

# Map partner slug -> ordered list of catalog_seed_v0_1 source slugs that
# back the partner's allow-listed sources. The catalog_seed_v0_1 directory
# names use underscores; the source URNs on the wire use hyphens. The two
# share a 1:1 mapping via slugify(source_id).
_PARTNER_SOURCE_DIRS: Mapping[str, List[str]] = {
    # IN-EXPORT-01: India textile exporter — Scope 2 location-based via India
    # CEA national grid. ipcc-ar6 is allow-listed in the partner doc; the
    # canonical alpha source id is ``ipcc_2006_nggi`` (with ``ipcc_ar6`` as
    # an alpha alias). For the golden test we only need the CEA factor +
    # the CBAM defaults stub, since the calc itself uses the CEA factor.
    "IN-EXPORT-01": [
        "india_cea_co2_baseline",
        "ipcc_2006_nggi",
        "cbam_default_values",
    ],
    # EU-MFG-01: Italian cement producer — CBAM cement default lookup.
    "EU-MFG-01": [
        "cbam_default_values",
        "ipcc_2006_nggi",
    ],
}

# One deterministic test API key per partner. Real keys never live in this
# repo; these strings exist only to drive the AuthMeteringMiddleware in
# the in-process test app.
PARTNER_API_KEYS: Mapping[str, str] = {
    "IN-EXPORT-01": "gl_alpha_in_export_01_test",
    "EU-MFG-01": "gl_alpha_eu_mfg_01_test",
}

# Repo root, used to resolve catalog_seed_v0_1/ relative to this file.
_REPO_ROOT = Path(__file__).resolve().parents[3]
_SEED_ROOT = (
    _REPO_ROOT / "greenlang" / "factors" / "data" / "catalog_seed_v0_1"
)


def seed_partner_catalog(partner_slug: str) -> List[Dict[str, Any]]:
    """Return the v0.1 factor records that back ``partner_slug``'s allow-list.

    Reads ``catalog_seed_v0_1/<source_id>/v1.json`` for every allow-listed
    source and concatenates the ``records`` arrays. The order is stable
    (allow-list order, then file order) so test assertions can rely on
    deterministic indices when they need to.

    Args:
        partner_slug: ``"IN-EXPORT-01"`` or ``"EU-MFG-01"``.

    Returns:
        Flat list of v0.1-shape factor dicts. Each dict satisfies the
        frozen ``factor_record_v0_1.schema.json`` contract AND the alpha
        provenance gate (the seeds were generated by the Wave D/D+1
        backfill and round-trip-tested in
        ``test_alpha_source_snapshots.py``).

    Raises:
        KeyError: ``partner_slug`` is not a known partner.
        FileNotFoundError: a seed file is missing on disk.
    """
    if partner_slug not in _PARTNER_SOURCE_DIRS:
        raise KeyError(
            f"unknown partner slug: {partner_slug!r}; "
            f"known: {sorted(_PARTNER_SOURCE_DIRS)!r}"
        )
    out: List[Dict[str, Any]] = []
    for source_dir in _PARTNER_SOURCE_DIRS[partner_slug]:
        seed_path = _SEED_ROOT / source_dir / "v1.json"
        if not seed_path.is_file():
            raise FileNotFoundError(
                f"catalog_seed_v0_1 missing for partner {partner_slug}: "
                f"{seed_path}"
            )
        with seed_path.open("r", encoding="utf-8") as handle:
            payload = json.load(handle)
        records = payload.get("records") or []
        if not isinstance(records, list):
            raise ValueError(
                f"catalog_seed_v0_1 file {seed_path} has malformed records: "
                f"{type(records).__name__}"
            )
        out.extend(records)
    return out


def boot_alpha_app_for_partner(
    monkeypatch: Any,
    partner_slug: str,
    factors: List[Dict[str, Any]],
    *,
    edition_id: str,
) -> Any:
    """Boot ``create_factors_app()`` in alpha mode and seed it for a partner.

    Steps:

      1. Force ``GL_FACTORS_RELEASE_PROFILE=alpha-v0.1`` and a clean
         test environment.
      2. Register the partner's deterministic test API key on the
         in-memory keyring (``GL_FACTORS_API_KEYS``) so the
         :class:`AuthMeteringMiddleware` accepts it on the four
         protected alpha routes.
      3. Validate every seeded record with the
         :class:`AlphaProvenanceGate` (production hard-gate).
      4. Install the v0.1 e2e shim from ``_e2e_helpers.install_alpha_e2e_shim``
         in shim mode, exposing the seeded records via the alpha router.

    Args:
        monkeypatch: pytest's ``monkeypatch`` fixture.
        partner_slug: ``"IN-EXPORT-01"`` or ``"EU-MFG-01"``.
        factors: pre-seeded v0.1 factor records (typically the output
            of :func:`seed_partner_catalog`).
        edition_id: synthetic edition id surfaced by ``/v1/healthz``.

    Returns:
        The booted FastAPI ``app``.
    """
    import pytest  # local import: keep helper importable outside pytest

    pytest.importorskip("fastapi")

    if partner_slug not in PARTNER_API_KEYS:
        raise KeyError(f"unknown partner slug: {partner_slug!r}")

    api_key = PARTNER_API_KEYS[partner_slug]

    # ---- Force alpha profile + clean env. -------------------------------
    monkeypatch.setenv("GL_FACTORS_RELEASE_PROFILE", "alpha-v0.1")
    monkeypatch.setenv("GL_ENV", "test")
    monkeypatch.setenv(
        "GL_FACTORS_SIGNING_SECRET",
        "test-signing-secret-for-partner-alpha-receipts-32chars",
    )
    monkeypatch.delenv("APP_ENV", raising=False)
    monkeypatch.delenv("ENVIRONMENT", raising=False)

    # ---- Register the partner's deterministic test API key. -------------
    # AuthMeteringMiddleware reads GL_FACTORS_API_KEYS at validator-load
    # time; we clear the cached singleton so the new key picks up.
    keyring_payload = json.dumps(
        [
            {
                "key_id": f"alpha-{partner_slug.lower()}",
                "key": api_key,
                "tier": "enterprise",
                "active": True,
            }
        ]
    )
    monkeypatch.setenv("GL_FACTORS_API_KEYS", keyring_payload)

    from greenlang.factors import api_auth as _api_auth

    _api_auth._default_validator = None
    _api_auth.default_validator().reload()

    # ---- Pre-publish gate — every seeded record MUST pass. --------------
    from greenlang.factors.quality.alpha_provenance_gate import (
        AlphaProvenanceGate,
    )

    gate = AlphaProvenanceGate()
    for record in factors:
        gate.assert_valid(record)

    # ---- Boot app + install shim. ---------------------------------------
    from greenlang.factors.factors_app import create_factors_app

    app = create_factors_app(
        enable_admin=False,
        enable_billing=False,
        enable_oem=False,
        enable_metrics=False,
    )

    from tests.factors.v0_1_alpha._e2e_helpers import (
        install_alpha_e2e_shim,
    )

    install_alpha_e2e_shim(
        monkeypatch,
        app,
        edition_id=edition_id,
        factors=factors,
    )

    return app


def _build_testclient_transport(app: Any) -> httpx.MockTransport:
    """Build a sync ``httpx.MockTransport`` that delegates to FastAPI.

    Mirrors the bridge used by ``test_sdk_e2e_ipcc_publish.py`` —
    httpx 0.28's :class:`httpx.ASGITransport` is async-only, so the
    sync :class:`FactorsClient` cannot use it directly. We route every
    outbound request through FastAPI's :class:`TestClient` and translate
    the result back into an :class:`httpx.Response`.
    """
    from fastapi.testclient import TestClient

    test_client = TestClient(app)

    def _handler(request: httpx.Request) -> httpx.Response:
        url = request.url.path
        if request.url.query:
            url = f"{url}?{request.url.query.decode()}"
        upstream = test_client.request(
            method=request.method,
            url=url,
            headers={
                k: v
                for k, v in request.headers.items()
                if k.lower() != "host"
            },
            content=request.content,
        )
        passthrough_headers = {
            k: v
            for k, v in upstream.headers.items()
            if k.lower()
            not in {
                "transfer-encoding",
                "content-encoding",
                "content-length",
            }
        }
        return httpx.Response(
            status_code=upstream.status_code,
            content=upstream.content,
            headers=passthrough_headers,
        )

    return httpx.MockTransport(_handler)


def make_partner_client(app: Any, partner_slug: str) -> Any:
    """Return a :class:`FactorsClient` bound to ``app`` as ``partner_slug``.

    The client uses the partner's deterministic test API key so the
    ``AuthMeteringMiddleware`` accepts it. ``api_prefix='/v1'`` is the
    canonical alpha prefix (the legacy ``/api/v1`` returns 410 Gone
    under alpha-v0.1).
    """
    from greenlang.factors.sdk.python import FactorsClient

    if partner_slug not in PARTNER_API_KEYS:
        raise KeyError(f"unknown partner slug: {partner_slug!r}")

    transport = _build_testclient_transport(app)
    return FactorsClient(
        base_url="http://factors.test",
        transport=transport,
        api_prefix="/v1",
        api_key=PARTNER_API_KEYS[partner_slug],
        verify_greenlang_cert=False,
    )


__all__ = [
    "PARTNER_API_KEYS",
    "boot_alpha_app_for_partner",
    "make_partner_client",
    "seed_partner_catalog",
]
