# -*- coding: utf-8 -*-
"""Wave C / WS1-T4 — Alpha schema CI gate.

Runs the v0.1 :class:`AlphaProvenanceGate` against every record produced
by the 6 alpha-source parsers and FAILS the build if any record is
invalid. This test is the regression bar that Wave C task #6 (provenance
backfill) must clear: until it lands, the test is :pyattr:`pytest.mark.xfail`
so CI surfaces the gap without breaking the master branch.

Pipeline
--------
1. Enumerate the 6 alpha sources via
   ``greenlang.factors.source_registry.alpha_v0_1_sources()`` (raw YAML
   dicts keyed by ``source_id``).
2. For each source, import the parser module declared in the registry
   (``parser_module``) and call the declared ``parser_function`` against
   the canonical alpha fixture under
   ``greenlang/factors/data/catalog_seed/_inputs/<filename>.json``.
3. Coerce each produced record to a plain dict (parsers may return
   :class:`EmissionFactorRecord` instances — call ``.to_dict()`` when
   present).
4. Run :py:meth:`AlphaProvenanceGate.validate` against every record and
   collect ALL failures across all sources.
5. The test fails with a structured per-source report listing
   total / fail counts plus the first 3 failure reasons per record.

The test is parametrised one case per source so a single CI report
shows pass/fail per alpha source. When the seed fixture for a source is
empty (e.g. the parser exists but the JSON has not been wired up yet),
the test calls ``pytest.skip()`` with a clear reason rather than
fail-loud — see the ``skip_unless_alpha_records_seeded`` marker
registered in ``conftest.py``.

CTO doc references: §6.1, §19.1 (FY27 Q1 alpha — provenance fields
complete), Wave C / TaskCreate #4.
Schema $id: https://schemas.greenlang.io/factors/factor_record_v0_1.schema.json
"""
from __future__ import annotations

import importlib
import json
import logging
import re
from collections import Counter
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

import pytest

from greenlang.factors.quality.alpha_provenance_gate import AlphaProvenanceGate
from greenlang.factors.source_registry import alpha_v0_1_sources

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Repo-relative paths
# ---------------------------------------------------------------------------

# tests/factors/v0_1_alpha/test_schema_validates_alpha_catalog.py -> repo root
_REPO_ROOT = Path(__file__).resolve().parents[3]
_SEED_INPUTS_DIR = (
    _REPO_ROOT / "greenlang" / "factors" / "data" / "catalog_seed" / "_inputs"
)
# Wave D / TaskCreate #6 — pre-lifted v0.1-shape seeds. When present we
# load these directly (no parser invocation, no further normalisation)
# and feed them to the gate as-is. Generated by
# ``scripts/factors_alpha_v0_1_backfill.py``.
_SEED_V0_1_DIR = (
    _REPO_ROOT / "greenlang" / "factors" / "data" / "catalog_seed_v0_1"
)


# ---------------------------------------------------------------------------
# source_id -> seed filename
# ---------------------------------------------------------------------------
# The catalog seed uses friendlier filenames than the registry source_ids
# (registry: `epa_hub`, seed file: `epa_ghg_hub.json`). Keep the mapping
# explicit so a rename in either side is caught immediately.
_SOURCE_ID_TO_SEED_FILE: Dict[str, str] = {
    "epa_hub": "epa_ghg_hub.json",
    "egrid": "egrid.json",
    "desnz_ghg_conversion": "desnz_uk.json",
    "india_cea_co2_baseline": "india_cea.json",
    "ipcc_2006_nggi": "ipcc_defaults.json",
    "cbam_default_values": "cbam_default_values.json",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _seed_path_for(source_id: str) -> Path:
    """Resolve the canonical seed JSON path for a registry source_id."""
    filename = _SOURCE_ID_TO_SEED_FILE.get(source_id, f"{source_id}.json")
    return _SEED_INPUTS_DIR / filename


def _load_seed_data(seed_path: Path) -> Optional[Any]:
    """Load and parse a JSON seed file. Returns None when absent/empty."""
    if not seed_path.is_file():
        return None
    try:
        text = seed_path.read_text(encoding="utf-8")
    except OSError as exc:  # pragma: no cover — surface-only path
        logger.warning("seed file %s unreadable: %s", seed_path, exc)
        return None
    if not text.strip():
        return None
    return json.loads(text)


def _resolve_parser(source: Dict[str, Any]) -> Callable[..., Any]:
    """Import the legacy function-style parser declared by the registry.

    Resolution order:
      1. The nested ``parser:`` block (``module``/``function``) — this is
         the legacy alpha parser kept unchanged for legacy callers per the
         Phase 3 / Wave 2.0 source-registry comment.
      2. Top-level ``parser_module`` / ``parser_function`` — these may
         have been overwritten in Wave 2.0 with class-based
         runner-dispatch parsers (Phase3*ExcelParser etc.). The alpha
         provenance gate exercises the FUNCTION-style parsers, so we
         prefer the nested block when present.
    """
    legacy = source.get("parser") or {}
    module_name = legacy.get("module") or source.get("parser_module")
    function_name = legacy.get("function") or source.get("parser_function")
    if not isinstance(module_name, str) or not module_name:
        raise RuntimeError(
            f"alpha source {source.get('source_id')!r} has no parser_module"
        )
    if not isinstance(function_name, str) or not function_name:
        raise RuntimeError(
            f"alpha source {source.get('source_id')!r} has no parser_function"
        )
    module = importlib.import_module(module_name)
    fn = getattr(module, function_name, None)
    if fn is None or not callable(fn):
        raise RuntimeError(
            f"{module_name}.{function_name} is not callable / does not exist"
        )
    return fn


def _record_to_dict(rec: Any) -> Dict[str, Any]:
    """Coerce a parser output into a plain dict.

    Parsers either return ``List[Dict[str, Any]]`` or
    ``List[EmissionFactorRecord]`` — both shapes are fed through the gate
    by going via ``.to_dict()`` when the object exposes it.
    """
    if isinstance(rec, dict):
        return rec
    to_dict = getattr(rec, "to_dict", None)
    if callable(to_dict):
        out = to_dict()
        if isinstance(out, dict):
            return out
    # Last resort: tell the test author the record shape is incompatible.
    raise TypeError(
        f"parser produced an unsupported record type {type(rec).__name__}; "
        f"expected dict or .to_dict()-compatible object"
    )


def _invoke_parser(
    parser: Callable[..., Any],
    payload: Any,
    source_id: str,
) -> List[Any]:
    """Call ``parser`` with the seed payload, handling shape variations.

    * Most parsers take a single dict (``parse_epa_ghg_hub(data)``).
    * ``parse_india_cea_rows`` takes an iterable of rows — when the seed
      is a dict with a ``rows`` key, dereference it.
    * Returns a list of records (whatever the parser produced).
    """
    # Special-case: india_cea expects rows directly, not the wrapper dict.
    if source_id == "india_cea_co2_baseline":
        if isinstance(payload, dict):
            rows = payload.get("rows") or []
        else:
            rows = payload
        result = parser(rows)
    else:
        result = parser(payload)

    if result is None:
        return []
    if isinstance(result, list):
        return result
    # Some parsers may yield iterators — materialise once, defensively.
    return list(result)


def _v0_1_seed_path_for(source_id: str) -> Path:
    """Path to the pre-lifted v0.1 seed JSON for a registry source_id."""
    return _SEED_V0_1_DIR / source_id / "v1.json"


def _load_v0_1_seed(source_id: str) -> Optional[List[Dict[str, Any]]]:
    """Return the pre-lifted v0.1 records for ``source_id`` if present.

    Reads ``greenlang/factors/data/catalog_seed_v0_1/<source_id>/v1.json``
    and returns its ``records`` array. Returns ``None`` when the seed
    file is absent (caller falls back to running the parser).
    """
    path = _v0_1_seed_path_for(source_id)
    if not path.is_file():
        return None
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:  # pragma: no cover — surface-only path
        logger.warning("v0.1 seed unreadable for %s: %s", source_id, exc)
        return None
    if not text.strip():
        return []
    try:
        payload = json.loads(text)
    except json.JSONDecodeError as exc:
        logger.warning("v0.1 seed invalid JSON for %s: %s", source_id, exc)
        return None
    if not isinstance(payload, dict):
        return None
    records = payload.get("records")
    if not isinstance(records, list):
        return []
    return [r for r in records if isinstance(r, dict)]


def _load_records_for_source(source: Dict[str, Any]) -> Tuple[List[Dict[str, Any]], str]:
    """Resolve the v0.1 records for an alpha source.

    Resolution priority:
      1. ``catalog_seed_v0_1/<source_id>/v1.json`` — pre-lifted v0.1
         records produced by ``scripts/factors_alpha_v0_1_backfill.py``.
         When present we feed these directly to the gate; they are the
         post-lift, contract-shaped records and require no further
         normalisation.
      2. Otherwise, run the source's parser against its v1-shape seed
         under ``catalog_seed/_inputs/`` and return the (still-v1-shape)
         records to the caller. This branch keeps the test useful before
         the backfill has been generated and is the path the original
         CI gate (Wave C / task #4) used.

    Returns ``(records, status)`` where ``status`` is one of:
      * ``"ok"``           — records were produced.
      * ``"no_seed"``      — seed file (either path) is missing or empty.
      * ``"parser_error"`` — parser import or invocation failed.

    A non-``"ok"`` status yields an empty record list; the caller is
    expected to ``pytest.skip()`` on those branches.
    """
    source_id = str(source.get("source_id") or "")

    # Path 1 — pre-lifted v0.1 seed.
    v0_1 = _load_v0_1_seed(source_id)
    if v0_1 is not None:
        if not v0_1:
            return [], "no_seed"
        return v0_1, "ok"

    # Path 2 — fall back to running the parser on the v1 seed.
    seed_path = _seed_path_for(source_id)
    payload = _load_seed_data(seed_path)
    if payload is None:
        return [], "no_seed"

    try:
        parser = _resolve_parser(source)
    except (ImportError, RuntimeError, AttributeError) as exc:
        logger.warning(
            "alpha parser resolve failed for %s: %s", source_id, exc
        )
        return [], "parser_error"

    try:
        raw_records = _invoke_parser(parser, payload, source_id)
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "alpha parser invocation failed for %s: %s", source_id, exc
        )
        return [], "parser_error"

    out: List[Dict[str, Any]] = []
    for rec in raw_records:
        try:
            out.append(_record_to_dict(rec))
        except TypeError as exc:
            # Skip records we can't interpret — flag it as a synthetic failure.
            logger.warning(
                "skipping unconvertable record from %s: %s", source_id, exc
            )
    return out, "ok"


def _format_failure_report(
    source: Dict[str, Any],
    total: int,
    failures: List[Tuple[int, List[str]]],
) -> str:
    """Build the structured failure report shown in the assertion."""
    source_id = source.get("source_id") or "<unknown>"
    lines: List[str] = [
        f"FAIL: source={source_id}",
        f"  total records: {total}",
        f"  failed: {len(failures)} / {total}",
        "  first 3 failures:",
    ]
    for idx, errs in failures[:3]:
        # Each record's errors are already capped to <=3 by the caller;
        # join them on '; ' so the report stays one-line-per-record.
        lines.append(f"    record[{idx}]: {'; '.join(errs)}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def gate() -> AlphaProvenanceGate:
    return AlphaProvenanceGate()


def _alpha_source_param_ids() -> List[Dict[str, Any]]:
    """Sorted list of alpha source raw dicts (stable test ordering)."""
    sources = alpha_v0_1_sources() or {}
    return [sources[k] for k in sorted(sources.keys())]


# ---------------------------------------------------------------------------
# The CI gate
# ---------------------------------------------------------------------------


@pytest.mark.skip_unless_alpha_records_seeded
@pytest.mark.parametrize(
    "source",
    _alpha_source_param_ids(),
    ids=lambda s: str(s.get("source_id") or "<unknown>"),
)
def test_alpha_source_records_pass_provenance_gate(
    source: Dict[str, Any], gate: AlphaProvenanceGate
) -> None:
    """Every record from an alpha-source parser must pass the gate.

    Wave D / TaskCreate #6 — when the v0.1 catalog seeds under
    ``greenlang/factors/data/catalog_seed_v0_1/<source_id>/v1.json``
    exist, this test loads them directly (post-lift, contract-shaped)
    and the gate must pass STRICT (no xfail). Until the backfill seeds
    are generated, the test transparently falls back to running the
    raw v1 parser and the gate will fail; in that state the test signals
    the regression by failing — not via xfail.
    """
    source_id = source.get("source_id") or "<unknown>"
    records, status = _load_records_for_source(source)

    if status == "no_seed":
        pytest.skip(
            f"no alpha seed input for {source_id} at "
            f"{_seed_path_for(source_id).relative_to(_REPO_ROOT)}"
        )
    if status == "parser_error":
        pytest.skip(
            f"parser for {source_id} could not be exercised in unit-test "
            f"scope (see captured logs for the underlying cause)"
        )

    assert records, f"no records produced by {source_id}"

    failures: List[Tuple[int, List[str]]] = []
    for i, rec in enumerate(records):
        errs = gate.validate(rec)
        if errs:
            failures.append((i, errs[:3]))  # cap each record's errors

    assert not failures, _format_failure_report(source, len(records), failures)


# ---------------------------------------------------------------------------
# Aggregate sanity check — produces the per-source pass/fail summary in the
# test logs even when the parametrised cases xfail. This test is NOT
# xfailed because it just verifies the test harness itself can execute
# the parsers and produce a report; the assertion only fires if EVERY
# alpha source has zero records (a config regression).
# ---------------------------------------------------------------------------


def test_alpha_catalog_summary_can_be_produced(
    gate: AlphaProvenanceGate, caplog: pytest.LogCaptureFixture
) -> None:
    """Smoke-test the harness: every alpha source must yield SOMETHING.

    Either records (which then go through the gate) or a clean
    ``no_seed`` / ``parser_error`` status. The test fails only when the
    registry-declared 6 alpha sources collapse to zero — a config
    regression that would silently disable the CI gate.
    """
    sources = _alpha_source_param_ids()
    assert len(sources) == 6, (
        f"expected 6 alpha sources from alpha_v0_1_sources(); got {len(sources)}"
    )

    rows: List[Dict[str, Any]] = []
    overall_failure_modes: Counter = Counter()
    for source in sources:
        source_id = str(source.get("source_id") or "<unknown>")
        records, status = _load_records_for_source(source)
        passed = 0
        failed = 0
        if status == "ok":
            for rec in records:
                errs = gate.validate(rec)
                if errs:
                    failed += 1
                    overall_failure_modes.update(_failure_keys(errs))
                else:
                    passed += 1
        rows.append(
            {
                "source_id": source_id,
                "status": status,
                "total": len(records),
                "passed": passed,
                "failed": failed,
            }
        )

    # Log the report at WARNING so it surfaces in CI without an extra flag.
    logger.warning("ALPHA-CATALOG GATE SUMMARY:")
    logger.warning(
        "%-28s | %-12s | %5s | %5s | %5s",
        "source_id", "status", "total", "pass", "fail",
    )
    logger.warning("-" * 72)
    for r in rows:
        logger.warning(
            "%-28s | %-12s | %5d | %5d | %5d",
            r["source_id"], r["status"], r["total"], r["passed"], r["failed"],
        )
    if overall_failure_modes:
        logger.warning("TOP FAILURE MODES:")
        for mode, count in overall_failure_modes.most_common(5):
            logger.warning("  %4d x %s", count, mode)

    # Require AT LEAST ONE source to have produced records. Zero across
    # the board means the test harness is broken (parser dir gone,
    # seeds purged, etc.) — that IS a regression worth blocking on.
    assert any(r["total"] > 0 for r in rows), (
        "ALL alpha sources produced 0 records — alpha CI gate is no-op. "
        f"per-source rows: {rows}"
    )


_REQUIRED_PROP_RE = re.compile(r"'([^']+)' is a required property")
_ADDITIONAL_PROPS_RE = re.compile(r"^Additional properties are not allowed")


def _failure_keys(errs: List[str]) -> List[str]:
    """Reduce each failure message to a stable, aggregable key.

    The gate produces messages like::

        schema[<root>]: 'urn' is a required property
        schema[<root>]: Additional properties are not allowed ('factor_id', ...)
        schema[extraction.parser_commit]: must be 7-40 hex...
        alpha[review.approved_by]: required when review_status == 'approved'
        alpha[gwp_basis]: must be 'ar6' in v0.1 alpha; got 'ar5'

    For aggregation, we want one bucket per *distinct missing field /
    distinct constraint violation*. Strategy:

    * If the message contains ``'<X>' is a required property``, bucket as
      ``missing[<X>]`` (independent of which path it surfaced under).
    * If the message starts with ``Additional properties...``, bucket as
      ``schema[additionalProperties]`` (the v1->v0_1 shape mismatch).
    * Otherwise, fall back to the leading ``<layer>[<path>]`` prefix.
    """
    out: List[str] = []
    for e in errs:
        head, sep, tail = e.partition(":")
        body = (tail or "").strip()
        m = _REQUIRED_PROP_RE.search(body)
        if m:
            out.append(f"missing[{m.group(1)}]")
            continue
        if _ADDITIONAL_PROPS_RE.match(body):
            out.append("schema[additionalProperties]")
            continue
        out.append(head.strip() if sep else e.strip())
    return out
