# -*- coding: utf-8 -*-
"""PACK-008 EU Taxonomy Alignment calculation engines."""

from .eligibility_engine import (
    TaxonomyEligibilityEngine,
    EligibilityResult,
    PortfolioEligibility,
    TaxonomyActivity,
    EnvironmentalObjective as EligibilityObjective,
    TaxonomySector,
    EligibilityStatus,
)
from .substantial_contribution_engine import (
    SubstantialContributionEngine,
    SCResult,
    ThresholdResult,
    TSCThreshold,
    SCStatus,
    ActivityClassification,
)
from .dnsh_engine import (
    DNSHAssessmentEngine,
    DNSHResult,
    ObjectiveDNSHResult,
    DNSHCriterion,
    DNSHStatus,
)
from .minimum_safeguards_engine import (
    MinimumSafeguardsEngine,
    MSResult,
    TopicResult,
    SafeguardTopic,
    TopicStatus,
)
from .kpi_calculation_engine import (
    KPICalculationEngine,
    KPIResult,
    KPIType,
    CapExPlanStatus,
    YoYComparison,
    ObjectiveBreakdown,
)
from .gar_engine import (
    GreenAssetRatioEngine,
    GARResult,
    BTARResult,
    ExposureClassification,
    Exposure,
    ExposureType,
    EPCRating,
    CounterpartyType,
    GARConfig,
)
from .tsc_engine import (
    TechnicalScreeningCriteriaEngine,
    TSCCriteria,
    TSCEvaluation,
    CriterionEvaluation,
    DelegatedActVersion,
    DelegatedActId,
    EnvironmentalObjective as TSCObjective,
    CriterionType,
    ComparisonOperator,
)
from .transition_activity_engine import (
    TransitionActivityEngine,
    BATResult,
    LockInResult,
    TransitionPathway,
    TransitionStatus,
    LockInRisk,
    BATBenchmark,
    TransitionActivityInfo,
)
from .enabling_activity_engine import (
    EnablingActivityEngine,
    EnablementResult,
    LifecycleResult,
    EnablementType,
    LifecycleImpact,
    MarketDistortionRisk,
    EnablingActivityInfo,
    EnabledActivity,
)
from .taxonomy_reporting_engine import (
    TaxonomyReportingEngine,
    Article8Report,
    EBATemplates,
    EBATemplate,
    XBRLOutput,
    XBRLTag,
    DisclosureTable,
    TableRow,
    ActivityKPIData,
    AlignmentData,
    GARInputData,
    PriorPeriodData,
    DisclosureType,
    EBATemplateId,
    KPIType as ReportingKPIType,
)

__all__ = [
    # Eligibility
    "TaxonomyEligibilityEngine",
    "EligibilityResult",
    "PortfolioEligibility",
    "TaxonomyActivity",
    "EligibilityObjective",
    "TaxonomySector",
    "EligibilityStatus",
    # Substantial Contribution
    "SubstantialContributionEngine",
    "SCResult",
    "ThresholdResult",
    "TSCThreshold",
    "SCStatus",
    "ActivityClassification",
    # DNSH
    "DNSHAssessmentEngine",
    "DNSHResult",
    "ObjectiveDNSHResult",
    "DNSHCriterion",
    "DNSHStatus",
    # Minimum Safeguards
    "MinimumSafeguardsEngine",
    "MSResult",
    "TopicResult",
    "SafeguardTopic",
    "TopicStatus",
    # KPI Calculation
    "KPICalculationEngine",
    "KPIResult",
    "KPIType",
    "CapExPlanStatus",
    "YoYComparison",
    "ObjectiveBreakdown",
    # GAR Engine
    "GreenAssetRatioEngine",
    "GARResult",
    "BTARResult",
    "ExposureClassification",
    "Exposure",
    "ExposureType",
    "EPCRating",
    "CounterpartyType",
    "GARConfig",
    # TSC Engine
    "TechnicalScreeningCriteriaEngine",
    "TSCCriteria",
    "TSCEvaluation",
    "CriterionEvaluation",
    "DelegatedActVersion",
    "DelegatedActId",
    "TSCObjective",
    "CriterionType",
    "ComparisonOperator",
    # Transition Activity Engine
    "TransitionActivityEngine",
    "BATResult",
    "LockInResult",
    "TransitionPathway",
    "TransitionStatus",
    "LockInRisk",
    "BATBenchmark",
    "TransitionActivityInfo",
    # Enabling Activity Engine
    "EnablingActivityEngine",
    "EnablementResult",
    "LifecycleResult",
    "EnablementType",
    "LifecycleImpact",
    "MarketDistortionRisk",
    "EnablingActivityInfo",
    "EnabledActivity",
    # Taxonomy Reporting Engine
    "TaxonomyReportingEngine",
    "Article8Report",
    "EBATemplates",
    "EBATemplate",
    "XBRLOutput",
    "XBRLTag",
    "DisclosureTable",
    "TableRow",
    "ActivityKPIData",
    "AlignmentData",
    "GARInputData",
    "PriorPeriodData",
    "DisclosureType",
    "EBATemplateId",
    "ReportingKPIType",
]
