# -*- coding: utf-8 -*-
"""
Prometheus Metrics - AGENT-DATA-019: Validation Rule Engine

12 Prometheus metrics for validation rule engine service monitoring with
graceful fallback when prometheus_client is not installed.

Standard metrics (via MetricsFactory):
    1.  gl_vre_operations_total (Counter, labels: type, tenant_id)
    2.  gl_vre_processing_duration_seconds (Histogram, 12 buckets)
    3.  gl_vre_validation_errors_total (Counter, labels: severity, type)
    4.  gl_vre_batch_jobs_total (Counter, labels: status)
    5.  gl_vre_active_jobs (Gauge)
    6.  gl_vre_queue_size (Gauge)

Agent-specific metrics:
    7.  gl_vre_rules_registered_total (Counter, labels: rule_type, severity)
    8.  gl_vre_rule_sets_created_total (Counter, labels: pack_type)
    9.  gl_vre_evaluations_total (Counter, labels: result, rule_type)
    10. gl_vre_rules_per_set (Histogram, buckets: set-size-scale)
    11. gl_vre_evaluation_duration_seconds (Histogram, labels: operation)
    12. gl_vre_active_rules (Gauge)

Author: GreenLang Platform Team
Date: February 2026
PRD: AGENT-DATA-019 Validation Rule Engine (GL-DATA-X-022)
Status: Production Ready
"""

from __future__ import annotations

from greenlang.data_commons.metrics import (
    PROMETHEUS_AVAILABLE,
    MetricsFactory,
)

# ---------------------------------------------------------------------------
# Standard metrics (6 of 12) via factory
# ---------------------------------------------------------------------------

m = MetricsFactory(
    "gl_vre",
    "Validation Rule Engine",
    duration_buckets=(0.01, 0.05, 0.1, 0.5, 1, 5, 10),
)

# ---------------------------------------------------------------------------
# Agent-specific metrics (6 of 12)
# ---------------------------------------------------------------------------

vre_rules_registered_total = m.create_custom_counter(
    "rules_registered_total",
    "Total validation rules registered in the rule engine",
    labelnames=["rule_type", "severity"],
)

vre_rule_sets_created_total = m.create_custom_counter(
    "rule_sets_created_total",
    "Total rule sets created in the validation rule engine",
    labelnames=["pack_type"],
)

vre_evaluations_total = m.create_custom_counter(
    "evaluations_total",
    "Total rule evaluations performed by the validation rule engine",
    labelnames=["result", "rule_type"],
)

vre_evaluation_failures_total = m.create_custom_counter(
    "evaluation_failures_total",
    "Total rule evaluation failures by severity level",
    labelnames=["severity"],
)

vre_conflicts_detected_total = m.create_custom_counter(
    "conflicts_detected_total",
    "Total rule conflicts detected during evaluation or registration",
    labelnames=["conflict_type"],
)

vre_reports_generated_total = m.create_custom_counter(
    "reports_generated_total",
    "Total validation reports generated by the rule engine",
    labelnames=["report_type", "format"],
)

vre_rules_per_set = m.create_custom_histogram(
    "rules_per_set",
    "Distribution of the number of rules per rule set",
    buckets=(1, 5, 10, 25, 50, 100, 250, 500),
)

vre_evaluation_duration_seconds = m.create_custom_histogram(
    "evaluation_duration_seconds",
    "Duration of rule evaluation operations in seconds",
    buckets=(0.01, 0.05, 0.1, 0.5, 1, 5, 10, 30),
    labelnames=["operation"],
)

vre_processing_duration_seconds = m.create_custom_histogram(
    "processing_duration_seconds_detail",
    "Validation rule engine operation processing duration in seconds",
    buckets=(0.01, 0.05, 0.1, 0.5, 1, 5, 10),
    labelnames=["operation"],
)

vre_active_rules = m.create_custom_gauge(
    "active_rules",
    "Current number of active validation rules in the engine",
)

vre_active_rule_sets = m.create_custom_gauge(
    "active_rule_sets",
    "Current number of active rule sets in the engine",
)

vre_pass_rate = m.create_custom_gauge(
    "pass_rate",
    "Current overall pass rate of rule evaluations (0.0 to 1.0)",
)


# ---------------------------------------------------------------------------
# Helper functions (safe to call even without prometheus_client)
# ---------------------------------------------------------------------------


def record_rule_registered(rule_type: str, severity: str) -> None:
    """Record a validation rule registration event.

    Args:
        rule_type: Type of validation rule registered
            (range_check, format_validation, cross_field, regex,
            lookup, threshold, conditional, temporal, referential,
            custom, regulatory, completeness, uniqueness, consistency).
        severity: Severity level of the registered rule
            (critical, error, warning, info, debug).
    """
    m.safe_inc(vre_rules_registered_total, 1, rule_type=rule_type, severity=severity)


def record_rule_set_created(pack_type: str) -> None:
    """Record a rule set creation event.

    Args:
        pack_type: Type or framework association of the rule set
            (ghg_protocol, csrd_esrs, tcfd, cdp, sbti, iso14064,
            eudr, custom, internal, regulatory, compliance, quality).
    """
    m.safe_inc(vre_rule_sets_created_total, 1, pack_type=pack_type)


def record_evaluation(result: str, rule_type: str) -> None:
    """Record a rule evaluation execution event.

    Args:
        result: Evaluation result outcome
            (pass, fail, warning, error, skipped, not_applicable).
        rule_type: Type of validation rule that was evaluated.
    """
    m.safe_inc(vre_evaluations_total, 1, result=result, rule_type=rule_type)


def record_evaluation_failure(severity: str) -> None:
    """Record an evaluation failure event by severity.

    Args:
        severity: Severity of the failed validation rule
            (critical, error, warning, info).
    """
    m.safe_inc(vre_evaluation_failures_total, 1, severity=severity)


def record_conflict_detected(conflict_type: str) -> None:
    """Record a rule conflict detection event.

    Args:
        conflict_type: Type of conflict detected between rules
            (contradiction, overlap, subsumption, redundancy,
            circular_dependency, priority_ambiguity, scope_collision,
            temporal_conflict).
    """
    m.safe_inc(vre_conflicts_detected_total, 1, conflict_type=conflict_type)


def record_report_generated(report_type: str, format: str) -> None:
    """Record a validation report generation event.

    Args:
        report_type: Type of validation report generated
            (evaluation_summary, compliance_report, conflict_analysis,
            rule_coverage, audit_trail, quality_scorecard,
            trend_analysis, exception_report).
        format: Output format of the generated report
            (json, html, pdf, csv, markdown, xml).
    """
    m.safe_inc(
        vre_reports_generated_total, 1,
        report_type=report_type, format=format,
    )


def observe_rules_per_set(count: int) -> None:
    """Record the number of rules in a newly created or updated rule set.

    Args:
        count: Number of rules contained in the rule set.
    """
    m.safe_observe(vre_rules_per_set, count)


def observe_evaluation_duration(operation: str, seconds: float) -> None:
    """Record the duration of a rule evaluation operation.

    Args:
        operation: Evaluation operation type label
            (single_rule, rule_set, compound_rule, batch,
            cross_field, conditional, full_pipeline).
        seconds: Evaluation wall-clock time in seconds.
    """
    m.safe_observe(vre_evaluation_duration_seconds, seconds, operation=operation)


def observe_processing_duration(operation: str, seconds: float) -> None:
    """Record processing duration for a single engine operation.

    Args:
        operation: Operation type label
            (rule_register, rule_update, rule_delete, set_create,
            set_update, conflict_detect, conflict_resolve,
            report_generate, pack_import, pack_export,
            rule_activate, rule_deactivate).
        seconds: Operation duration in seconds.
    """
    m.safe_observe(vre_processing_duration_seconds, seconds, operation=operation)


def set_active_rules(count: int) -> None:
    """Set the gauge for current number of active validation rules.

    Args:
        count: Number of active validation rules currently loaded
            in the engine. Must be >= 0.
    """
    m.safe_set(vre_active_rules, count)


def set_active_rule_sets(count: int) -> None:
    """Set the gauge for current number of active rule sets.

    Args:
        count: Number of active rule sets currently loaded
            in the engine. Must be >= 0.
    """
    m.safe_set(vre_active_rule_sets, count)


def set_pass_rate(rate: float) -> None:
    """Set the gauge for current overall evaluation pass rate.

    Args:
        rate: Pass rate as a float between 0.0 (all fail) and
            1.0 (all pass).
    """
    m.safe_set(vre_pass_rate, rate)


__all__ = [
    "PROMETHEUS_AVAILABLE",
    "m",
    # Metric objects
    "vre_rules_registered_total",
    "vre_rule_sets_created_total",
    "vre_evaluations_total",
    "vre_evaluation_failures_total",
    "vre_conflicts_detected_total",
    "vre_reports_generated_total",
    "vre_rules_per_set",
    "vre_evaluation_duration_seconds",
    "vre_processing_duration_seconds",
    "vre_active_rules",
    "vre_active_rule_sets",
    "vre_pass_rate",
    # Helper functions
    "record_rule_registered",
    "record_rule_set_created",
    "record_evaluation",
    "record_evaluation_failure",
    "record_conflict_detected",
    "record_report_generated",
    "observe_rules_per_set",
    "observe_evaluation_duration",
    "observe_processing_duration",
    "set_active_rules",
    "set_active_rule_sets",
    "set_pass_rate",
]
