# -*- coding: utf-8 -*-
"""
GL-CBAM-APP Quarterly Automation Engine - Data Models v1.1

Pydantic models, enums, and constants for quarterly CBAM report generation,
deadline tracking, amendment management, and EU CBAM Registry format output.

Per EU CBAM Regulation 2023/956 Articles 6-8 (quarterly reporting obligation)
and Implementing Regulation 2023/1773 Articles 3-7 (report content, deadlines).

Transitional period: Oct 2023 - Dec 2025 (simplified reporting)
Definitive period: Jan 2026+ (full reporting with CBAM certificates)

All monetary and emissions values use Decimal with ROUND_HALF_UP to prevent
floating-point drift in regulatory calculations.

Version: 1.1.0
Author: GreenLang CBAM Team
License: Proprietary
"""

import hashlib
import json
import logging
from datetime import date, datetime, timezone
from decimal import Decimal, ROUND_HALF_UP
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, field_validator, model_validator

logger = logging.getLogger(__name__)


# ============================================================================
# ENUMS
# ============================================================================

class QuarterlyPeriod(str, Enum):
    """CBAM quarterly reporting periods per Regulation 2023/956 Article 6."""

    Q1 = "Q1"
    Q2 = "Q2"
    Q3 = "Q3"
    Q4 = "Q4"

    @property
    def start_month(self) -> int:
        """Return the first month of this quarter (1-indexed)."""
        return QUARTER_MONTHS[self][0]

    @property
    def end_month(self) -> int:
        """Return the last month of this quarter (1-indexed)."""
        return QUARTER_MONTHS[self][2]

    @property
    def label(self) -> str:
        """Human-readable label for the quarter."""
        labels = {
            QuarterlyPeriod.Q1: "January - March",
            QuarterlyPeriod.Q2: "April - June",
            QuarterlyPeriod.Q3: "July - September",
            QuarterlyPeriod.Q4: "October - December",
        }
        return labels[self]


class ReportStatus(str, Enum):
    """
    Report lifecycle status per Implementing Regulation 2023/1773 Article 8.

    Lifecycle: draft -> in_review -> submitted -> accepted/rejected -> amended
    """

    DRAFT = "draft"
    IN_REVIEW = "in_review"
    SUBMITTED = "submitted"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    AMENDED = "amended"

    @property
    def is_terminal(self) -> bool:
        """Whether this status represents a terminal state."""
        return self in {ReportStatus.ACCEPTED}

    @property
    def is_editable(self) -> bool:
        """Whether the report can be modified in this status."""
        return self in {ReportStatus.DRAFT, ReportStatus.REJECTED, ReportStatus.AMENDED}

    @property
    def allows_amendment(self) -> bool:
        """Whether an amendment can be created from this status."""
        return self in {ReportStatus.SUBMITTED, ReportStatus.ACCEPTED, ReportStatus.REJECTED}


class AmendmentReason(str, Enum):
    """
    Reasons for amending a submitted CBAM quarterly report.
    Per Implementing Regulation 2023/1773 Article 9 (corrections).
    """

    DATA_CORRECTION = "data_correction"
    CALCULATION_ERROR = "calculation_error"
    NEW_SUPPLIER_DATA = "new_supplier_data"
    REGULATORY_UPDATE = "regulatory_update"
    VERIFIER_FINDING = "verifier_finding"

    @property
    def description(self) -> str:
        """Human-readable description for audit trail."""
        descriptions = {
            AmendmentReason.DATA_CORRECTION: "Correction of input data errors",
            AmendmentReason.CALCULATION_ERROR: "Correction of calculation methodology error",
            AmendmentReason.NEW_SUPPLIER_DATA: "Incorporation of newly received supplier actual data",
            AmendmentReason.REGULATORY_UPDATE: "Adaptation to updated regulatory guidance or default values",
            AmendmentReason.VERIFIER_FINDING: "Correction based on third-party verifier finding",
        }
        return descriptions[self]


class NotificationType(str, Enum):
    """Types of notifications generated by the deadline tracker."""

    DEADLINE_APPROACHING = "deadline_approaching"
    DEADLINE_OVERDUE = "deadline_overdue"
    REPORT_ACCEPTED = "report_accepted"
    REPORT_REJECTED = "report_rejected"
    AMENDMENT_REQUIRED = "amendment_required"

    @property
    def default_subject(self) -> str:
        """Default email/notification subject line."""
        subjects = {
            NotificationType.DEADLINE_APPROACHING: "CBAM Report Submission Deadline Approaching",
            NotificationType.DEADLINE_OVERDUE: "CBAM Report Submission Overdue - Action Required",
            NotificationType.REPORT_ACCEPTED: "CBAM Quarterly Report Accepted",
            NotificationType.REPORT_REJECTED: "CBAM Quarterly Report Rejected - Resubmission Required",
            NotificationType.AMENDMENT_REQUIRED: "CBAM Report Amendment Required",
        }
        return subjects[self]


class AlertLevel(str, Enum):
    """Severity levels for deadline alerts, mapped to notification urgency."""

    INFO = "info"
    WARNING = "warning"
    URGENT = "urgent"
    CRITICAL = "critical"

    @property
    def priority_order(self) -> int:
        """Numeric priority for sorting (lower = higher priority)."""
        order = {
            AlertLevel.CRITICAL: 0,
            AlertLevel.URGENT: 1,
            AlertLevel.WARNING: 2,
            AlertLevel.INFO: 3,
        }
        return order[self]


class CBAMSector(str, Enum):
    """
    CBAM product sectors per Regulation 2023/956 Annex I.
    Six sectors covered by CBAM.
    """

    CEMENT = "cement"
    IRON_AND_STEEL = "iron_and_steel"
    ALUMINUM = "aluminum"
    FERTILIZERS = "fertilizers"
    HYDROGEN = "hydrogen"
    ELECTRICITY = "electricity"


class CalculationMethod(str, Enum):
    """Emissions calculation method hierarchy per CBAM Regulation."""

    SUPPLIER_ACTUAL = "supplier_actual"
    REGIONAL_FACTOR = "regional_factor"
    DEFAULT_VALUE = "default_value"
    ESTIMATION = "estimation"

    @property
    def data_quality_rank(self) -> int:
        """Data quality ranking (1 = best)."""
        ranks = {
            CalculationMethod.SUPPLIER_ACTUAL: 1,
            CalculationMethod.REGIONAL_FACTOR: 2,
            CalculationMethod.DEFAULT_VALUE: 3,
            CalculationMethod.ESTIMATION: 4,
        }
        return ranks[self]


# ============================================================================
# CONSTANTS
# ============================================================================

QUARTER_MONTHS: Dict[QuarterlyPeriod, tuple] = {
    QuarterlyPeriod.Q1: (1, 2, 3),
    QuarterlyPeriod.Q2: (4, 5, 6),
    QuarterlyPeriod.Q3: (7, 8, 9),
    QuarterlyPeriod.Q4: (10, 11, 12),
}

# Submission deadline: 30 calendar days after end of quarter
# Per Implementing Regulation 2023/1773 Article 6(1)
SUBMISSION_DEADLINE_DAYS: int = 30

# Amendment window: 60 calendar days after end of quarter
# Per Implementing Regulation 2023/1773 Article 9
AMENDMENT_WINDOW_DAYS: int = 60

# Alert thresholds in days before submission deadline
# Triggers escalating notifications as deadline approaches
ALERT_THRESHOLDS: Dict[AlertLevel, int] = {
    AlertLevel.INFO: 30,
    AlertLevel.WARNING: 14,
    AlertLevel.URGENT: 7,
    AlertLevel.CRITICAL: 3,
}

# Additional critical threshold at T-1 day
FINAL_WARNING_DAYS: int = 1

# Transitional period end date (per Regulation 2023/956 Article 32)
TRANSITIONAL_PERIOD_END: date = date(2025, 12, 31)

# Definitive period start date
DEFINITIVE_PERIOD_START: date = date(2026, 1, 1)

# CBAM reporting start date (first quarter of transitional period)
CBAM_REPORTING_START: date = date(2023, 10, 1)

# Default value markup percentages by year (transitional period)
# Per Implementing Regulation 2023/1773 Article 4(3)
DEFAULT_VALUE_MARKUP_PCT: Dict[int, Decimal] = {
    2024: Decimal("10"),   # +10% in 2024
    2025: Decimal("20"),   # +20% in 2025
    2026: Decimal("30"),   # +30% in 2026 (definitive period)
}

# Complex goods threshold percentage
# Per Regulation 2023/956 Article 7(3) - 20% rule for precursors
COMPLEX_GOODS_THRESHOLD_PCT: Decimal = Decimal("20.0")

# Maximum report versions before requiring manual review
MAX_AMENDMENT_VERSIONS: int = 10

# Report ID format prefix
REPORT_ID_PREFIX: str = "CBAM-QR"

# XML namespace for EU CBAM Registry format
CBAM_XML_NAMESPACE: str = "urn:eu:ec:cbam:registry:quarterly:v1"

# Valid status transitions
VALID_STATUS_TRANSITIONS: Dict[ReportStatus, List[ReportStatus]] = {
    ReportStatus.DRAFT: [ReportStatus.IN_REVIEW],
    ReportStatus.IN_REVIEW: [ReportStatus.DRAFT, ReportStatus.SUBMITTED],
    ReportStatus.SUBMITTED: [ReportStatus.ACCEPTED, ReportStatus.REJECTED],
    ReportStatus.ACCEPTED: [ReportStatus.AMENDED],
    ReportStatus.REJECTED: [ReportStatus.DRAFT, ReportStatus.AMENDED],
    ReportStatus.AMENDED: [ReportStatus.IN_REVIEW],
}


# ============================================================================
# PYDANTIC MODELS
# ============================================================================

class QuarterlyReportPeriod(BaseModel):
    """
    Represents a CBAM quarterly reporting period with computed deadlines.

    Per EU CBAM Regulation 2023/956 Article 6 and Implementing Regulation
    2023/1773 Articles 3-7, importers must submit quarterly reports within
    30 days after the end of each quarter.

    Attributes:
        year: Reporting year (2023-2099).
        quarter: Quarter identifier (Q1-Q4).
        start_date: First day of the quarter.
        end_date: Last day of the quarter.
        submission_deadline: T+30 days after quarter end.
        amendment_deadline: T+60 days after quarter end.
        is_transitional: True if period falls within the transitional phase.
    """

    year: int = Field(
        ...,
        ge=2023,
        le=2099,
        description="Reporting year (CBAM starts Q4 2023)"
    )
    quarter: QuarterlyPeriod = Field(
        ...,
        description="Quarter identifier"
    )
    start_date: date = Field(
        ...,
        description="First calendar day of the reporting quarter"
    )
    end_date: date = Field(
        ...,
        description="Last calendar day of the reporting quarter"
    )
    submission_deadline: date = Field(
        ...,
        description="Submission deadline (T+30 after quarter end)"
    )
    amendment_deadline: date = Field(
        ...,
        description="Amendment window deadline (T+60 after quarter end)"
    )
    is_transitional: bool = Field(
        ...,
        description="Whether this period falls in the CBAM transitional phase (before Jan 2026)"
    )

    @field_validator("year")
    @classmethod
    def validate_year_range(cls, v: int) -> int:
        """Validate year is within CBAM reporting range."""
        if v < 2023:
            raise ValueError("CBAM reporting began in Q4 2023")
        return v

    @model_validator(mode="after")
    def validate_dates_consistent(self) -> "QuarterlyReportPeriod":
        """Validate that start_date < end_date and deadlines are after end_date."""
        if self.start_date >= self.end_date:
            raise ValueError(
                f"start_date ({self.start_date}) must be before end_date ({self.end_date})"
            )
        if self.submission_deadline <= self.end_date:
            raise ValueError(
                f"submission_deadline ({self.submission_deadline}) must be after end_date ({self.end_date})"
            )
        if self.amendment_deadline <= self.submission_deadline:
            raise ValueError(
                f"amendment_deadline ({self.amendment_deadline}) must be after "
                f"submission_deadline ({self.submission_deadline})"
            )
        return self

    @property
    def period_label(self) -> str:
        """Human-readable period label, e.g., '2025Q4'."""
        return f"{self.year}{self.quarter.value}"

    @property
    def is_definitive(self) -> bool:
        """Whether this period falls in the definitive phase (Jan 2026+)."""
        return not self.is_transitional

    class Config:
        """Pydantic model configuration."""
        frozen = True
        json_schema_extra = {
            "example": {
                "year": 2025,
                "quarter": "Q4",
                "start_date": "2025-10-01",
                "end_date": "2025-12-31",
                "submission_deadline": "2026-01-30",
                "amendment_deadline": "2026-03-01",
                "is_transitional": True,
            }
        }


class ShipmentAggregation(BaseModel):
    """
    Aggregated shipment data grouped by CN code, country, installation, or sector.

    Per Implementing Regulation 2023/1773 Article 3(2), quarterly reports must
    aggregate goods imported by CN code within each product category.

    All emissions values use Decimal to avoid floating-point precision issues.

    Attributes:
        cn_code: 8-digit Combined Nomenclature code.
        cn_description: Human-readable description of the CN code.
        country_of_origin: ISO 3166-1 alpha-2 country code.
        installation_id: EU CBAM Registry installation identifier.
        product_group: CBAM sector classification.
        quantity_mt: Total quantity in metric tonnes.
        direct_emissions_tCO2e: Total direct (Scope 1) emissions.
        indirect_emissions_tCO2e: Total indirect (Scope 2) emissions.
        total_emissions_tCO2e: Sum of direct + indirect emissions.
        embedded_emissions_per_mt: Emissions intensity per metric tonne.
        calculation_method: Primary calculation method used.
        default_values_used_pct: Percentage of quantity using default EFs.
        supplier_data_quality_score: Weighted quality score 0.0-1.0.
    """

    cn_code: str = Field(
        ...,
        min_length=2,
        max_length=10,
        description="Combined Nomenclature code (6-10 digits) or 'MIXED' for multi-code aggregations"
    )
    cn_description: str = Field(
        default="",
        description="Human-readable CN code description"
    )
    country_of_origin: str = Field(
        ...,
        min_length=2,
        max_length=2,
        description="ISO 3166-1 alpha-2 country code"
    )
    installation_id: Optional[str] = Field(
        default=None,
        description="EU CBAM Registry installation identifier"
    )
    product_group: CBAMSector = Field(
        ...,
        description="CBAM product sector classification"
    )
    quantity_mt: Decimal = Field(
        ...,
        ge=0,
        description="Total quantity in metric tonnes"
    )
    direct_emissions_tCO2e: Decimal = Field(
        ...,
        ge=0,
        description="Total direct (Scope 1) embedded emissions in tCO2e"
    )
    indirect_emissions_tCO2e: Decimal = Field(
        ...,
        ge=0,
        description="Total indirect (Scope 2) embedded emissions in tCO2e"
    )
    total_emissions_tCO2e: Decimal = Field(
        ...,
        ge=0,
        description="Total embedded emissions (direct + indirect) in tCO2e"
    )
    embedded_emissions_per_mt: Decimal = Field(
        ...,
        ge=0,
        description="Specific embedded emissions per metric tonne (tCO2e/t)"
    )
    calculation_method: CalculationMethod = Field(
        ...,
        description="Primary calculation method used for this aggregation"
    )
    default_values_used_pct: Decimal = Field(
        default=Decimal("0"),
        ge=0,
        le=100,
        description="Percentage of quantity using EU default emission factors"
    )
    supplier_data_quality_score: Decimal = Field(
        default=Decimal("0"),
        ge=0,
        le=1,
        description="Weighted data quality score (0.0=lowest, 1.0=highest)"
    )

    @model_validator(mode="after")
    def validate_emissions_consistency(self) -> "ShipmentAggregation":
        """Validate that total emissions equals sum of direct + indirect."""
        expected_total = (
            self.direct_emissions_tCO2e + self.indirect_emissions_tCO2e
        )
        tolerance = Decimal("0.01")
        if abs(self.total_emissions_tCO2e - expected_total) > tolerance:
            raise ValueError(
                f"total_emissions_tCO2e ({self.total_emissions_tCO2e}) must equal "
                f"direct ({self.direct_emissions_tCO2e}) + indirect "
                f"({self.indirect_emissions_tCO2e}) = {expected_total}"
            )
        return self

    @model_validator(mode="after")
    def validate_intensity(self) -> "ShipmentAggregation":
        """Validate embedded emissions intensity is consistent with totals."""
        if self.quantity_mt > 0:
            expected_intensity = (
                self.total_emissions_tCO2e / self.quantity_mt
            ).quantize(Decimal("0.000001"), rounding=ROUND_HALF_UP)
            actual_intensity = self.embedded_emissions_per_mt.quantize(
                Decimal("0.000001"), rounding=ROUND_HALF_UP
            )
            tolerance = Decimal("0.01")
            if abs(actual_intensity - expected_intensity) > tolerance:
                raise ValueError(
                    f"embedded_emissions_per_mt ({self.embedded_emissions_per_mt}) "
                    f"inconsistent with total/quantity = {expected_intensity}"
                )
        return self

    class Config:
        """Pydantic model configuration."""
        json_schema_extra = {
            "example": {
                "cn_code": "72031000",
                "cn_description": "Ferrous products obtained by direct reduction of iron ore",
                "country_of_origin": "TR",
                "installation_id": "CBAM-TR-INSTALL-001",
                "product_group": "iron_and_steel",
                "quantity_mt": "1500.000",
                "direct_emissions_tCO2e": "2775.000",
                "indirect_emissions_tCO2e": "225.000",
                "total_emissions_tCO2e": "3000.000",
                "embedded_emissions_per_mt": "2.000",
                "calculation_method": "supplier_actual",
                "default_values_used_pct": "0",
                "supplier_data_quality_score": "0.85",
            }
        }


class QuarterlyReport(BaseModel):
    """
    Complete CBAM quarterly report model.

    Per Implementing Regulation 2023/1773 Articles 3-5, a quarterly report
    contains identification of the importer, goods imported (by CN code
    and origin), and embedded emissions calculations.

    Attributes:
        report_id: Unique report identifier (format: CBAM-QR-{year}{quarter}-{importer}-{ts}).
        period: The quarterly reporting period.
        importer_id: Importer EORI number or internal identifier.
        status: Current lifecycle status.
        shipments_count: Total number of shipments in the report.
        total_quantity_mt: Total imported quantity in metric tonnes.
        aggregations: List of shipment aggregations by CN code/country.
        total_direct_emissions: Sum of all direct emissions in tCO2e.
        total_indirect_emissions: Sum of all indirect emissions in tCO2e.
        total_embedded_emissions: Grand total embedded emissions in tCO2e.
        calculation_methods_used: Map of calculation method to shipment count.
        report_xml: XML output in EU CBAM Registry format.
        report_summary_md: Human-readable Markdown summary.
        version: Report version (incremented on amendment).
        created_at: UTC timestamp of report creation.
        submitted_at: UTC timestamp of submission (None if not submitted).
        provenance_hash: SHA-256 hash of report content for integrity.
    """

    report_id: str = Field(
        ...,
        min_length=10,
        description="Unique report identifier"
    )
    period: QuarterlyReportPeriod = Field(
        ...,
        description="The quarterly reporting period"
    )
    importer_id: str = Field(
        ...,
        min_length=1,
        description="Importer EORI number or internal identifier"
    )
    status: ReportStatus = Field(
        default=ReportStatus.DRAFT,
        description="Current report lifecycle status"
    )
    shipments_count: int = Field(
        default=0,
        ge=0,
        description="Total number of shipments included"
    )
    total_quantity_mt: Decimal = Field(
        default=Decimal("0"),
        ge=0,
        description="Total imported quantity in metric tonnes"
    )
    aggregations: List[ShipmentAggregation] = Field(
        default_factory=list,
        description="Shipment aggregations by CN code and origin country"
    )
    total_direct_emissions: Decimal = Field(
        default=Decimal("0"),
        ge=0,
        description="Total direct (Scope 1) embedded emissions in tCO2e"
    )
    total_indirect_emissions: Decimal = Field(
        default=Decimal("0"),
        ge=0,
        description="Total indirect (Scope 2) embedded emissions in tCO2e"
    )
    total_embedded_emissions: Decimal = Field(
        default=Decimal("0"),
        ge=0,
        description="Grand total embedded emissions in tCO2e"
    )
    calculation_methods_used: Dict[str, int] = Field(
        default_factory=dict,
        description="Map of CalculationMethod value to shipment count"
    )
    report_xml: Optional[str] = Field(
        default=None,
        description="XML output in EU CBAM Registry format"
    )
    report_summary_md: Optional[str] = Field(
        default=None,
        description="Human-readable Markdown summary"
    )
    version: int = Field(
        default=1,
        ge=1,
        le=MAX_AMENDMENT_VERSIONS,
        description="Report version (incremented on each amendment)"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of report creation"
    )
    submitted_at: Optional[datetime] = Field(
        default=None,
        description="UTC timestamp of report submission"
    )
    provenance_hash: str = Field(
        default="",
        description="SHA-256 hash of report content for integrity verification"
    )

    @model_validator(mode="after")
    def validate_emissions_totals(self) -> "QuarterlyReport":
        """Validate that total embedded equals direct + indirect."""
        if self.aggregations:
            expected = self.total_direct_emissions + self.total_indirect_emissions
            tolerance = Decimal("0.01")
            if abs(self.total_embedded_emissions - expected) > tolerance:
                raise ValueError(
                    f"total_embedded_emissions ({self.total_embedded_emissions}) must equal "
                    f"direct ({self.total_direct_emissions}) + indirect "
                    f"({self.total_indirect_emissions}) = {expected}"
                )
        return self

    @model_validator(mode="after")
    def validate_submitted_status(self) -> "QuarterlyReport":
        """Validate submitted_at is set when status is submitted or beyond."""
        post_submission = {
            ReportStatus.SUBMITTED,
            ReportStatus.ACCEPTED,
            ReportStatus.REJECTED,
        }
        if self.status in post_submission and self.submitted_at is None:
            raise ValueError(
                f"submitted_at must be set when status is {self.status.value}"
            )
        return self

    def compute_provenance_hash(self) -> str:
        """
        Compute SHA-256 hash of report content for integrity verification.

        Includes all material fields except the hash itself and mutable timestamps.
        This is a ZERO-HALLUCINATION deterministic computation.

        Returns:
            Hexadecimal SHA-256 hash string.
        """
        hash_payload = {
            "report_id": self.report_id,
            "period_label": self.period.period_label,
            "importer_id": self.importer_id,
            "shipments_count": self.shipments_count,
            "total_quantity_mt": str(self.total_quantity_mt),
            "total_direct_emissions": str(self.total_direct_emissions),
            "total_indirect_emissions": str(self.total_indirect_emissions),
            "total_embedded_emissions": str(self.total_embedded_emissions),
            "version": self.version,
            "aggregation_count": len(self.aggregations),
        }
        payload_str = json.dumps(hash_payload, sort_keys=True)
        return hashlib.sha256(payload_str.encode("utf-8")).hexdigest()

    class Config:
        """Pydantic model configuration."""
        json_schema_extra = {
            "example": {
                "report_id": "CBAM-QR-2025Q4-NL123456789012-20260115120000",
                "importer_id": "NL123456789012",
                "status": "draft",
                "shipments_count": 45,
                "total_quantity_mt": "12500.000",
                "total_direct_emissions": "23125.000",
                "total_indirect_emissions": "1875.000",
                "total_embedded_emissions": "25000.000",
                "version": 1,
            }
        }


class ReportAmendment(BaseModel):
    """
    Versioned amendment to a submitted CBAM quarterly report.

    Per Implementing Regulation 2023/1773 Article 9, importers may amend
    submitted reports within the amendment window (T+60 days).

    Each amendment creates a new version and preserves the full diff for audit.

    Attributes:
        amendment_id: Unique amendment identifier.
        report_id: The report being amended.
        version: New version number after this amendment.
        reason: Categorized reason for the amendment.
        changes_summary: Human-readable description of changes.
        diff_data: Structured diff between old and new versions.
        amended_by: User or system identifier who created the amendment.
        amended_at: UTC timestamp of amendment creation.
        previous_hash: SHA-256 hash of the report before amendment.
        new_hash: SHA-256 hash of the report after amendment.
    """

    amendment_id: str = Field(
        ...,
        min_length=5,
        description="Unique amendment identifier"
    )
    report_id: str = Field(
        ...,
        description="Report ID being amended"
    )
    version: int = Field(
        ...,
        ge=2,
        le=MAX_AMENDMENT_VERSIONS,
        description="New version number after amendment (must be >= 2)"
    )
    reason: AmendmentReason = Field(
        ...,
        description="Categorized reason for the amendment"
    )
    changes_summary: str = Field(
        ...,
        min_length=10,
        description="Human-readable description of what changed and why"
    )
    diff_data: Dict[str, Any] = Field(
        default_factory=dict,
        description="Structured diff: {field: {old: ..., new: ...}}"
    )
    amended_by: str = Field(
        ...,
        min_length=1,
        description="User or system identifier who created the amendment"
    )
    amended_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of amendment creation"
    )
    previous_hash: str = Field(
        ...,
        min_length=64,
        max_length=64,
        description="SHA-256 hash of the report before amendment"
    )
    new_hash: str = Field(
        ...,
        min_length=64,
        max_length=64,
        description="SHA-256 hash of the report after amendment"
    )

    @field_validator("previous_hash", "new_hash")
    @classmethod
    def validate_hash_format(cls, v: str) -> str:
        """Validate hash is a valid hexadecimal SHA-256 string."""
        if len(v) != 64:
            raise ValueError(f"SHA-256 hash must be 64 hex characters, got {len(v)}")
        try:
            int(v, 16)
        except ValueError:
            raise ValueError("SHA-256 hash must contain only hexadecimal characters")
        return v.lower()

    @model_validator(mode="after")
    def validate_hashes_differ(self) -> "ReportAmendment":
        """Validate that the amendment actually changed the report."""
        if self.previous_hash == self.new_hash:
            raise ValueError(
                "previous_hash and new_hash must differ (amendment must change report)"
            )
        return self

    def compute_amendment_hash(self) -> str:
        """
        Compute SHA-256 hash of the amendment itself for audit chain.

        Returns:
            Hexadecimal SHA-256 hash string.
        """
        payload = {
            "amendment_id": self.amendment_id,
            "report_id": self.report_id,
            "version": self.version,
            "reason": self.reason.value,
            "previous_hash": self.previous_hash,
            "new_hash": self.new_hash,
            "amended_by": self.amended_by,
            "amended_at": self.amended_at.isoformat(),
        }
        payload_str = json.dumps(payload, sort_keys=True)
        return hashlib.sha256(payload_str.encode("utf-8")).hexdigest()

    class Config:
        """Pydantic model configuration."""
        json_schema_extra = {
            "example": {
                "amendment_id": "AMEND-2025Q4-NL123-002",
                "report_id": "CBAM-QR-2025Q4-NL123456789012-20260115120000",
                "version": 2,
                "reason": "new_supplier_data",
                "changes_summary": "Updated steel emissions for installation TR-001 with verified supplier EPD data",
                "amended_by": "compliance-officer@acme.eu",
                "previous_hash": "a" * 64,
                "new_hash": "b" * 64,
            }
        }


class DeadlineAlert(BaseModel):
    """
    Deadline alert/notification for an upcoming or overdue CBAM report.

    The deadline tracker generates alerts at configured thresholds
    (30, 14, 7, 3, 1 days before deadline) with escalating severity.

    Attributes:
        alert_id: Unique alert identifier.
        report_period: The quarterly period this alert relates to.
        alert_level: Severity level of the alert.
        notification_type: Type of notification.
        days_remaining: Days until (positive) or past (negative) the deadline.
        message: Human-readable alert message.
        recipients: List of email addresses or webhook URLs to notify.
        sent_at: UTC timestamp when alert was sent (None if pending).
        acknowledged: Whether the alert has been acknowledged by a user.
    """

    alert_id: str = Field(
        ...,
        min_length=5,
        description="Unique alert identifier"
    )
    report_period: QuarterlyReportPeriod = Field(
        ...,
        description="The quarterly period this alert relates to"
    )
    alert_level: AlertLevel = Field(
        ...,
        description="Severity level of the alert"
    )
    notification_type: NotificationType = Field(
        ...,
        description="Type of notification"
    )
    days_remaining: int = Field(
        ...,
        description="Days until deadline (positive) or days overdue (negative)"
    )
    message: str = Field(
        ...,
        min_length=10,
        description="Human-readable alert message"
    )
    recipients: List[str] = Field(
        default_factory=list,
        description="List of email addresses or webhook URLs to notify"
    )
    sent_at: Optional[datetime] = Field(
        default=None,
        description="UTC timestamp when alert was sent"
    )
    acknowledged: bool = Field(
        default=False,
        description="Whether the alert has been acknowledged by a user"
    )

    @field_validator("recipients")
    @classmethod
    def validate_recipients_not_empty(cls, v: List[str]) -> List[str]:
        """Validate that at least one recipient is provided."""
        if not v:
            raise ValueError("At least one recipient must be specified")
        return v

    class Config:
        """Pydantic model configuration."""
        json_schema_extra = {
            "example": {
                "alert_id": "ALERT-2025Q4-NL123-003",
                "alert_level": "urgent",
                "notification_type": "deadline_approaching",
                "days_remaining": 7,
                "message": "CBAM report for Q4 2025 is due in 7 days (2026-01-30)",
                "recipients": ["compliance@acme.eu"],
                "acknowledged": False,
            }
        }


class NotificationConfig(BaseModel):
    """
    Notification routing configuration for an importer.

    Configures which recipients receive which types of notifications,
    and via which channels (email, webhook, etc.).

    Attributes:
        importer_id: The importer this configuration belongs to.
        email_recipients: Email addresses for notifications.
        webhook_urls: Webhook endpoints for external integrations.
        alert_levels_enabled: Which alert levels trigger notifications.
        notification_types_enabled: Which notification types are active.
        quiet_hours_start: Start of quiet hours (notifications held, UTC hour).
        quiet_hours_end: End of quiet hours (UTC hour).
    """

    importer_id: str = Field(
        ...,
        description="Importer EORI or internal identifier"
    )
    email_recipients: List[str] = Field(
        default_factory=list,
        description="Email addresses for notifications"
    )
    webhook_urls: List[str] = Field(
        default_factory=list,
        description="Webhook endpoints for external integrations"
    )
    alert_levels_enabled: List[AlertLevel] = Field(
        default_factory=lambda: list(AlertLevel),
        description="Which alert levels trigger notifications"
    )
    notification_types_enabled: List[NotificationType] = Field(
        default_factory=lambda: list(NotificationType),
        description="Which notification types are active"
    )
    quiet_hours_start: Optional[int] = Field(
        default=None,
        ge=0,
        le=23,
        description="Start of quiet hours (UTC hour, 0-23)"
    )
    quiet_hours_end: Optional[int] = Field(
        default=None,
        ge=0,
        le=23,
        description="End of quiet hours (UTC hour, 0-23)"
    )

    class Config:
        """Pydantic model configuration."""
        json_schema_extra = {
            "example": {
                "importer_id": "NL123456789012",
                "email_recipients": ["compliance@acme.eu", "legal@acme.eu"],
                "webhook_urls": ["https://hooks.slack.com/services/xxx"],
                "alert_levels_enabled": ["warning", "urgent", "critical"],
                "notification_types_enabled": [
                    "deadline_approaching",
                    "deadline_overdue",
                    "report_rejected",
                ],
            }
        }


class NotificationLogEntry(BaseModel):
    """
    Log entry for a sent notification, for audit trail.

    Attributes:
        log_id: Unique log entry identifier.
        alert_id: Related alert identifier (if applicable).
        importer_id: Importer identifier.
        notification_type: Type of notification sent.
        channel: Delivery channel (email, webhook, etc.).
        recipient: Specific recipient address/URL.
        subject: Notification subject line.
        body: Notification body content.
        sent_at: UTC timestamp of delivery.
        delivery_status: Delivery status (sent, failed, bounced).
        error_message: Error details if delivery failed.
    """

    log_id: str = Field(..., description="Unique log entry identifier")
    alert_id: Optional[str] = Field(default=None, description="Related alert ID")
    importer_id: str = Field(..., description="Importer identifier")
    notification_type: NotificationType = Field(..., description="Notification type")
    channel: str = Field(..., description="Delivery channel (email/webhook)")
    recipient: str = Field(..., description="Recipient address or URL")
    subject: str = Field(..., description="Notification subject")
    body: str = Field(default="", description="Notification body content")
    sent_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of delivery"
    )
    delivery_status: str = Field(
        default="sent",
        description="Delivery status: sent, failed, bounced"
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Error details if delivery failed"
    )

    class Config:
        """Pydantic model configuration."""
        json_schema_extra = {
            "example": {
                "log_id": "LOG-20260123-001",
                "alert_id": "ALERT-2025Q4-NL123-003",
                "importer_id": "NL123456789012",
                "notification_type": "deadline_approaching",
                "channel": "email",
                "recipient": "compliance@acme.eu",
                "subject": "CBAM Report Submission Deadline Approaching",
                "delivery_status": "sent",
            }
        }


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def compute_sha256(data: Union[str, bytes, dict]) -> str:
    """
    Compute SHA-256 hash of arbitrary data.

    This is a ZERO-HALLUCINATION deterministic computation.

    Args:
        data: String, bytes, or dict to hash. Dicts are JSON-serialized
              with sorted keys for deterministic output.

    Returns:
        Hexadecimal SHA-256 hash string (64 characters).
    """
    if isinstance(data, dict):
        data = json.dumps(data, sort_keys=True, default=str)
    if isinstance(data, str):
        data = data.encode("utf-8")
    return hashlib.sha256(data).hexdigest()


def quantize_decimal(
    value: Union[Decimal, float, str],
    places: int = 3
) -> Decimal:
    """
    Quantize a value to the specified number of decimal places using ROUND_HALF_UP.

    This is the standard rounding method for CBAM regulatory calculations
    to ensure consistency across implementations.

    Args:
        value: The value to quantize.
        places: Number of decimal places (default: 3 for metric tonnes).

    Returns:
        Quantized Decimal value.
    """
    if not isinstance(value, Decimal):
        value = Decimal(str(value))
    quantizer = Decimal(10) ** -places
    return value.quantize(quantizer, rounding=ROUND_HALF_UP)


def validate_status_transition(
    current: ReportStatus,
    target: ReportStatus
) -> bool:
    """
    Validate that a status transition is allowed.

    Args:
        current: Current report status.
        target: Target report status.

    Returns:
        True if the transition is valid.

    Raises:
        ValueError: If the transition is not allowed.
    """
    allowed = VALID_STATUS_TRANSITIONS.get(current, [])
    if target not in allowed:
        raise ValueError(
            f"Invalid status transition: {current.value} -> {target.value}. "
            f"Allowed transitions from {current.value}: "
            f"{[s.value for s in allowed]}"
        )
    return True
