# -*- coding: utf-8 -*-
"""
GL-CBAM-APP Notification Service v1.1

Multi-channel notification delivery for CBAM quarterly report lifecycle events.
Supports email, webhook, and extensible channel types. Includes template
rendering, notification routing, delivery tracking, and audit logging.

Notification triggers:
  - Deadline approaching (T-30, T-14, T-7, T-3, T-1 days)
  - Deadline overdue
  - Report accepted / rejected
  - Amendment required / processed

All operations are logged for regulatory audit compliance.

Version: 1.1.0
Author: GreenLang CBAM Team
License: Proprietary
"""

import json
import logging
import threading
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from .models import (
    AlertLevel,
    DeadlineAlert,
    NotificationConfig,
    NotificationLogEntry,
    NotificationType,
    QuarterlyReport,
    ReportAmendment,
    ReportStatus,
)

logger = logging.getLogger(__name__)


# ============================================================================
# EMAIL TEMPLATES
# ============================================================================

DEADLINE_APPROACHING_TEMPLATE = """Subject: {subject}

CBAM Quarterly Report - Deadline Reminder
==========================================

Dear {importer_id},

This is a reminder that your CBAM quarterly report for {period_label}
({quarter_label}) is due in {days_remaining} day(s).

Submission Deadline: {submission_deadline}
Amendment Deadline:  {amendment_deadline}
Phase:              {phase}

{message}

Action Required:
  1. Finalize your quarterly report data
  2. Review and validate emissions calculations
  3. Submit through the EU CBAM Transitional Registry

For assistance, contact your CBAM compliance team.

---
This notification was generated by GreenLang CBAM Importer Copilot v1.1.0.
Do not reply to this email.
"""

DEADLINE_OVERDUE_TEMPLATE = """Subject: {subject}

URGENT: CBAM Report OVERDUE
============================

Dear {importer_id},

Your CBAM quarterly report for {period_label} ({quarter_label}) is
OVERDUE by {days_overdue} day(s).

Original Deadline: {submission_deadline}
Days Overdue:      {days_overdue}

{message}

Non-compliance with EU CBAM Regulation 2023/956 Article 16 may result
in financial penalties. Please submit your report immediately.

Amendment Window: {amendment_deadline}
Window Status:    {amendment_status}

---
This notification was generated by GreenLang CBAM Importer Copilot v1.1.0.
"""

REPORT_STATUS_TEMPLATE = """Subject: {subject}

CBAM Report Status Update
==========================

Dear {importer_id},

Your CBAM quarterly report status has been updated:

Report ID:   {report_id}
Period:      {period_label}
New Status:  {status}
Updated At:  {updated_at}

{details}

---
This notification was generated by GreenLang CBAM Importer Copilot v1.1.0.
"""

AMENDMENT_TEMPLATE = """Subject: {subject}

CBAM Report Amendment Notification
=====================================

Dear {importer_id},

An amendment has been processed for your CBAM quarterly report:

Report ID:     {report_id}
Amendment ID:  {amendment_id}
Version:       {version}
Reason:        {reason}
Amended By:    {amended_by}
Amended At:    {amended_at}

Changes Summary:
{changes_summary}

Previous Hash: {previous_hash}
New Hash:      {new_hash}

---
This notification was generated by GreenLang CBAM Importer Copilot v1.1.0.
"""


class NotificationService:
    """
    Multi-channel notification service for CBAM quarterly report lifecycle.

    Manages notification routing, template rendering, delivery tracking,
    and audit logging across email and webhook channels.

    Thread Safety:
        Uses threading.RLock for all mutable state access.

    Example:
        >>> service = NotificationService()
        >>> service.configure_recipients("NL123", {
        ...     "email_recipients": ["compliance@acme.eu"],
        ...     "webhook_urls": ["https://hooks.slack.com/..."],
        ... })
        >>> success = service.send_deadline_notification(alert)
    """

    def __init__(self) -> None:
        """Initialize the notification service."""
        self._lock = threading.RLock()
        # importer_id -> NotificationConfig
        self._configs: Dict[str, NotificationConfig] = {}
        # Notification log: list of NotificationLogEntry
        self._notification_log: List[NotificationLogEntry] = []
        # Webhook handlers (extensible)
        self._webhook_handlers: Dict[str, Any] = {}
        logger.info("NotificationService initialized")

    # ========================================================================
    # CONFIGURATION
    # ========================================================================

    def configure_recipients(
        self,
        importer_id: str,
        config: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Set notification routing configuration for an importer.

        Args:
            importer_id: Importer EORI or internal identifier.
            config: Configuration dict with:
                - email_recipients: list of email addresses
                - webhook_urls: list of webhook endpoints
                - alert_levels_enabled: list of AlertLevel values
                - notification_types_enabled: list of NotificationType values
                - quiet_hours_start: UTC hour (0-23)
                - quiet_hours_end: UTC hour (0-23)

        Returns:
            Stored configuration as dict.
        """
        with self._lock:
            notification_config = NotificationConfig(
                importer_id=importer_id,
                email_recipients=config.get("email_recipients", []),
                webhook_urls=config.get("webhook_urls", []),
                alert_levels_enabled=[
                    AlertLevel(level) if isinstance(level, str) else level
                    for level in config.get("alert_levels_enabled", list(AlertLevel))
                ],
                notification_types_enabled=[
                    NotificationType(nt) if isinstance(nt, str) else nt
                    for nt in config.get(
                        "notification_types_enabled", list(NotificationType)
                    )
                ],
                quiet_hours_start=config.get("quiet_hours_start"),
                quiet_hours_end=config.get("quiet_hours_end"),
            )

            self._configs[importer_id] = notification_config

            logger.info(
                "Notification config set for %s: %d email, %d webhook recipients",
                importer_id,
                len(notification_config.email_recipients),
                len(notification_config.webhook_urls),
            )

            return notification_config.model_dump()

    def get_config(self, importer_id: str) -> Optional[NotificationConfig]:
        """
        Get the notification configuration for an importer.

        Args:
            importer_id: Importer identifier.

        Returns:
            NotificationConfig if configured, None otherwise.
        """
        with self._lock:
            return self._configs.get(importer_id)

    # ========================================================================
    # DEADLINE NOTIFICATIONS
    # ========================================================================

    def send_deadline_notification(
        self,
        alert: DeadlineAlert,
    ) -> bool:
        """
        Send a deadline notification based on a DeadlineAlert.

        Routes the notification to all configured channels for the
        importer. Respects quiet hours and enabled alert levels.

        Args:
            alert: The DeadlineAlert to send notifications for.

        Returns:
            True if at least one notification was delivered successfully.
        """
        # Extract importer_id from alert recipients or use a default
        importer_id = self._resolve_importer_from_alert(alert)
        config = self._get_or_default_config(importer_id)

        # Check if this alert level is enabled
        if alert.alert_level not in config.alert_levels_enabled:
            logger.debug(
                "Alert level %s not enabled for %s, skipping",
                alert.alert_level.value, importer_id,
            )
            return False

        # Check quiet hours
        if self._is_quiet_hours(config):
            logger.info(
                "Quiet hours active for %s, deferring notification", importer_id
            )
            return False

        # Determine template
        if alert.notification_type == NotificationType.DEADLINE_OVERDUE:
            template = DEADLINE_OVERDUE_TEMPLATE
        else:
            template = DEADLINE_APPROACHING_TEMPLATE

        period = alert.report_period
        phase = "Transitional" if period.is_transitional else "Definitive"

        template_vars = {
            "subject": alert.notification_type.default_subject,
            "importer_id": importer_id,
            "period_label": period.period_label,
            "quarter_label": period.quarter.label,
            "days_remaining": max(0, alert.days_remaining),
            "days_overdue": abs(min(0, alert.days_remaining)),
            "submission_deadline": period.submission_deadline.isoformat(),
            "amendment_deadline": period.amendment_deadline.isoformat(),
            "phase": phase,
            "message": alert.message,
            "amendment_status": (
                "Open" if alert.days_remaining > -60 else "Closed"
            ),
        }

        body = template.format(**template_vars)
        subject = template_vars["subject"]

        # Send via all channels
        success = False

        # Email channel
        for recipient in config.email_recipients:
            delivered = self._send_email(
                recipient=recipient,
                subject=subject,
                body=body,
            )
            self._log_notification(
                alert_id=alert.alert_id,
                importer_id=importer_id,
                notification_type=alert.notification_type,
                channel="email",
                recipient=recipient,
                subject=subject,
                body=body,
                success=delivered,
            )
            if delivered:
                success = True

        # Webhook channel
        for webhook_url in config.webhook_urls:
            payload = self._build_webhook_payload(alert, template_vars)
            delivered = self._send_webhook(
                url=webhook_url,
                payload=payload,
            )
            self._log_notification(
                alert_id=alert.alert_id,
                importer_id=importer_id,
                notification_type=alert.notification_type,
                channel="webhook",
                recipient=webhook_url,
                subject=subject,
                body=json.dumps(payload),
                success=delivered,
            )
            if delivered:
                success = True

        return success

    # ========================================================================
    # REPORT STATUS NOTIFICATIONS
    # ========================================================================

    def send_report_status_notification(
        self,
        report: QuarterlyReport,
        status: ReportStatus,
    ) -> bool:
        """
        Send notification about a report status change (accepted/rejected).

        Args:
            report: The quarterly report.
            status: The new status.

        Returns:
            True if at least one notification was delivered.
        """
        importer_id = report.importer_id
        config = self._get_or_default_config(importer_id)

        # Determine notification type
        if status == ReportStatus.ACCEPTED:
            notification_type = NotificationType.REPORT_ACCEPTED
        elif status == ReportStatus.REJECTED:
            notification_type = NotificationType.REPORT_REJECTED
        else:
            notification_type = NotificationType.DEADLINE_APPROACHING

        if notification_type not in config.notification_types_enabled:
            return False

        # Build details based on status
        if status == ReportStatus.ACCEPTED:
            details = (
                "Your CBAM quarterly report has been accepted by the registry.\n"
                "No further action is required for this reporting period.\n"
                "Please retain all supporting documentation for potential audits."
            )
        elif status == ReportStatus.REJECTED:
            details = (
                "Your CBAM quarterly report has been rejected by the registry.\n"
                "Please review the rejection reasons and resubmit a corrected report.\n"
                f"Amendment deadline: {report.period.amendment_deadline}"
            )
        else:
            details = f"Report status changed to {status.value}."

        template_vars = {
            "subject": notification_type.default_subject,
            "importer_id": importer_id,
            "report_id": report.report_id,
            "period_label": report.period.period_label,
            "status": status.value.upper(),
            "updated_at": datetime.now(timezone.utc).isoformat(),
            "details": details,
        }

        body = REPORT_STATUS_TEMPLATE.format(**template_vars)
        subject = template_vars["subject"]

        success = False

        for recipient in config.email_recipients:
            delivered = self._send_email(recipient, subject, body)
            self._log_notification(
                alert_id=None,
                importer_id=importer_id,
                notification_type=notification_type,
                channel="email",
                recipient=recipient,
                subject=subject,
                body=body,
                success=delivered,
            )
            if delivered:
                success = True

        for webhook_url in config.webhook_urls:
            payload = {
                "event": "report_status_change",
                "report_id": report.report_id,
                "period_label": report.period.period_label,
                "status": status.value,
                "importer_id": importer_id,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }
            delivered = self._send_webhook(webhook_url, payload)
            self._log_notification(
                alert_id=None,
                importer_id=importer_id,
                notification_type=notification_type,
                channel="webhook",
                recipient=webhook_url,
                subject=subject,
                body=json.dumps(payload),
                success=delivered,
            )
            if delivered:
                success = True

        return success

    # ========================================================================
    # AMENDMENT NOTIFICATIONS
    # ========================================================================

    def send_amendment_notification(
        self,
        amendment: ReportAmendment,
    ) -> bool:
        """
        Send notification about an amendment being processed.

        Args:
            amendment: The processed amendment.

        Returns:
            True if at least one notification was delivered.
        """
        # Resolve importer from amendment.report_id
        importer_id = self._extract_importer_from_report_id(
            amendment.report_id
        )
        config = self._get_or_default_config(importer_id)

        notification_type = NotificationType.AMENDMENT_REQUIRED

        if notification_type not in config.notification_types_enabled:
            return False

        template_vars = {
            "subject": "CBAM Report Amendment Processed",
            "importer_id": importer_id,
            "report_id": amendment.report_id,
            "amendment_id": amendment.amendment_id,
            "version": amendment.version,
            "reason": amendment.reason.description,
            "amended_by": amendment.amended_by,
            "amended_at": amendment.amended_at.isoformat(),
            "changes_summary": amendment.changes_summary,
            "previous_hash": amendment.previous_hash[:16] + "...",
            "new_hash": amendment.new_hash[:16] + "...",
        }

        body = AMENDMENT_TEMPLATE.format(**template_vars)
        subject = template_vars["subject"]

        success = False

        for recipient in config.email_recipients:
            delivered = self._send_email(recipient, subject, body)
            self._log_notification(
                alert_id=None,
                importer_id=importer_id,
                notification_type=notification_type,
                channel="email",
                recipient=recipient,
                subject=subject,
                body=body,
                success=delivered,
            )
            if delivered:
                success = True

        for webhook_url in config.webhook_urls:
            payload = {
                "event": "amendment_processed",
                "amendment_id": amendment.amendment_id,
                "report_id": amendment.report_id,
                "version": amendment.version,
                "reason": amendment.reason.value,
                "amended_by": amendment.amended_by,
                "timestamp": datetime.now(timezone.utc).isoformat(),
            }
            delivered = self._send_webhook(webhook_url, payload)
            self._log_notification(
                alert_id=None,
                importer_id=importer_id,
                notification_type=notification_type,
                channel="webhook",
                recipient=webhook_url,
                subject=subject,
                body=json.dumps(payload),
                success=delivered,
            )
            if delivered:
                success = True

        return success

    # ========================================================================
    # NOTIFICATION LOG
    # ========================================================================

    def get_notification_log(
        self,
        importer_id: str,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """
        Get the notification history for an importer.

        Returns notifications sorted by sent_at (most recent first).

        Args:
            importer_id: Importer identifier.
            limit: Maximum number of entries to return.

        Returns:
            List of notification log entry dicts.
        """
        with self._lock:
            entries = [
                entry.model_dump()
                for entry in self._notification_log
                if entry.importer_id == importer_id
            ]
            # Sort by sent_at descending
            entries.sort(
                key=lambda e: e.get("sent_at", ""),
                reverse=True,
            )
            return entries[:limit]

    def get_notification_stats(
        self,
        importer_id: str,
    ) -> Dict[str, Any]:
        """
        Get notification delivery statistics for an importer.

        Args:
            importer_id: Importer identifier.

        Returns:
            Dict with delivery statistics.
        """
        with self._lock:
            entries = [
                e for e in self._notification_log
                if e.importer_id == importer_id
            ]

            total = len(entries)
            sent = sum(1 for e in entries if e.delivery_status == "sent")
            failed = sum(1 for e in entries if e.delivery_status == "failed")

            by_channel: Dict[str, int] = {}
            by_type: Dict[str, int] = {}
            for e in entries:
                by_channel[e.channel] = by_channel.get(e.channel, 0) + 1
                by_type[e.notification_type.value] = (
                    by_type.get(e.notification_type.value, 0) + 1
                )

            return {
                "total_notifications": total,
                "sent": sent,
                "failed": failed,
                "success_rate_pct": (
                    round(sent / total * 100, 1) if total > 0 else 0
                ),
                "by_channel": by_channel,
                "by_type": by_type,
            }

    # ========================================================================
    # DELIVERY CHANNELS (PLUGGABLE)
    # ========================================================================

    def _send_email(
        self,
        recipient: str,
        subject: str,
        body: str,
    ) -> bool:
        """
        Send an email notification.

        In production, this integrates with SMTP/SES. Currently logs the
        delivery for testing and development.

        Args:
            recipient: Email address.
            subject: Email subject.
            body: Email body.

        Returns:
            True if delivery was successful.
        """
        # Production: integrate with SMTP, AWS SES, SendGrid, etc.
        # For now, log the delivery attempt
        logger.info(
            "EMAIL -> %s | Subject: %s | Body length: %d chars",
            recipient, subject, len(body),
        )
        return True  # Simulated successful delivery

    def _send_webhook(
        self,
        url: str,
        payload: Dict[str, Any],
    ) -> bool:
        """
        Send a webhook notification.

        In production, this makes an HTTP POST to the webhook URL.
        Currently logs the delivery for testing and development.

        Args:
            url: Webhook endpoint URL.
            payload: JSON payload to send.

        Returns:
            True if delivery was successful.
        """
        # Production: use httpx/aiohttp for async webhook delivery
        # For now, log the delivery attempt
        logger.info(
            "WEBHOOK -> %s | Event: %s | Payload keys: %s",
            url,
            payload.get("event", "unknown"),
            list(payload.keys()),
        )
        return True  # Simulated successful delivery

    def _build_webhook_payload(
        self,
        alert: DeadlineAlert,
        template_vars: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Build a structured webhook payload from an alert.

        Args:
            alert: The deadline alert.
            template_vars: Template variables for context.

        Returns:
            Structured payload dict for webhook delivery.
        """
        return {
            "event": "deadline_alert",
            "alert_id": alert.alert_id,
            "alert_level": alert.alert_level.value,
            "notification_type": alert.notification_type.value,
            "period_label": template_vars.get("period_label", ""),
            "days_remaining": alert.days_remaining,
            "submission_deadline": template_vars.get("submission_deadline", ""),
            "amendment_deadline": template_vars.get("amendment_deadline", ""),
            "message": alert.message,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "source": "GreenLang CBAM Importer Copilot v1.1.0",
        }

    # ========================================================================
    # INTERNAL HELPERS
    # ========================================================================

    def _log_notification(
        self,
        alert_id: Optional[str],
        importer_id: str,
        notification_type: NotificationType,
        channel: str,
        recipient: str,
        subject: str,
        body: str,
        success: bool,
        error_message: Optional[str] = None,
    ) -> None:
        """
        Log a notification delivery for audit trail.

        Args:
            alert_id: Related alert ID.
            importer_id: Importer identifier.
            notification_type: Type of notification.
            channel: Delivery channel.
            recipient: Recipient address/URL.
            subject: Notification subject.
            body: Notification body.
            success: Whether delivery was successful.
            error_message: Error details if failed.
        """
        log_entry = NotificationLogEntry(
            log_id=f"LOG-{uuid.uuid4().hex[:12].upper()}",
            alert_id=alert_id,
            importer_id=importer_id,
            notification_type=notification_type,
            channel=channel,
            recipient=recipient,
            subject=subject,
            body=body,
            sent_at=datetime.now(timezone.utc),
            delivery_status="sent" if success else "failed",
            error_message=error_message,
        )

        with self._lock:
            self._notification_log.append(log_entry)

    def _get_or_default_config(
        self,
        importer_id: str,
    ) -> NotificationConfig:
        """
        Get notification config for an importer, or return a default.

        Args:
            importer_id: Importer identifier.

        Returns:
            NotificationConfig for the importer.
        """
        with self._lock:
            config = self._configs.get(importer_id)
            if config:
                return config

            # Default config with generic recipient
            return NotificationConfig(
                importer_id=importer_id,
                email_recipients=[f"{importer_id}@notifications.cbam"],
                webhook_urls=[],
            )

    def _resolve_importer_from_alert(self, alert: DeadlineAlert) -> str:
        """
        Extract the importer ID from an alert's recipients or metadata.

        Args:
            alert: The deadline alert.

        Returns:
            Importer identifier string.
        """
        if alert.recipients:
            # Try to extract from email format: importer_id@...
            first_recipient = alert.recipients[0]
            if "@" in first_recipient:
                return first_recipient.split("@")[0]
            return first_recipient
        return "unknown"

    def _extract_importer_from_report_id(self, report_id: str) -> str:
        """
        Extract the importer identifier from a report ID.

        Report ID format: CBAM-QR-{period}-{importer}-{timestamp}

        Args:
            report_id: The report identifier.

        Returns:
            Extracted importer identifier, or "unknown".
        """
        parts = report_id.split("-")
        if len(parts) >= 4:
            # The importer part is between period and timestamp
            # CBAM-QR-2025Q4-NL123456789012-20260115120000
            return parts[3] if len(parts) > 3 else "unknown"
        return "unknown"

    def _is_quiet_hours(self, config: NotificationConfig) -> bool:
        """
        Check if the current UTC time falls within quiet hours.

        Args:
            config: Notification configuration with quiet hours settings.

        Returns:
            True if currently in quiet hours.
        """
        if config.quiet_hours_start is None or config.quiet_hours_end is None:
            return False

        current_hour = datetime.now(timezone.utc).hour
        start = config.quiet_hours_start
        end = config.quiet_hours_end

        if start <= end:
            return start <= current_hour < end
        else:
            # Wraps past midnight (e.g., 22:00 - 06:00)
            return current_hour >= start or current_hour < end
