{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "greenlang-factors.serviceAccountName" . }}
  labels:
    {{- include "greenlang-factors.labels" . | nindent 4 }}
{{- end }}
