# -*- coding: utf-8 -*-
"""
Data Contracts Module for GL-013 PredictiveMaintenance Agent.

Provides validated data schemas for sensor inputs, predictions,
assets, and data quality assessment with zero-hallucination guarantees.
"""

from .sensor_schemas import (
    SensorModality,
    SensorQualityStatus,
    AxisType,
    RunState,
    CalibrationInfo,
    SamplingInfo,
    SensorMetadata,
    VibrationReading,
    TemperatureReading,
    PressureReading,
    CurrentReading,
    ContextReading,
    EnvironmentReading,
    SensorReadingEvent,
    SensorReadingBatch,
    SENSOR_READING_TYPES,
)

from .prediction_schemas import (
    UncertaintyMethod,
    CalibrationStatus,
    ActionSeverity,
    ActionType,
    PredictionConfidence,
    RULPrediction,
    FailureProbability,
    UncertaintyQuantification,
    Explainability,
    DataQualityReference,
    RecommendedAction,
    ModelMetadata,
    PredictionEvent,
    PredictionBatch,
    PREDICTION_SCHEMAS,
)

from .asset_schemas import (
    AssetStatus,
    AssetCriticality,
    BearingType,
    MaintenanceType,
    SiteAlias,
    VendorAlias,
    NameplateData,
    BearingInfo,
    EquipmentSpec,
    InstallationRecord,
    OverhaulRecord,
    MaintenanceRecord,
    OperatingLimits,
    Asset,
    AssetHierarchy,
    ASSET_SCHEMAS,
)

from .data_quality import (
    QualitySeverity,
    QualityDimension,
    QualityIssue,
    DataQualityMetrics,
    QualityReport,
    ValidationRule,
    DataValidator,
    DataQualityAssessor,
)

__all__ = [
    # Sensor schemas
    "SensorModality",
    "SensorQualityStatus",
    "AxisType",
    "RunState",
    "CalibrationInfo",
    "SamplingInfo",
    "SensorMetadata",
    "VibrationReading",
    "TemperatureReading",
    "PressureReading",
    "CurrentReading",
    "ContextReading",
    "EnvironmentReading",
    "SensorReadingEvent",
    "SensorReadingBatch",
    "SENSOR_READING_TYPES",
    # Prediction schemas
    "UncertaintyMethod",
    "CalibrationStatus",
    "ActionSeverity",
    "ActionType",
    "PredictionConfidence",
    "RULPrediction",
    "FailureProbability",
    "UncertaintyQuantification",
    "Explainability",
    "DataQualityReference",
    "RecommendedAction",
    "ModelMetadata",
    "PredictionEvent",
    "PredictionBatch",
    "PREDICTION_SCHEMAS",
    # Asset schemas
    "AssetStatus",
    "AssetCriticality",
    "BearingType",
    "MaintenanceType",
    "SiteAlias",
    "VendorAlias",
    "NameplateData",
    "BearingInfo",
    "EquipmentSpec",
    "InstallationRecord",
    "OverhaulRecord",
    "MaintenanceRecord",
    "OperatingLimits",
    "Asset",
    "AssetHierarchy",
    "ASSET_SCHEMAS",
    # Data quality
    "QualitySeverity",
    "QualityDimension",
    "QualityIssue",
    "DataQualityMetrics",
    "QualityReport",
    "ValidationRule",
    "DataValidator",
    "DataQualityAssessor",
]
