# -*- coding: utf-8 -*-
"""
Prometheus Metrics - AGENT-DATA-004: EUDR Traceability Connector

12 Prometheus metrics for EUDR traceability service monitoring with graceful
fallback when prometheus_client is not installed.

Metrics:
    1.  gl_eudr_plots_registered_total (Counter, labels: commodity, country)
    2.  gl_eudr_custody_transfers_total (Counter, labels: commodity, custody_model)
    3.  gl_eudr_dds_generated_total (Counter, labels: commodity, dds_type)
    4.  gl_eudr_risk_assessments_total (Counter, labels: risk_level, target_type)
    5.  gl_eudr_commodity_classifications_total (Counter, labels: commodity)
    6.  gl_eudr_compliance_checks_total (Counter, labels: article, result)
    7.  gl_eudr_eu_submissions_total (Counter, labels: status)
    8.  gl_eudr_supplier_declarations_total (Counter, labels: commodity)
    9.  gl_eudr_processing_duration_seconds (Histogram, labels: operation)
    10. gl_eudr_errors_total (Counter, labels: operation)
    11. gl_eudr_active_plots (Gauge)
    12. gl_eudr_pending_verifications (Gauge)

Author: GreenLang Platform Team
Date: February 2026
PRD: AGENT-DATA-004 EUDR Traceability Connector
Status: Production Ready
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Graceful prometheus_client import
# ---------------------------------------------------------------------------

try:
    from prometheus_client import Counter, Gauge, Histogram
    PROMETHEUS_AVAILABLE = True
except ImportError:
    PROMETHEUS_AVAILABLE = False
    logger.info(
        "prometheus_client not installed; EUDR traceability metrics disabled"
    )


# ---------------------------------------------------------------------------
# Metric definitions
# ---------------------------------------------------------------------------

if PROMETHEUS_AVAILABLE:
    # 1. Plot registrations by commodity and country
    eudr_plots_registered_total = Counter(
        "gl_eudr_plots_registered_total",
        "Total plots registered in EUDR traceability system",
        labelnames=["commodity", "country"],
    )

    # 2. Custody transfers by commodity and custody model
    eudr_custody_transfers_total = Counter(
        "gl_eudr_custody_transfers_total",
        "Total chain of custody transfers recorded",
        labelnames=["commodity", "custody_model"],
    )

    # 3. Due diligence statements generated by commodity and type
    eudr_dds_generated_total = Counter(
        "gl_eudr_dds_generated_total",
        "Total due diligence statements generated",
        labelnames=["commodity", "dds_type"],
    )

    # 4. Risk assessments performed by risk level and target type
    eudr_risk_assessments_total = Counter(
        "gl_eudr_risk_assessments_total",
        "Total risk assessments performed",
        labelnames=["risk_level", "target_type"],
    )

    # 5. Commodity classifications by commodity
    eudr_commodity_classifications_total = Counter(
        "gl_eudr_commodity_classifications_total",
        "Total commodity classifications performed",
        labelnames=["commodity"],
    )

    # 6. Compliance checks by article and result
    eudr_compliance_checks_total = Counter(
        "gl_eudr_compliance_checks_total",
        "Total compliance checks performed",
        labelnames=["article", "result"],
    )

    # 7. EU Information System submissions by status
    eudr_eu_submissions_total = Counter(
        "gl_eudr_eu_submissions_total",
        "Total submissions to EU Information System",
        labelnames=["status"],
    )

    # 8. Supplier declarations by commodity
    eudr_supplier_declarations_total = Counter(
        "gl_eudr_supplier_declarations_total",
        "Total supplier declarations registered",
        labelnames=["commodity"],
    )

    # 9. Processing duration histogram (12 buckets)
    eudr_processing_duration_seconds = Histogram(
        "gl_eudr_processing_duration_seconds",
        "EUDR traceability operation duration in seconds",
        labelnames=["operation"],
        buckets=(
            0.01, 0.05, 0.1, 0.25, 0.5, 1.0,
            2.5, 5.0, 10.0, 30.0, 60.0, 120.0,
        ),
    )

    # 10. Processing errors by operation
    eudr_processing_errors_total = Counter(
        "gl_eudr_errors_total",
        "Total EUDR traceability processing errors",
        labelnames=["operation"],
    )

    # 11. Currently active (registered) plots
    eudr_active_plots = Gauge(
        "gl_eudr_active_plots",
        "Number of currently active registered plots",
    )

    # 12. Pending verifications/submissions
    eudr_pending_submissions = Gauge(
        "gl_eudr_pending_verifications",
        "Number of pending verifications or submissions",
    )

else:
    # No-op placeholders
    eudr_plots_registered_total = None  # type: ignore[assignment]
    eudr_custody_transfers_total = None  # type: ignore[assignment]
    eudr_dds_generated_total = None  # type: ignore[assignment]
    eudr_risk_assessments_total = None  # type: ignore[assignment]
    eudr_commodity_classifications_total = None  # type: ignore[assignment]
    eudr_compliance_checks_total = None  # type: ignore[assignment]
    eudr_eu_submissions_total = None  # type: ignore[assignment]
    eudr_supplier_declarations_total = None  # type: ignore[assignment]
    eudr_processing_duration_seconds = None  # type: ignore[assignment]
    eudr_processing_errors_total = None  # type: ignore[assignment]
    eudr_active_plots = None  # type: ignore[assignment]
    eudr_pending_submissions = None  # type: ignore[assignment]


# ---------------------------------------------------------------------------
# Helper functions (safe to call even without prometheus_client)
# ---------------------------------------------------------------------------


def record_plot_registered(commodity: str, country: str) -> None:
    """Record a plot registration event.

    Args:
        commodity: EUDR commodity type.
        country: Country code (ISO 3166-1 alpha-2).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    eudr_plots_registered_total.labels(
        commodity=commodity, country=country,
    ).inc()


def record_custody_transfer(commodity: str, custody_model: str) -> None:
    """Record a chain of custody transfer event.

    Args:
        commodity: EUDR commodity type.
        custody_model: Chain of custody model used.
    """
    if not PROMETHEUS_AVAILABLE:
        return
    eudr_custody_transfers_total.labels(
        commodity=commodity, custody_model=custody_model,
    ).inc()


def record_dds_generated(commodity: str, dds_type: str = "operator") -> None:
    """Record a due diligence statement generation event.

    Args:
        commodity: EUDR commodity type.
        dds_type: DDS type (operator, trader, operator_trader).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    eudr_dds_generated_total.labels(
        commodity=commodity, dds_type=dds_type,
    ).inc()


def record_risk_assessment(risk_level: str, target_type: str) -> None:
    """Record a risk assessment event.

    Args:
        risk_level: Assessed risk level (low, standard, high).
        target_type: Type of entity assessed (plot, operator, shipment).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    eudr_risk_assessments_total.labels(
        risk_level=risk_level, target_type=target_type,
    ).inc()


def record_commodity_classification(commodity: str) -> None:
    """Record a commodity classification event.

    Args:
        commodity: Classified EUDR commodity or 'unknown'.
    """
    if not PROMETHEUS_AVAILABLE:
        return
    eudr_commodity_classifications_total.labels(
        commodity=commodity,
    ).inc()


def record_compliance_check(article: str, result: str) -> None:
    """Record a compliance check event.

    Args:
        article: EUDR article checked (e.g. 'article_3').
        result: Check result (compliant, non_compliant, partial, pending).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    eudr_compliance_checks_total.labels(
        article=article, result=result,
    ).inc()


def record_eu_submission(status: str) -> None:
    """Record an EU Information System submission event.

    Args:
        status: Submission status (submitted, accepted, rejected, failed).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    eudr_eu_submissions_total.labels(status=status).inc()


def record_supplier_declaration(commodity: str) -> None:
    """Record a supplier declaration event.

    Args:
        commodity: EUDR commodity declared.
    """
    if not PROMETHEUS_AVAILABLE:
        return
    eudr_supplier_declarations_total.labels(commodity=commodity).inc()


def record_processing_error(operation: str) -> None:
    """Record a processing error event.

    Args:
        operation: Operation that failed.
    """
    if not PROMETHEUS_AVAILABLE:
        return
    eudr_processing_errors_total.labels(operation=operation).inc()


def record_batch_operation(operation: str, duration_seconds: float) -> None:
    """Record a batch operation duration.

    Args:
        operation: Operation name.
        duration_seconds: Duration in seconds.
    """
    if not PROMETHEUS_AVAILABLE:
        return
    eudr_processing_duration_seconds.labels(
        operation=operation,
    ).observe(duration_seconds)


def update_active_plots(delta: int) -> None:
    """Update the active plots gauge.

    Args:
        delta: Positive to increment, negative to decrement.
    """
    if not PROMETHEUS_AVAILABLE:
        return
    if delta > 0:
        eudr_active_plots.inc(delta)
    elif delta < 0:
        eudr_active_plots.dec(abs(delta))


def update_pending_submissions(count: int) -> None:
    """Set the current pending submissions/verifications count.

    Args:
        count: Current pending count.
    """
    if not PROMETHEUS_AVAILABLE:
        return
    eudr_pending_submissions.set(count)


__all__ = [
    "PROMETHEUS_AVAILABLE",
    # Metric objects
    "eudr_plots_registered_total",
    "eudr_custody_transfers_total",
    "eudr_dds_generated_total",
    "eudr_risk_assessments_total",
    "eudr_commodity_classifications_total",
    "eudr_compliance_checks_total",
    "eudr_eu_submissions_total",
    "eudr_supplier_declarations_total",
    "eudr_processing_duration_seconds",
    "eudr_processing_errors_total",
    "eudr_active_plots",
    "eudr_pending_submissions",
    # Helper functions
    "record_plot_registered",
    "record_custody_transfer",
    "record_dds_generated",
    "record_risk_assessment",
    "record_commodity_classification",
    "record_compliance_check",
    "record_eu_submission",
    "record_supplier_declaration",
    "record_processing_error",
    "record_batch_operation",
    "update_active_plots",
    "update_pending_submissions",
]
