"""
PACK-027 Enterprise Net Zero Pack - Configuration Module

This module exports all configuration classes, enums, constants, and utility
functions for the Enterprise Net Zero Pack. Import from this module to access
the full configuration API.

Usage:
    >>> from packs.net_zero.PACK_027_enterprise_net_zero.config import (
    ...     PackConfig,
    ...     EnterpriseNetZeroConfig,
    ...     EnterpriseSector,
    ...     ConsolidationApproach,
    ...     SBTiPathway,
    ...     get_sector_info,
    ...     get_default_config,
    ... )
    >>> config = PackConfig.from_preset("manufacturing")
    >>> print(config.pack.organization.sector)
    EnterpriseSector.MANUFACTURING
"""

from .pack_config import (
    # Enums
    AmbitionLevel,
    AssuranceLevel,
    CarbonPricingApproach,
    ConsolidationApproach,
    DataQualityTier,
    EmissionsProfileType,
    EnterpriseSector,
    ERPSystem,
    FLAGCommodity,
    MaturityAssessment,
    PCAFAssetClass,
    RegulatoryFramework,
    ReportFormat,
    SBTiPathway,
    Scope3Method,
    ScenarioType,
    SDASector,
    SupplierEngagementTier,
    # Sub-config models
    AssuranceConfig,
    AuditTrailConfig,
    CarbonPricingConfig,
    ConsolidationConfig,
    DataQualityConfig,
    EnterpriseOrganizationConfig,
    FinancialIntegrationConfig,
    PerformanceConfig,
    ReportingConfig,
    SBTiTargetConfig,
    ScenarioModelingConfig,
    Scope4Config,
    ScopeConfig,
    ScorecardConfig,
    SupplyChainConfig,
    # Main config models
    EnterpriseNetZeroConfig,
    PackConfig,
    # Constants
    ALL_SCOPE3_CATEGORIES,
    CARBON_PRICE_SCENARIOS,
    DEFAULT_BASE_YEAR,
    DEFAULT_REPORTING_YEAR,
    DEFAULT_TARGET_YEAR_LONG,
    DEFAULT_TARGET_YEAR_NEAR,
    ENTERPRISE_REPORT_TEMPLATES,
    ENTERPRISE_SECTOR_INFO,
    ENTERPRISE_THRESHOLDS,
    IPCC_AR6_GWP100,
    SBTI_CORPORATE_PARAMETERS,
    SDA_SECTOR_BENCHMARKS,
    SECTOR_EMISSIONS_PROFILE,
    SUPPORTED_PRESETS,
    # Directories
    CONFIG_DIR,
    PACK_BASE_DIR,
    # Utility functions
    get_carbon_price_scenario,
    get_default_config,
    get_emissions_profile,
    get_env_overrides,
    get_gwp100,
    get_report_templates,
    get_sbti_parameters,
    get_sda_benchmark,
    get_sector_info,
    list_available_presets,
    load_preset,
    merge_config,
    validate_config,
)

__all__ = [
    # Enums
    "AmbitionLevel",
    "AssuranceLevel",
    "CarbonPricingApproach",
    "ConsolidationApproach",
    "DataQualityTier",
    "EmissionsProfileType",
    "EnterpriseSector",
    "ERPSystem",
    "FLAGCommodity",
    "MaturityAssessment",
    "PCAFAssetClass",
    "RegulatoryFramework",
    "ReportFormat",
    "SBTiPathway",
    "Scope3Method",
    "ScenarioType",
    "SDASector",
    "SupplierEngagementTier",
    # Sub-config models
    "AssuranceConfig",
    "AuditTrailConfig",
    "CarbonPricingConfig",
    "ConsolidationConfig",
    "DataQualityConfig",
    "EnterpriseOrganizationConfig",
    "FinancialIntegrationConfig",
    "PerformanceConfig",
    "ReportingConfig",
    "SBTiTargetConfig",
    "ScenarioModelingConfig",
    "Scope4Config",
    "ScopeConfig",
    "ScorecardConfig",
    "SupplyChainConfig",
    # Main config models
    "EnterpriseNetZeroConfig",
    "PackConfig",
    # Constants
    "ALL_SCOPE3_CATEGORIES",
    "CARBON_PRICE_SCENARIOS",
    "DEFAULT_BASE_YEAR",
    "DEFAULT_REPORTING_YEAR",
    "DEFAULT_TARGET_YEAR_LONG",
    "DEFAULT_TARGET_YEAR_NEAR",
    "ENTERPRISE_REPORT_TEMPLATES",
    "ENTERPRISE_SECTOR_INFO",
    "ENTERPRISE_THRESHOLDS",
    "IPCC_AR6_GWP100",
    "SBTI_CORPORATE_PARAMETERS",
    "SDA_SECTOR_BENCHMARKS",
    "SECTOR_EMISSIONS_PROFILE",
    "SUPPORTED_PRESETS",
    # Directories
    "CONFIG_DIR",
    "PACK_BASE_DIR",
    # Utility functions
    "get_carbon_price_scenario",
    "get_default_config",
    "get_emissions_profile",
    "get_env_overrides",
    "get_gwp100",
    "get_report_templates",
    "get_sbti_parameters",
    "get_sda_benchmark",
    "get_sector_info",
    "list_available_presets",
    "load_preset",
    "merge_config",
    "validate_config",
]
