"""
PACK-010 SFDR Article 8 Pack - Engines Module
================================================

Calculation engines for SFDR Article 8 product compliance and disclosure.

Engines:
    1. PAIIndicatorCalculatorEngine  - All 18 mandatory PAI indicators
    2. TaxonomyAlignmentRatioEngine  - EU Taxonomy alignment ratios
    3. SFDRDNSHEngine                - SFDR-specific DNSH assessment
    4. GoodGovernanceEngine          - Article 2(17) good governance checks
"""

from .pai_indicator_calculator import (
    PAIIndicatorCalculatorEngine,
    PAIIndicatorConfig,
    PAIIndicatorId,
    PAICategory as PAIPAICategory,
    PAIResult,
    PAISingleResult,
    PAICoverage,
    PAIPeriodComparison,
    InvesteeData,
    InvesteeGHGData,
    InvesteeEnvironmentalData,
    InvesteeSocialData,
    InvesteeEnergyData,
    SovereignData,
    RealEstateData,
    DataQualityFlag,
    NACESector,
)

from .taxonomy_alignment_ratio import (
    TaxonomyAlignmentRatioEngine,
    TaxonomyAlignmentConfig,
    HoldingAlignmentData,
    AlignmentResult,
    AlignmentCategory,
    EnvironmentalObjective,
    ObjectiveBreakdown,
    PieChartSlice,
    CommitmentAdherence,
    GASExposureType,
)

from .sfdr_dnsh_engine import (
    SFDRDNSHEngine,
    DNSHConfig,
    DNSHAssessment,
    DNSHStatus,
    InvestmentPAIData,
    PAIThreshold,
    PAIDNSHCheck,
    PortfolioDNSHResult,
    DNSHReportSection,
    ThresholdDirection,
    SeverityLevel,
    PAICategory as DNSHPAICategory,
)

from .good_governance_engine import (
    GoodGovernanceEngine,
    GovernanceConfig,
    CompanyGovernanceData,
    GovernanceResult,
    GovernanceArea,
    GovernanceStatus,
    GovernanceCriterion,
    AreaResult,
    GovernanceViolation,
    PortfolioGovernanceResult,
    ManagementStructureData,
    EmployeeRelationsData,
    RemunerationData,
    TaxComplianceData,
    ViolationType,
)

from .esg_characteristics_engine import (
    ESGCharacteristicsEngine,
    ESGCharacteristicsConfig,
    CharacteristicDefinition,
    BindingElement,
    SustainabilityIndicator,
    AttainmentResult,
    BenchmarkComparison,
    StrategyValidationResult,
    CharacteristicsSummary,
    CharacteristicType,
    CharacteristicStatus,
    AttainmentStatus,
    BindingElementStatus,
    BenchmarkType,
)

from .sustainable_investment_calculator import (
    SustainableInvestmentCalculatorEngine,
    SustainableInvestmentConfig,
    InvestmentData,
    InvestmentClassification,
    InvestmentClassificationType,
    ProportionResult,
    CommitmentAdherence as SICommitmentAdherence,
    ClassificationSummary,
    DNSHAssessment as SIDNSHAssessment,
    GovernanceAssessment,
    DNSHStatus as SIDNSHStatus,
    GovernanceStatus as SIGovernanceStatus,
    ObjectiveContribution,
    AdherenceStatus,
)

from .portfolio_carbon_footprint import (
    PortfolioCarbonFootprintEngine,
    CarbonFootprintConfig,
    HoldingEmissions,
    WACIResult,
    CarbonFootprintResult,
    FinancedEmissionsResult,
    TemperatureAlignment,
    SectorBreakdown,
    CarbonSummary,
    CarbonMethodology,
    ScopeCoverage,
    AttributionMethod,
    DataQuality as CarbonDataQuality,
)

from .eet_data_engine import (
    EETDataEngine,
    EETConfig,
    EETField,
    EETDataSet,
    EETValidationResult,
    EETExportResult,
    EETVersion,
    EETSection,
    EETDataType,
    SFDRClassification,
    ExportFormat,
)

__all__ = [
    # Engine 1: PAI Indicators
    "PAIIndicatorCalculatorEngine",
    "PAIIndicatorConfig",
    "PAIIndicatorId",
    "PAIPAICategory",
    "PAIResult",
    "PAISingleResult",
    "PAICoverage",
    "PAIPeriodComparison",
    "InvesteeData",
    "InvesteeGHGData",
    "InvesteeEnvironmentalData",
    "InvesteeSocialData",
    "InvesteeEnergyData",
    "SovereignData",
    "RealEstateData",
    "DataQualityFlag",
    "NACESector",
    # Engine 2: Taxonomy Alignment
    "TaxonomyAlignmentRatioEngine",
    "TaxonomyAlignmentConfig",
    "HoldingAlignmentData",
    "AlignmentResult",
    "AlignmentCategory",
    "EnvironmentalObjective",
    "ObjectiveBreakdown",
    "PieChartSlice",
    "CommitmentAdherence",
    "GASExposureType",
    # Engine 3: SFDR DNSH
    "SFDRDNSHEngine",
    "DNSHConfig",
    "DNSHAssessment",
    "DNSHStatus",
    "InvestmentPAIData",
    "PAIThreshold",
    "PAIDNSHCheck",
    "PortfolioDNSHResult",
    "DNSHReportSection",
    "ThresholdDirection",
    "SeverityLevel",
    "DNSHPAICategory",
    # Engine 4: Good Governance
    "GoodGovernanceEngine",
    "GovernanceConfig",
    "CompanyGovernanceData",
    "GovernanceResult",
    "GovernanceArea",
    "GovernanceStatus",
    "GovernanceCriterion",
    "AreaResult",
    "GovernanceViolation",
    "PortfolioGovernanceResult",
    "ManagementStructureData",
    "EmployeeRelationsData",
    "RemunerationData",
    "TaxComplianceData",
    "ViolationType",
    # Engine 5: ESG Characteristics
    "ESGCharacteristicsEngine",
    "ESGCharacteristicsConfig",
    "CharacteristicDefinition",
    "BindingElement",
    "SustainabilityIndicator",
    "AttainmentResult",
    "BenchmarkComparison",
    "StrategyValidationResult",
    "CharacteristicsSummary",
    "CharacteristicType",
    "CharacteristicStatus",
    "AttainmentStatus",
    "BindingElementStatus",
    "BenchmarkType",
    # Engine 6: Sustainable Investment Calculator
    "SustainableInvestmentCalculatorEngine",
    "SustainableInvestmentConfig",
    "InvestmentData",
    "InvestmentClassification",
    "InvestmentClassificationType",
    "ProportionResult",
    "SICommitmentAdherence",
    "ClassificationSummary",
    "SIDNSHAssessment",
    "GovernanceAssessment",
    "SIDNSHStatus",
    "SIGovernanceStatus",
    "ObjectiveContribution",
    "AdherenceStatus",
    # Engine 7: Portfolio Carbon Footprint
    "PortfolioCarbonFootprintEngine",
    "CarbonFootprintConfig",
    "HoldingEmissions",
    "WACIResult",
    "CarbonFootprintResult",
    "FinancedEmissionsResult",
    "TemperatureAlignment",
    "SectorBreakdown",
    "CarbonSummary",
    "CarbonMethodology",
    "ScopeCoverage",
    "AttributionMethod",
    "CarbonDataQuality",
    # Engine 8: EET Data
    "EETDataEngine",
    "EETConfig",
    "EETField",
    "EETDataSet",
    "EETValidationResult",
    "EETExportResult",
    "EETVersion",
    "EETSection",
    "EETDataType",
    "SFDRClassification",
    "ExportFormat",
]
