# -*- coding: utf-8 -*-
"""
Prometheus Metrics - AGENT-EUDR-028: Risk Assessment Engine

18 Prometheus metrics for risk assessment engine service monitoring
with graceful fallback when prometheus_client is not installed.

All metric names use the ``gl_eudr_rae_`` prefix for consistent
identification in Prometheus queries, Grafana dashboards, and alerting
rules across the GreenLang platform.

Metrics (18 per PRD Section 7.6):
    Counters (8):
        1.  gl_eudr_rae_assessments_total                    - Assessments by commodity/status
        2.  gl_eudr_rae_factor_aggregations_total             - Factor aggregations by dimension
        3.  gl_eudr_rae_benchmarks_applied_total              - Country benchmarks applied
        4.  gl_eudr_rae_criteria_evaluations_total            - Article 10 criteria evaluated
        5.  gl_eudr_rae_classifications_total                 - Risk classifications by level
        6.  gl_eudr_rae_reports_generated_total               - Reports generated by commodity
        7.  gl_eudr_rae_overrides_applied_total               - Manual overrides applied
        8.  gl_eudr_rae_api_errors_total                      - API errors by operation

    Histograms (5):
        9.  gl_eudr_rae_assessment_duration_seconds           - Assessment latency
        10. gl_eudr_rae_aggregation_duration_seconds          - Aggregation latency
        11. gl_eudr_rae_classification_duration_seconds       - Classification latency
        12. gl_eudr_rae_report_generation_duration_seconds    - Report generation latency
        13. gl_eudr_rae_criteria_evaluation_duration_seconds  - Criteria evaluation latency

    Gauges (5):
        14. gl_eudr_rae_active_assessments                    - Active assessments
        15. gl_eudr_rae_high_risk_operators                   - High-risk operator count
        16. gl_eudr_rae_average_risk_score                    - Average risk score gauge
        17. gl_eudr_rae_override_count                        - Active override count
        18. gl_eudr_rae_trend_data_points                     - Trend data points tracked

Author: GreenLang Platform Team
Date: March 2026
PRD: PRD-AGENT-EUDR-028 (GL-EUDR-RAE-028)
Status: Production Ready
"""
from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

try:
    from prometheus_client import Counter, Gauge, Histogram

    _PROMETHEUS_AVAILABLE = True
except ImportError:
    _PROMETHEUS_AVAILABLE = False
    logger.debug("prometheus_client not available; metrics disabled")


# ---------------------------------------------------------------------------
# Metric Definitions
# ---------------------------------------------------------------------------

if _PROMETHEUS_AVAILABLE:
    # Counters
    _ASSESSMENTS = Counter(
        "gl_eudr_rae_assessments_total",
        "Risk assessments performed",
        ["commodity", "status"],
    )
    _FACTOR_AGGREGATIONS = Counter(
        "gl_eudr_rae_factor_aggregations_total",
        "Risk factor aggregations by dimension",
        ["dimension", "status"],
    )
    _BENCHMARKS_APPLIED = Counter(
        "gl_eudr_rae_benchmarks_applied_total",
        "Country benchmarks applied",
        ["country_code", "level"],
    )
    _CRITERIA_EVALUATIONS = Counter(
        "gl_eudr_rae_criteria_evaluations_total",
        "Article 10 criteria evaluations",
        ["criterion", "result"],
    )
    _CLASSIFICATIONS = Counter(
        "gl_eudr_rae_classifications_total",
        "Risk classifications by level",
        ["risk_level"],
    )
    _REPORTS_GENERATED = Counter(
        "gl_eudr_rae_reports_generated_total",
        "Risk assessment reports generated",
        ["commodity"],
    )
    _OVERRIDES_APPLIED = Counter(
        "gl_eudr_rae_overrides_applied_total",
        "Manual risk overrides applied",
        ["reason"],
    )
    _API_ERRORS = Counter(
        "gl_eudr_rae_api_errors_total",
        "API errors by operation type",
        ["operation"],
    )

    # Histograms
    _ASSESSMENT_DURATION = Histogram(
        "gl_eudr_rae_assessment_duration_seconds",
        "End-to-end risk assessment latency",
        ["commodity"],
        buckets=(0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0),
    )
    _AGGREGATION_DURATION = Histogram(
        "gl_eudr_rae_aggregation_duration_seconds",
        "Risk factor aggregation latency",
        ["dimension"],
        buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0),
    )
    _CLASSIFICATION_DURATION = Histogram(
        "gl_eudr_rae_classification_duration_seconds",
        "Risk classification latency",
        buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0),
    )
    _REPORT_DURATION = Histogram(
        "gl_eudr_rae_report_generation_duration_seconds",
        "Report generation latency",
        ["commodity"],
        buckets=(0.1, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0),
    )
    _CRITERIA_DURATION = Histogram(
        "gl_eudr_rae_criteria_evaluation_duration_seconds",
        "Article 10 criteria evaluation latency",
        buckets=(0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0),
    )

    # Gauges
    _ACTIVE_ASSESSMENTS = Gauge(
        "gl_eudr_rae_active_assessments",
        "Currently active risk assessments",
    )
    _HIGH_RISK_OPERATORS = Gauge(
        "gl_eudr_rae_high_risk_operators",
        "Number of operators classified as HIGH or CRITICAL risk",
    )
    _AVERAGE_RISK_SCORE = Gauge(
        "gl_eudr_rae_average_risk_score",
        "Rolling average composite risk score",
    )
    _OVERRIDE_COUNT = Gauge(
        "gl_eudr_rae_override_count",
        "Number of active manual overrides",
    )
    _TREND_DATA_POINTS = Gauge(
        "gl_eudr_rae_trend_data_points",
        "Total trend data points being tracked",
    )


# ---------------------------------------------------------------------------
# Helper Functions
# ---------------------------------------------------------------------------


def record_assessment(commodity: str, status: str) -> None:
    """Record a risk assessment metric."""
    if _PROMETHEUS_AVAILABLE:
        _ASSESSMENTS.labels(commodity=commodity, status=status).inc()


def record_factor_aggregation(dimension: str, status: str) -> None:
    """Record a risk factor aggregation metric."""
    if _PROMETHEUS_AVAILABLE:
        _FACTOR_AGGREGATIONS.labels(dimension=dimension, status=status).inc()


def record_benchmark_applied(country_code: str, level: str) -> None:
    """Record a country benchmark application metric."""
    if _PROMETHEUS_AVAILABLE:
        _BENCHMARKS_APPLIED.labels(country_code=country_code, level=level).inc()


def record_criteria_evaluation(criterion: str, result: str) -> None:
    """Record an Article 10 criteria evaluation metric."""
    if _PROMETHEUS_AVAILABLE:
        _CRITERIA_EVALUATIONS.labels(criterion=criterion, result=result).inc()


def record_classification(risk_level: str) -> None:
    """Record a risk classification metric."""
    if _PROMETHEUS_AVAILABLE:
        _CLASSIFICATIONS.labels(risk_level=risk_level).inc()


def record_report_generated(commodity: str) -> None:
    """Record a report generation metric."""
    if _PROMETHEUS_AVAILABLE:
        _REPORTS_GENERATED.labels(commodity=commodity).inc()


def record_override_applied(reason: str) -> None:
    """Record a manual override application metric."""
    if _PROMETHEUS_AVAILABLE:
        _OVERRIDES_APPLIED.labels(reason=reason).inc()


def record_api_error(operation: str) -> None:
    """Record an API error metric."""
    if _PROMETHEUS_AVAILABLE:
        _API_ERRORS.labels(operation=operation).inc()


def observe_assessment_duration(commodity: str, duration: float) -> None:
    """Observe end-to-end assessment duration."""
    if _PROMETHEUS_AVAILABLE:
        _ASSESSMENT_DURATION.labels(commodity=commodity).observe(duration)


def observe_aggregation_duration(dimension: str, duration: float) -> None:
    """Observe risk factor aggregation duration."""
    if _PROMETHEUS_AVAILABLE:
        _AGGREGATION_DURATION.labels(dimension=dimension).observe(duration)


def observe_classification_duration(duration: float) -> None:
    """Observe risk classification duration."""
    if _PROMETHEUS_AVAILABLE:
        _CLASSIFICATION_DURATION.observe(duration)


def observe_report_generation_duration(commodity: str, duration: float) -> None:
    """Observe report generation duration."""
    if _PROMETHEUS_AVAILABLE:
        _REPORT_DURATION.labels(commodity=commodity).observe(duration)


def observe_criteria_evaluation_duration(duration: float) -> None:
    """Observe Article 10 criteria evaluation duration."""
    if _PROMETHEUS_AVAILABLE:
        _CRITERIA_DURATION.observe(duration)


def set_active_assessments(count: int) -> None:
    """Set gauge of active assessments."""
    if _PROMETHEUS_AVAILABLE:
        _ACTIVE_ASSESSMENTS.set(count)


def set_high_risk_operators(count: int) -> None:
    """Set gauge of high-risk operators."""
    if _PROMETHEUS_AVAILABLE:
        _HIGH_RISK_OPERATORS.set(count)


def set_average_risk_score(score: float) -> None:
    """Set gauge of average risk score."""
    if _PROMETHEUS_AVAILABLE:
        _AVERAGE_RISK_SCORE.set(score)


def set_override_count(count: int) -> None:
    """Set gauge of active overrides."""
    if _PROMETHEUS_AVAILABLE:
        _OVERRIDE_COUNT.set(count)


def set_trend_data_points(count: int) -> None:
    """Set gauge of trend data points tracked."""
    if _PROMETHEUS_AVAILABLE:
        _TREND_DATA_POINTS.set(count)


# ---------------------------------------------------------------------------
# Engine-specific convenience wrappers
# ---------------------------------------------------------------------------
# These are thin wrappers called by the 7 processing engines.  Each delegates
# to the corresponding generic counter/histogram helper above so that all
# metric recording goes through a single code-path.


def record_composite_calculation(risk_level: str) -> None:
    """Record a composite risk calculation metric."""
    record_assessment("composite", risk_level)


def observe_calculation_duration(duration: float) -> None:
    """Observe composite calculation duration."""
    observe_assessment_duration("composite", duration)


def record_benchmark_lookup(country_code: str, level: str) -> None:
    """Record a country benchmark lookup metric."""
    record_benchmark_applied(country_code, level)


def record_risk_classification(risk_level: str) -> None:
    """Record a risk classification metric."""
    record_classification(risk_level)


def record_trend_analysis(direction: str) -> None:
    """Record a trend analysis metric."""
    record_assessment("trend", direction)


def record_report_generation(risk_level: str, dds_ready: bool = False) -> None:
    """Record a report generation metric."""
    record_report_generated(risk_level)


def record_risk_assessment_operation(commodity: str, status: str) -> None:
    """Record a risk assessment operation metric."""
    record_assessment(commodity, status)
