# -*- coding: utf-8 -*-
"""
Prometheus Metrics - AGENT-DATA-018: Data Lineage Tracker

12 Prometheus metrics for data lineage tracking service monitoring with
graceful fallback when prometheus_client is not installed.

Metrics:
    1.  gl_dlt_assets_registered_total           (Counter,   labels: asset_type, classification)
    2.  gl_dlt_transformations_captured_total     (Counter,   labels: transformation_type, agent_id)
    3.  gl_dlt_edges_created_total               (Counter,   labels: edge_type)
    4.  gl_dlt_impact_analyses_total             (Counter,   labels: direction, severity)
    5.  gl_dlt_validations_total                 (Counter,   labels: result)
    6.  gl_dlt_reports_generated_total           (Counter,   labels: report_type, format)
    7.  gl_dlt_change_events_total               (Counter,   labels: change_type, severity)
    8.  gl_dlt_quality_scores_computed_total     (Counter,   labels: score_tier)
    9.  gl_dlt_graph_traversal_duration_seconds  (Histogram, buckets: traversal-scale)
    10. gl_dlt_processing_duration_seconds       (Histogram, labels: operation, buckets: sub-second)
    11. gl_dlt_graph_node_count                  (Gauge)
    12. gl_dlt_graph_edge_count                  (Gauge)

Author: GreenLang Platform Team
Date: February 2026
PRD: AGENT-DATA-018 Data Lineage Tracker (GL-DATA-X-021)
Status: Production Ready
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Graceful prometheus_client import
# ---------------------------------------------------------------------------

try:
    from prometheus_client import Counter, Gauge, Histogram
    PROMETHEUS_AVAILABLE = True
except ImportError:
    PROMETHEUS_AVAILABLE = False
    logger.info(
        "prometheus_client not installed; data lineage tracker metrics disabled"
    )

# ---------------------------------------------------------------------------
# Metric definitions
# ---------------------------------------------------------------------------

if PROMETHEUS_AVAILABLE:
    # 1. Assets registered by asset type and data classification
    dlt_assets_registered_total = Counter(
        "gl_dlt_assets_registered_total",
        "Total data assets registered in the lineage graph",
        labelnames=["asset_type", "classification"],
    )

    # 2. Transformations captured by transformation type and originating agent
    dlt_transformations_captured_total = Counter(
        "gl_dlt_transformations_captured_total",
        "Total data transformations captured in the lineage graph",
        labelnames=["transformation_type", "agent_id"],
    )

    # 3. Lineage edges created by edge type
    dlt_edges_created_total = Counter(
        "gl_dlt_edges_created_total",
        "Total lineage edges created between data assets",
        labelnames=["edge_type"],
    )

    # 4. Impact analyses performed by traversal direction and severity
    dlt_impact_analyses_total = Counter(
        "gl_dlt_impact_analyses_total",
        "Total impact analyses performed on the lineage graph",
        labelnames=["direction", "severity"],
    )

    # 5. Lineage validations by result outcome
    dlt_validations_total = Counter(
        "gl_dlt_validations_total",
        "Total lineage validation checks performed",
        labelnames=["result"],
    )

    # 6. Lineage reports generated by report type and output format
    dlt_reports_generated_total = Counter(
        "gl_dlt_reports_generated_total",
        "Total lineage reports generated",
        labelnames=["report_type", "format"],
    )

    # 7. Change events tracked by change type and severity
    dlt_change_events_total = Counter(
        "gl_dlt_change_events_total",
        "Total lineage change events detected and recorded",
        labelnames=["change_type", "severity"],
    )

    # 8. Quality scores computed by score tier
    dlt_quality_scores_computed_total = Counter(
        "gl_dlt_quality_scores_computed_total",
        "Total lineage quality scores computed for data assets",
        labelnames=["score_tier"],
    )

    # 9. Graph traversal duration for impact analysis and path queries
    dlt_graph_traversal_duration_seconds = Histogram(
        "gl_dlt_graph_traversal_duration_seconds",
        "Duration of lineage graph traversal operations in seconds",
        buckets=(0.01, 0.05, 0.1, 0.5, 1, 5, 10, 30),
    )

    # 10. Processing duration for individual engine operations
    dlt_processing_duration_seconds = Histogram(
        "gl_dlt_processing_duration_seconds",
        "Data lineage tracker engine operation processing duration in seconds",
        labelnames=["operation"],
        buckets=(0.01, 0.05, 0.1, 0.5, 1, 5, 10),
    )

    # 11. Current number of nodes in the lineage graph
    dlt_graph_node_count = Gauge(
        "gl_dlt_graph_node_count",
        "Current number of nodes in the data lineage graph",
    )

    # 12. Current number of edges in the lineage graph
    dlt_graph_edge_count = Gauge(
        "gl_dlt_graph_edge_count",
        "Current number of edges in the data lineage graph",
    )

else:
    # No-op placeholders so callers never need to guard on PROMETHEUS_AVAILABLE
    dlt_assets_registered_total = None           # type: ignore[assignment]
    dlt_transformations_captured_total = None     # type: ignore[assignment]
    dlt_edges_created_total = None               # type: ignore[assignment]
    dlt_impact_analyses_total = None             # type: ignore[assignment]
    dlt_validations_total = None                 # type: ignore[assignment]
    dlt_reports_generated_total = None           # type: ignore[assignment]
    dlt_change_events_total = None               # type: ignore[assignment]
    dlt_quality_scores_computed_total = None     # type: ignore[assignment]
    dlt_graph_traversal_duration_seconds = None  # type: ignore[assignment]
    dlt_processing_duration_seconds = None       # type: ignore[assignment]
    dlt_graph_node_count = None                  # type: ignore[assignment]
    dlt_graph_edge_count = None                  # type: ignore[assignment]


# ---------------------------------------------------------------------------
# Helper functions (safe to call even without prometheus_client)
# ---------------------------------------------------------------------------


def record_asset_registered(asset_type: str, classification: str) -> None:
    """Record a data asset registration event.

    Args:
        asset_type: Type of data asset registered
            (dataset, table, column, file, stream, api_endpoint, model,
            report, dashboard, metric).
        classification: Data classification level
            (public, internal, confidential, restricted, pii).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_assets_registered_total.labels(
        asset_type=asset_type,
        classification=classification,
    ).inc()


def record_transformation_captured(
    transformation_type: str, agent_id: str
) -> None:
    """Record a data transformation capture event.

    Args:
        transformation_type: Type of transformation captured
            (filter, aggregate, join, map, enrich, normalize, validate,
            deduplicate, impute, classify, extract, convert).
        agent_id: Identifier of the agent that performed the transformation
            (e.g. ``"data-quality-profiler"``, ``"excel-normalizer"``).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_transformations_captured_total.labels(
        transformation_type=transformation_type,
        agent_id=agent_id,
    ).inc()


def record_edge_created(edge_type: str) -> None:
    """Record a lineage edge creation event.

    Args:
        edge_type: Type of lineage edge created
            (derived_from, consumed_by, produced_by, transformed_by,
            validated_by, enriched_by, copied_from, merged_from).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_edges_created_total.labels(
        edge_type=edge_type,
    ).inc()


def record_impact_analysis(direction: str, severity: str) -> None:
    """Record an impact analysis execution event.

    Args:
        direction: Traversal direction for impact analysis
            (upstream, downstream, bidirectional).
        severity: Highest severity level found during analysis
            (critical, high, medium, low, none).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_impact_analyses_total.labels(
        direction=direction,
        severity=severity,
    ).inc()


def record_validation(result: str) -> None:
    """Record a lineage validation result.

    Args:
        result: Validation outcome
            (pass, fail, warning, error, skipped).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_validations_total.labels(
        result=result,
    ).inc()


def record_report_generated(report_type: str, format: str) -> None:
    """Record a lineage report generation event.

    Args:
        report_type: Type of lineage report generated
            (full_lineage, impact_analysis, compliance, audit_trail,
            data_flow, quality_summary, change_history).
        format: Output format of the generated report
            (json, html, pdf, csv, markdown, graphviz).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_reports_generated_total.labels(
        report_type=report_type,
        format=format,
    ).inc()


def record_change_event(change_type: str, severity: str) -> None:
    """Record a lineage change event.

    Args:
        change_type: Type of change detected in the lineage graph
            (asset_added, asset_removed, asset_modified, edge_added,
            edge_removed, schema_changed, classification_changed,
            owner_changed, status_changed).
        severity: Severity level of the change
            (critical, high, medium, low, informational).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_change_events_total.labels(
        change_type=change_type,
        severity=severity,
    ).inc()


def record_quality_score(score_tier: str) -> None:
    """Record a lineage quality score computation event.

    Args:
        score_tier: Quality score tier computed for the data asset
            (excellent, good, fair, poor, critical).
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_quality_scores_computed_total.labels(
        score_tier=score_tier,
    ).inc()


def observe_graph_traversal_duration(seconds: float) -> None:
    """Record the duration of a lineage graph traversal operation.

    Args:
        seconds: Graph traversal wall-clock time in seconds.
            Buckets: 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 30.
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_graph_traversal_duration_seconds.observe(seconds)


def observe_processing_duration(operation: str, seconds: float) -> None:
    """Record processing duration for a single engine operation.

    Args:
        operation: Operation type label
            (asset_register, transformation_capture, edge_create,
            impact_analyze, validate, report_generate, change_detect,
            quality_score, graph_query, export, import).
        seconds: Operation duration in seconds.
            Buckets: 0.01, 0.05, 0.1, 0.5, 1, 5, 10.
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_processing_duration_seconds.labels(
        operation=operation,
    ).observe(seconds)


def set_graph_node_count(count: int) -> None:
    """Set the gauge for current number of nodes in the lineage graph.

    This is an absolute set (not an increment) so the caller is
    responsible for computing the correct current count.

    Args:
        count: Number of nodes currently in the lineage graph.
            Must be >= 0.
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_graph_node_count.set(count)


def set_graph_edge_count(count: int) -> None:
    """Set the gauge for current number of edges in the lineage graph.

    This is an absolute set (not an increment) so the caller is
    responsible for computing the correct current count.

    Args:
        count: Number of edges currently in the lineage graph.
            Must be >= 0.
    """
    if not PROMETHEUS_AVAILABLE:
        return
    dlt_graph_edge_count.set(count)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

__all__ = [
    "PROMETHEUS_AVAILABLE",
    # Metric objects
    "dlt_assets_registered_total",
    "dlt_transformations_captured_total",
    "dlt_edges_created_total",
    "dlt_impact_analyses_total",
    "dlt_validations_total",
    "dlt_reports_generated_total",
    "dlt_change_events_total",
    "dlt_quality_scores_computed_total",
    "dlt_graph_traversal_duration_seconds",
    "dlt_processing_duration_seconds",
    "dlt_graph_node_count",
    "dlt_graph_edge_count",
    # Helper functions
    "record_asset_registered",
    "record_transformation_captured",
    "record_edge_created",
    "record_impact_analysis",
    "record_validation",
    "record_report_generated",
    "record_change_event",
    "record_quality_score",
    "observe_graph_traversal_duration",
    "observe_processing_duration",
    "set_graph_node_count",
    "set_graph_edge_count",
]
