# -*- coding: utf-8 -*-
"""
Compliance Reporter Engine - AGENT-EUDR-005: Land Use Change (Engine 8)

Generates regulatory-grade evidence packages for DDS (Due Diligence
Statement) submission under the EU Deforestation Regulation (EUDR).
Supports 5 report types, 4 output formats, and includes complete
evidence chains with SHA-256 provenance hashing.  Integrates with
the GL-EUDR-APP DDS Reporting Engine for end-to-end regulatory
submission.

Zero-Hallucination Guarantees:
    - All report data is assembled from deterministic analysis results.
    - No narrative text is generated by LLMs; all summaries use
      template-based composition from computed fields.
    - SHA-256 provenance hashes cover every report for tamper detection.
    - Evidence chain links all input hashes to final report hash.
    - No ML/LLM used for any numeric computation.

Report Types (5):
    SINGLE_PLOT:           Complete land use analysis for one plot.
    REGIONAL_TRANSITION:   Transition matrix and spatial map for a region.
    COMMODITY_CONVERSION:  Commodity-specific conversion analysis.
    CUTOFF_COMPLIANCE:     EUDR cutoff date compliance for plot set.
    RISK_ASSESSMENT:       Conversion risk assessment with heatmap.

Output Formats (4):
    JSON:      Machine-readable JSON for API integration.
    CSV:       Tabular CSV for bulk export and spreadsheet analysis.
    PDF:       Human-readable PDF structure for regulatory submission.
    EUDR_XML:  EUDR-specific XML for EU Information System submission.

Regulatory References:
    - EUDR Article 4: Due diligence obligation and DDS requirements.
    - EUDR Article 9: Geolocation-based evidence requirements.
    - EUDR Article 10: Risk assessment documentation.
    - EUDR Article 31: Record-keeping (5-year retention).
    - Implementing Regulation: DDS XML schema for EU Information System.

Author: GreenLang Platform Team
Date: March 2026
PRD: PRD-AGENT-EUDR-005 (Engine 8: Compliance Reporting)
Agent ID: GL-EUDR-LUC-005
Status: Production Ready
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import logging
import time
import uuid
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from xml.etree import ElementTree as ET
from greenlang.schemas import utcnow
from greenlang.schemas.enums import ReportFormat

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Module version for provenance tracking
# ---------------------------------------------------------------------------

_MODULE_VERSION = "1.0.0"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _compute_hash(data: Any) -> str:
    """Compute a deterministic SHA-256 hash for audit provenance."""
    raw = json.dumps(data, sort_keys=True, default=str)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()

def _generate_id() -> str:
    """Generate a unique identifier using UUID4."""
    return str(uuid.uuid4())

def _today_iso() -> str:
    """Return today's date in ISO format."""
    return datetime.now(timezone.utc).date().isoformat()

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class ReportType(str, Enum):
    """Type of compliance report to generate.

    SINGLE_PLOT:           One-plot comprehensive analysis.
    REGIONAL_TRANSITION:   Regional transition matrix with spatial map.
    COMMODITY_CONVERSION:  Commodity-specific conversion analysis.
    CUTOFF_COMPLIANCE:     EUDR cutoff date (31 Dec 2020) compliance.
    RISK_ASSESSMENT:       Conversion risk assessment with heatmap.
    """

    SINGLE_PLOT = "SINGLE_PLOT"
    REGIONAL_TRANSITION = "REGIONAL_TRANSITION"
    COMMODITY_CONVERSION = "COMMODITY_CONVERSION"
    CUTOFF_COMPLIANCE = "CUTOFF_COMPLIANCE"
    RISK_ASSESSMENT = "RISK_ASSESSMENT"

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: EUDR cutoff date per Article 2(1).
EUDR_CUTOFF_DATE: date = date(2020, 12, 31)

#: Regulatory framework reference string.
REGULATORY_FRAMEWORK: str = "EUDR EU 2023/1115"

#: Valid report types set.
VALID_REPORT_TYPES = frozenset(t.value for t in ReportType)

#: Valid report formats set.
VALID_FORMATS = frozenset(f.value for f in ReportFormat)

#: Default report validity period in days.
DEFAULT_VALIDITY_DAYS: int = 365

#: CSV column order for single-plot reports.
SINGLE_PLOT_CSV_COLUMNS: List[str] = [
    "report_id",
    "plot_id",
    "latitude",
    "longitude",
    "area_ha",
    "land_use_at_cutoff",
    "land_use_current",
    "transition_detected",
    "compliance_verdict",
    "confidence",
    "risk_tier",
    "risk_score",
    "data_quality_tier",
    "assessment_date",
    "provenance_hash",
]

#: CSV column order for batch/regional reports.
BATCH_CSV_COLUMNS: List[str] = [
    "report_id",
    "plot_id",
    "compliance_verdict",
    "confidence",
    "risk_tier",
    "risk_score",
    "transition_detected",
    "commodity",
    "area_ha",
    "latitude",
    "longitude",
    "assessment_date",
    "provenance_hash",
]

# ---------------------------------------------------------------------------
# Data Classes
# ---------------------------------------------------------------------------

@dataclass
class ReportConfig:
    """Configuration for a compliance report generation request.

    Attributes:
        report_type: Type of report to generate.
        plot_ids: List of plot identifiers to include.
        format: Output format.
        commodity: Optional commodity filter.
        region: Optional region bounds.
        date_from: Optional analysis start date.
        date_to: Optional analysis end date.
        include_maps: Whether to include map visualizations.
        include_evidence_chain: Whether to include full evidence.
        reviewer: Optional reviewer identifier.
    """

    report_type: str = ReportType.SINGLE_PLOT.value
    plot_ids: List[str] = field(default_factory=list)
    format: str = ReportFormat.JSON.value
    commodity: str = ""
    region: Dict[str, float] = field(default_factory=dict)
    date_from: str = ""
    date_to: str = ""
    include_maps: bool = False
    include_evidence_chain: bool = True
    reviewer: str = ""

@dataclass
class ComplianceReport:
    """Generated compliance report for EUDR land use change assessment.

    Attributes:
        report_id: Unique report identifier (UUID).
        report_type: Type of report generated.
        format: Output format.
        plot_ids: Plot identifiers covered.
        total_plots: Number of plots in the report.
        compliant_count: Number of compliant plots.
        non_compliant_count: Number of non-compliant plots.
        inconclusive_count: Number of inconclusive plots.
        summary: Narrative summary of findings.
        content: Formatted report content (JSON string, CSV string,
            PDF structure dict, or XML string).
        evidence_chain: Dictionary of input hashes and provenance.
        report_hash: SHA-256 hash of the complete report content.
        regulatory_framework: Applicable regulatory framework.
        created_at: UTC timestamp of report generation.
        valid_until: Validity expiration date.
        reviewer: Reviewer identifier.
        processing_time_ms: Report generation time in milliseconds.
        metadata: Additional contextual fields.
    """

    report_id: str = ""
    report_type: str = ""
    format: str = ""
    plot_ids: List[str] = field(default_factory=list)
    total_plots: int = 0
    compliant_count: int = 0
    non_compliant_count: int = 0
    inconclusive_count: int = 0
    summary: str = ""
    content: str = ""
    evidence_chain: Dict[str, Any] = field(default_factory=dict)
    report_hash: str = ""
    regulatory_framework: str = REGULATORY_FRAMEWORK
    created_at: str = ""
    valid_until: str = ""
    reviewer: str = ""
    processing_time_ms: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the report to a plain dictionary."""
        return {
            "report_id": self.report_id,
            "report_type": self.report_type,
            "format": self.format,
            "plot_ids": self.plot_ids,
            "total_plots": self.total_plots,
            "compliant_count": self.compliant_count,
            "non_compliant_count": self.non_compliant_count,
            "inconclusive_count": self.inconclusive_count,
            "summary": self.summary,
            "evidence_chain": self.evidence_chain,
            "report_hash": self.report_hash,
            "regulatory_framework": self.regulatory_framework,
            "created_at": self.created_at,
            "valid_until": self.valid_until,
            "reviewer": self.reviewer,
            "processing_time_ms": self.processing_time_ms,
            "metadata": self.metadata,
        }

# ---------------------------------------------------------------------------
# ComplianceReporter
# ---------------------------------------------------------------------------

class ComplianceReporter:
    """Generates regulatory-grade evidence packages for DDS submission.

    Supports 5 report types, 4 output formats, and complete evidence
    chains with SHA-256 provenance hashing.  Integrates with
    GL-EUDR-APP DDS Reporting Engine.

    All report content is assembled from deterministic analysis results.
    No LLM is used for numeric computations.

    Example::

        reporter = ComplianceReporter()
        config = ReportConfig(
            report_type="SINGLE_PLOT",
            plot_ids=["plot-001"],
            format="JSON",
        )
        report = reporter.generate_report(
            report_type=config.report_type,
            plot_ids=config.plot_ids,
            format=config.format,
            options={"analysis_results": results_dict},
        )
        assert report.report_hash != ""

    Attributes:
        config: Optional agent configuration object.
    """

    def __init__(self, config: Any = None) -> None:
        """Initialize the ComplianceReporter.

        Args:
            config: Optional LandUseChangeConfig instance.
        """
        self.config = config
        logger.info(
            "ComplianceReporter initialized: module_version=%s",
            _MODULE_VERSION,
        )

    # ------------------------------------------------------------------
    # Public API: Report Generation
    # ------------------------------------------------------------------

    def generate_report(
        self,
        report_type: str,
        plot_ids: List[str],
        format: str = ReportFormat.JSON.value,
        options: Optional[Dict[str, Any]] = None,
    ) -> ComplianceReport:
        """Generate a compliance report.

        Dispatches to the appropriate report generator based on
        report_type and formats the output according to format.

        Args:
            report_type: Report type (SINGLE_PLOT, REGIONAL_TRANSITION,
                COMMODITY_CONVERSION, CUTOFF_COMPLIANCE, RISK_ASSESSMENT).
            plot_ids: List of plot identifiers.
            format: Output format (JSON, CSV, PDF, EUDR_XML).
            options: Optional dictionary with analysis_results and
                configuration overrides.

        Returns:
            ComplianceReport with formatted content and provenance.

        Raises:
            ValueError: If report_type or format is invalid.
        """
        start_time = time.monotonic()
        self._validate_report_type(report_type)
        self._validate_format(format)

        opts = options or {}
        analysis_results = opts.get("analysis_results", {})
        region = opts.get("region", {})
        commodity = opts.get("commodity", "")
        date_from = opts.get("date_from", "")
        date_to = opts.get("date_to", "")

        if report_type == ReportType.SINGLE_PLOT.value:
            report_data = self._generate_single_plot_report(
                plot_ids, analysis_results,
            )
        elif report_type == ReportType.REGIONAL_TRANSITION.value:
            report_data = self._generate_regional_transition_report(
                region, date_from, date_to, analysis_results,
            )
        elif report_type == ReportType.COMMODITY_CONVERSION.value:
            report_data = self._generate_commodity_conversion_report(
                commodity, region, analysis_results,
            )
        elif report_type == ReportType.CUTOFF_COMPLIANCE.value:
            report_data = self._generate_cutoff_compliance_report(
                plot_ids, analysis_results,
            )
        elif report_type == ReportType.RISK_ASSESSMENT.value:
            report_data = self._generate_risk_assessment_report(
                plot_ids, analysis_results,
            )
        else:
            raise ValueError(f"Unsupported report_type: {report_type}")

        evidence_chain = self._compile_evidence_chain(report_data)

        if format == ReportFormat.JSON.value:
            content = self._format_json(report_data)
        elif format == ReportFormat.CSV.value:
            content = self._format_csv(report_data)
        elif format == ReportFormat.PDF.value:
            pdf_structure = self._format_pdf(report_data)
            content = json.dumps(pdf_structure, indent=2, default=str)
        elif format == ReportFormat.EUDR_XML.value:
            content = self._format_eudr_xml(report_data)
        else:
            content = self._format_json(report_data)

        report_hash = self._compute_report_hash(report_data)

        verdicts = report_data.get("verdicts", [])
        non_compliant = self._flag_non_compliant(verdicts)

        compliant_count = sum(
            1 for v in verdicts
            if v.get("verdict", "").lower() in (
                "compliant", "deforestation_free",
            )
        )
        non_compliant_count = len(non_compliant)
        inconclusive_count = sum(
            1 for v in verdicts
            if v.get("verdict", "").lower() == "inconclusive"
        )

        summary = self._generate_summary(
            report_type=report_type,
            total_plots=len(plot_ids),
            compliant=compliant_count,
            non_compliant=non_compliant_count,
            inconclusive=inconclusive_count,
        )

        from datetime import timedelta

        valid_until = (
            datetime.now(timezone.utc).date()
            + timedelta(days=DEFAULT_VALIDITY_DAYS)
        )

        elapsed_ms = (time.monotonic() - start_time) * 1000

        report = ComplianceReport(
            report_id=_generate_id(),
            report_type=report_type,
            format=format,
            plot_ids=list(plot_ids),
            total_plots=len(plot_ids),
            compliant_count=compliant_count,
            non_compliant_count=non_compliant_count,
            inconclusive_count=inconclusive_count,
            summary=summary,
            content=content,
            evidence_chain=evidence_chain,
            report_hash=report_hash,
            regulatory_framework=REGULATORY_FRAMEWORK,
            created_at=utcnow().isoformat(),
            valid_until=valid_until.isoformat(),
            reviewer=opts.get("reviewer", ""),
            processing_time_ms=round(elapsed_ms, 2),
            metadata={
                "module_version": _MODULE_VERSION,
                "commodity": commodity,
                "region": region,
                "date_from": date_from,
                "date_to": date_to,
                "non_compliant_flags": non_compliant,
            },
        )

        logger.info(
            "Report generated: type=%s, format=%s, %d plots, "
            "compliant=%d, non_compliant=%d, inconclusive=%d, "
            "%.2fms",
            report_type, format, len(plot_ids),
            compliant_count, non_compliant_count,
            inconclusive_count, elapsed_ms,
        )
        return report

    # ------------------------------------------------------------------
    # Public API: Batch Report Generation
    # ------------------------------------------------------------------

    def generate_batch_reports(
        self,
        report_configs: List[ReportConfig],
    ) -> List[ComplianceReport]:
        """Generate multiple reports from a list of configurations.

        Args:
            report_configs: List of ReportConfig objects.

        Returns:
            List of ComplianceReport objects.

        Raises:
            ValueError: If report_configs is empty.
        """
        if not report_configs:
            raise ValueError("report_configs list must not be empty")

        start_time = time.monotonic()
        reports: List[ComplianceReport] = []

        for i, config in enumerate(report_configs):
            try:
                report = self.generate_report(
                    report_type=config.report_type,
                    plot_ids=config.plot_ids,
                    format=config.format,
                    options={
                        "commodity": config.commodity,
                        "region": config.region,
                        "date_from": config.date_from,
                        "date_to": config.date_to,
                        "reviewer": config.reviewer,
                    },
                )
                reports.append(report)
            except Exception as exc:
                logger.error(
                    "generate_batch_reports: failed on config[%d]: %s",
                    i, str(exc),
                )
                reports.append(self._create_error_report(
                    config, str(exc),
                ))

        elapsed_ms = (time.monotonic() - start_time) * 1000
        logger.info(
            "Batch reports: %d generated, %.2fms",
            len(reports), elapsed_ms,
        )
        return reports

    # ------------------------------------------------------------------
    # Internal: Report Type Generators
    # ------------------------------------------------------------------

    def _generate_single_plot_report(
        self,
        plot_ids: List[str],
        analysis_results: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Generate single-plot report data.

        Args:
            plot_ids: Plot identifiers (uses first plot).
            analysis_results: Analysis results dictionary.

        Returns:
            Report data dictionary.
        """
        plot_id = plot_ids[0] if plot_ids else "unknown"
        plot_data = analysis_results.get(plot_id, {})

        land_use_at_cutoff = plot_data.get("land_use_at_cutoff", "unknown")
        land_use_current = plot_data.get("land_use_current", "unknown")
        transition_detected = plot_data.get("transition_detected", False)
        confidence = plot_data.get("confidence", 0.0)
        risk_score = plot_data.get("risk_score", 0.0)
        risk_tier = plot_data.get("risk_tier", "MODERATE")
        latitude = plot_data.get("latitude", 0.0)
        longitude = plot_data.get("longitude", 0.0)
        area_ha = plot_data.get("area_ha", 0.0)
        data_quality = plot_data.get("data_quality_tier", "SILVER")

        if transition_detected:
            verdict = "non_compliant"
        elif confidence < 0.5:
            verdict = "inconclusive"
        else:
            verdict = "compliant"

        return {
            "report_type": ReportType.SINGLE_PLOT.value,
            "plot_id": plot_id,
            "latitude": latitude,
            "longitude": longitude,
            "area_ha": area_ha,
            "land_use_at_cutoff": land_use_at_cutoff,
            "land_use_current": land_use_current,
            "transition_detected": transition_detected,
            "compliance_verdict": verdict,
            "confidence": confidence,
            "risk_tier": risk_tier,
            "risk_score": risk_score,
            "data_quality_tier": data_quality,
            "cutoff_date": EUDR_CUTOFF_DATE.isoformat(),
            "assessment_date": _today_iso(),
            "before_after_map": self._generate_before_after_map(
                land_use_at_cutoff, land_use_current,
            ),
            "verdicts": [
                {
                    "plot_id": plot_id,
                    "verdict": verdict,
                    "confidence": confidence,
                },
            ],
            "plots": [{
                "plot_id": plot_id,
                "latitude": latitude,
                "longitude": longitude,
                "area_ha": area_ha,
                "verdict": verdict,
                "confidence": confidence,
                "risk_tier": risk_tier,
                "risk_score": risk_score,
                "transition_detected": transition_detected,
                "commodity": plot_data.get("commodity", ""),
                "assessment_date": _today_iso(),
            }],
        }

    def _generate_regional_transition_report(
        self,
        region: Dict[str, float],
        date_from: str,
        date_to: str,
        analysis_results: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Generate regional transition report data.

        Args:
            region: Region bounds.
            date_from: Analysis start date.
            date_to: Analysis end date.
            analysis_results: Analysis results dictionary.

        Returns:
            Report data dictionary.
        """
        plots = list(analysis_results.values()) if analysis_results else []
        transition_matrix = analysis_results.get("transition_matrix", {})

        verdicts: List[Dict[str, Any]] = []
        for plot_data in plots:
            if isinstance(plot_data, dict) and "plot_id" in plot_data:
                verdict = "compliant"
                if plot_data.get("transition_detected", False):
                    verdict = "non_compliant"
                elif plot_data.get("confidence", 0.0) < 0.5:
                    verdict = "inconclusive"
                verdicts.append({
                    "plot_id": plot_data.get("plot_id", ""),
                    "verdict": verdict,
                    "confidence": plot_data.get("confidence", 0.0),
                })

        matrix_viz = self._generate_transition_matrix_viz(transition_matrix)

        return {
            "report_type": ReportType.REGIONAL_TRANSITION.value,
            "region": region,
            "date_from": date_from,
            "date_to": date_to,
            "total_plots": len(plots),
            "transition_matrix": transition_matrix,
            "transition_matrix_visualization": matrix_viz,
            "verdicts": verdicts,
            "assessment_date": _today_iso(),
            "plots": [
                p for p in plots
                if isinstance(p, dict) and "plot_id" in p
            ],
        }

    def _generate_commodity_conversion_report(
        self,
        commodity: str,
        region: Dict[str, float],
        analysis_results: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Generate commodity-specific conversion report data.

        Args:
            commodity: Target commodity.
            region: Region bounds.
            analysis_results: Analysis results dictionary.

        Returns:
            Report data dictionary.
        """
        plots = list(analysis_results.values()) if analysis_results else []
        conversions = [
            p for p in plots
            if isinstance(p, dict) and p.get("conversion_detected", False)
        ]

        verdicts: List[Dict[str, Any]] = []
        for plot_data in plots:
            if isinstance(plot_data, dict) and "plot_id" in plot_data:
                verdict = "compliant"
                if plot_data.get("conversion_detected", False):
                    verdict = "non_compliant"
                elif plot_data.get("confidence", 0.0) < 0.5:
                    verdict = "inconclusive"
                verdicts.append({
                    "plot_id": plot_data.get("plot_id", ""),
                    "verdict": verdict,
                    "confidence": plot_data.get("confidence", 0.0),
                })

        total_conversion_area = sum(
            c.get("area_ha", 0.0) for c in conversions
        )

        return {
            "report_type": ReportType.COMMODITY_CONVERSION.value,
            "commodity": commodity,
            "region": region,
            "total_plots": len(plots),
            "conversion_count": len(conversions),
            "total_conversion_area_ha": round(total_conversion_area, 2),
            "conversion_rate_pct": round(
                len(conversions) / max(len(plots), 1) * 100.0, 2,
            ),
            "verdicts": verdicts,
            "assessment_date": _today_iso(),
            "plots": [
                p for p in plots
                if isinstance(p, dict) and "plot_id" in p
            ],
        }

    def _generate_cutoff_compliance_report(
        self,
        plot_ids: List[str],
        analysis_results: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Generate EUDR cutoff date compliance report data.

        Args:
            plot_ids: Plot identifiers.
            analysis_results: Analysis results dictionary.

        Returns:
            Report data dictionary.
        """
        verdicts: List[Dict[str, Any]] = []
        plots_data: List[Dict[str, Any]] = []

        for plot_id in plot_ids:
            plot_data = analysis_results.get(plot_id, {})
            was_forest = plot_data.get("was_forest_at_cutoff", False)
            is_forest = plot_data.get("is_forest_current", False)
            transition = plot_data.get("transition_detected", False)
            confidence = plot_data.get("confidence", 0.0)

            if was_forest and not is_forest and transition:
                verdict = "non_compliant"
            elif confidence < 0.5:
                verdict = "inconclusive"
            else:
                verdict = "compliant"

            verdicts.append({
                "plot_id": plot_id,
                "verdict": verdict,
                "confidence": confidence,
                "was_forest_at_cutoff": was_forest,
                "is_forest_current": is_forest,
            })
            plots_data.append({
                "plot_id": plot_id,
                "verdict": verdict,
                "confidence": confidence,
                "was_forest_at_cutoff": was_forest,
                "is_forest_current": is_forest,
                "transition_detected": transition,
                "latitude": plot_data.get("latitude", 0.0),
                "longitude": plot_data.get("longitude", 0.0),
                "area_ha": plot_data.get("area_ha", 0.0),
                "commodity": plot_data.get("commodity", ""),
                "risk_tier": plot_data.get("risk_tier", ""),
                "risk_score": plot_data.get("risk_score", 0.0),
                "assessment_date": _today_iso(),
            })

        return {
            "report_type": ReportType.CUTOFF_COMPLIANCE.value,
            "cutoff_date": EUDR_CUTOFF_DATE.isoformat(),
            "total_plots": len(plot_ids),
            "verdicts": verdicts,
            "assessment_date": _today_iso(),
            "plots": plots_data,
        }

    def _generate_risk_assessment_report(
        self,
        plot_ids: List[str],
        analysis_results: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Generate risk assessment report data.

        Args:
            plot_ids: Plot identifiers.
            analysis_results: Analysis results dictionary.

        Returns:
            Report data dictionary.
        """
        verdicts: List[Dict[str, Any]] = []
        plots_data: List[Dict[str, Any]] = []
        risk_scores: List[float] = []

        for plot_id in plot_ids:
            plot_data = analysis_results.get(plot_id, {})
            risk_score = plot_data.get("risk_score", 0.0)
            risk_tier = plot_data.get("risk_tier", "MODERATE")
            confidence = plot_data.get("confidence", 0.0)

            risk_scores.append(risk_score)

            if risk_tier in ("CRITICAL", "HIGH"):
                verdict = "non_compliant"
            elif confidence < 0.5:
                verdict = "inconclusive"
            else:
                verdict = "compliant"

            verdicts.append({
                "plot_id": plot_id,
                "verdict": verdict,
                "confidence": confidence,
                "risk_score": risk_score,
                "risk_tier": risk_tier,
            })
            plots_data.append({
                "plot_id": plot_id,
                "verdict": verdict,
                "confidence": confidence,
                "risk_tier": risk_tier,
                "risk_score": risk_score,
                "latitude": plot_data.get("latitude", 0.0),
                "longitude": plot_data.get("longitude", 0.0),
                "area_ha": plot_data.get("area_ha", 0.0),
                "commodity": plot_data.get("commodity", ""),
                "transition_detected": plot_data.get(
                    "transition_detected", False,
                ),
                "assessment_date": _today_iso(),
            })

        tier_distribution = {
            "CRITICAL": sum(1 for s in risk_scores if s > 75.0),
            "HIGH": sum(1 for s in risk_scores if 50.0 < s <= 75.0),
            "MODERATE": sum(1 for s in risk_scores if 25.0 < s <= 50.0),
            "LOW": sum(1 for s in risk_scores if s <= 25.0),
        }

        return {
            "report_type": ReportType.RISK_ASSESSMENT.value,
            "total_plots": len(plot_ids),
            "mean_risk_score": round(
                sum(risk_scores) / max(len(risk_scores), 1), 2,
            ),
            "max_risk_score": round(
                max(risk_scores, default=0.0), 2,
            ),
            "tier_distribution": tier_distribution,
            "verdicts": verdicts,
            "assessment_date": _today_iso(),
            "plots": plots_data,
        }

    # ------------------------------------------------------------------
    # Internal: Output Formatters
    # ------------------------------------------------------------------

    def _format_json(self, report_data: Dict[str, Any]) -> str:
        """Format report data as JSON string.

        Args:
            report_data: Report data dictionary.

        Returns:
            Formatted JSON string.
        """
        return json.dumps(report_data, indent=2, default=str)

    def _format_csv(self, report_data: Dict[str, Any]) -> str:
        """Format report data as CSV string.

        Args:
            report_data: Report data dictionary.

        Returns:
            CSV string with header row and data rows.
        """
        output = io.StringIO()
        plots = report_data.get("plots", [])

        if not plots:
            report_type = report_data.get("report_type", "")
            if report_type == ReportType.SINGLE_PLOT.value:
                columns = SINGLE_PLOT_CSV_COLUMNS
            else:
                columns = BATCH_CSV_COLUMNS
            writer = csv.DictWriter(output, fieldnames=columns)
            writer.writeheader()
            return output.getvalue()

        all_keys = set()
        for plot in plots:
            if isinstance(plot, dict):
                all_keys.update(plot.keys())

        report_type = report_data.get("report_type", "")
        if report_type == ReportType.SINGLE_PLOT.value:
            columns = SINGLE_PLOT_CSV_COLUMNS
        else:
            columns = BATCH_CSV_COLUMNS

        final_columns = [c for c in columns if c in all_keys or c == "report_id"]
        extra_keys = sorted(all_keys - set(final_columns))
        final_columns.extend(extra_keys)

        writer = csv.DictWriter(
            output,
            fieldnames=final_columns,
            extrasaction="ignore",
        )
        writer.writeheader()

        for plot in plots:
            if isinstance(plot, dict):
                row = dict(plot)
                row.setdefault("report_id", report_data.get("report_id", ""))
                row.setdefault("provenance_hash", _compute_hash(row))
                writer.writerow(row)

        return output.getvalue()

    def _format_pdf(self, report_data: Dict[str, Any]) -> Dict[str, Any]:
        """Format report data as a PDF structure for a renderer.

        Returns a dictionary describing the PDF layout: title, sections,
        tables, charts, and maps.  The actual PDF rendering is performed
        by the downstream PDF renderer service.

        Args:
            report_data: Report data dictionary.

        Returns:
            PDF structure dictionary.
        """
        report_type = report_data.get("report_type", "")
        plots = report_data.get("plots", [])
        verdicts = report_data.get("verdicts", [])

        title = f"EUDR Compliance Report - {report_type}"
        subtitle = (
            f"Generated: {_today_iso()} | "
            f"Regulatory Framework: {REGULATORY_FRAMEWORK}"
        )

        sections: List[Dict[str, Any]] = []

        sections.append({
            "heading": "Executive Summary",
            "content": self._generate_summary(
                report_type=report_type,
                total_plots=len(plots),
                compliant=sum(
                    1 for v in verdicts
                    if v.get("verdict", "") in ("compliant", "deforestation_free")
                ),
                non_compliant=sum(
                    1 for v in verdicts
                    if v.get("verdict", "") == "non_compliant"
                ),
                inconclusive=sum(
                    1 for v in verdicts
                    if v.get("verdict", "") == "inconclusive"
                ),
            ),
        })

        if report_type == ReportType.SINGLE_PLOT.value:
            sections.append({
                "heading": "Plot Details",
                "content": report_data.get("plot_id", ""),
                "table": {
                    "columns": SINGLE_PLOT_CSV_COLUMNS,
                    "rows": plots,
                },
            })
            sections.append({
                "heading": "Before/After Land Use Map",
                "chart_type": "before_after_map",
                "data": report_data.get("before_after_map", {}),
            })

        elif report_type == ReportType.REGIONAL_TRANSITION.value:
            sections.append({
                "heading": "Transition Matrix",
                "chart_type": "transition_matrix",
                "data": report_data.get(
                    "transition_matrix_visualization", {},
                ),
            })

        elif report_type == ReportType.RISK_ASSESSMENT.value:
            sections.append({
                "heading": "Risk Distribution",
                "chart_type": "risk_heatmap",
                "data": report_data.get("tier_distribution", {}),
            })

        sections.append({
            "heading": "Compliance Verdicts",
            "table": {
                "columns": ["plot_id", "verdict", "confidence"],
                "rows": verdicts,
            },
        })

        if plots:
            sections.append({
                "heading": "Detailed Plot Data",
                "table": {
                    "columns": BATCH_CSV_COLUMNS,
                    "rows": plots,
                },
            })

        sections.append({
            "heading": "Regulatory References",
            "content": (
                "This report was generated under the EU Deforestation "
                "Regulation (EU) 2023/1115. The EUDR cutoff date is "
                f"{EUDR_CUTOFF_DATE.isoformat()} per Article 2(1). "
                "Evidence has been compiled per Articles 4, 9, 10, "
                "and 31."
            ),
        })

        return {
            "title": title,
            "subtitle": subtitle,
            "page_size": "A4",
            "orientation": "portrait",
            "sections": sections,
            "footer": (
                f"Report ID: {report_data.get('report_id', _generate_id())} | "
                f"Generated by GreenLang EUDR Land Use Change Agent v{_MODULE_VERSION}"
            ),
        }

    def _format_eudr_xml(self, report_data: Dict[str, Any]) -> str:
        """Format report data as EUDR regulatory XML.

        Produces XML compatible with the EU Information System
        DDS submission schema.

        Args:
            report_data: Report data dictionary.

        Returns:
            XML string.
        """
        root = ET.Element("EUDRComplianceReport")
        root.set("xmlns", "urn:eu:eudr:compliance:v1")
        root.set("version", _MODULE_VERSION)

        header = ET.SubElement(root, "Header")
        ET.SubElement(header, "ReportId").text = _generate_id()
        ET.SubElement(header, "ReportType").text = report_data.get(
            "report_type", "",
        )
        ET.SubElement(header, "RegulatoryFramework").text = REGULATORY_FRAMEWORK
        ET.SubElement(header, "CutoffDate").text = EUDR_CUTOFF_DATE.isoformat()
        ET.SubElement(header, "AssessmentDate").text = _today_iso()
        ET.SubElement(header, "GeneratedAt").text = utcnow().isoformat()

        summary_elem = ET.SubElement(root, "Summary")
        ET.SubElement(summary_elem, "TotalPlots").text = str(
            report_data.get("total_plots", 0),
        )

        verdicts = report_data.get("verdicts", [])
        compliant = sum(
            1 for v in verdicts
            if v.get("verdict", "") in ("compliant", "deforestation_free")
        )
        non_compliant = sum(
            1 for v in verdicts
            if v.get("verdict", "") == "non_compliant"
        )
        inconclusive = sum(
            1 for v in verdicts
            if v.get("verdict", "") == "inconclusive"
        )
        ET.SubElement(summary_elem, "Compliant").text = str(compliant)
        ET.SubElement(summary_elem, "NonCompliant").text = str(non_compliant)
        ET.SubElement(summary_elem, "Inconclusive").text = str(inconclusive)

        plots_elem = ET.SubElement(root, "Plots")
        plots = report_data.get("plots", [])
        for plot_data in plots:
            if not isinstance(plot_data, dict):
                continue
            plot_elem = ET.SubElement(plots_elem, "Plot")
            ET.SubElement(plot_elem, "PlotId").text = str(
                plot_data.get("plot_id", ""),
            )
            ET.SubElement(plot_elem, "Latitude").text = str(
                plot_data.get("latitude", 0.0),
            )
            ET.SubElement(plot_elem, "Longitude").text = str(
                plot_data.get("longitude", 0.0),
            )
            ET.SubElement(plot_elem, "AreaHa").text = str(
                plot_data.get("area_ha", 0.0),
            )
            ET.SubElement(plot_elem, "Verdict").text = str(
                plot_data.get("verdict", ""),
            )
            ET.SubElement(plot_elem, "Confidence").text = str(
                plot_data.get("confidence", 0.0),
            )
            ET.SubElement(plot_elem, "RiskTier").text = str(
                plot_data.get("risk_tier", ""),
            )
            ET.SubElement(plot_elem, "RiskScore").text = str(
                plot_data.get("risk_score", 0.0),
            )
            ET.SubElement(plot_elem, "Commodity").text = str(
                plot_data.get("commodity", ""),
            )
            ET.SubElement(plot_elem, "TransitionDetected").text = str(
                plot_data.get("transition_detected", False),
            ).lower()

        evidence_elem = ET.SubElement(root, "Evidence")
        ET.SubElement(evidence_elem, "ProvenanceHash").text = _compute_hash(
            report_data,
        )
        ET.SubElement(evidence_elem, "ModuleVersion").text = _MODULE_VERSION

        tree_str = ET.tostring(root, encoding="unicode", xml_declaration=False)
        return f'<?xml version="1.0" encoding="UTF-8"?>\n{tree_str}'

    # ------------------------------------------------------------------
    # Internal: Evidence Chain
    # ------------------------------------------------------------------

    def _compile_evidence_chain(
        self,
        results: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Compile complete evidence chain with all input hashes.

        Args:
            results: Report data dictionary.

        Returns:
            Evidence chain dictionary.
        """
        plots = results.get("plots", [])
        input_hashes: List[str] = []

        for plot in plots:
            if isinstance(plot, dict):
                plot_hash = _compute_hash(plot)
                input_hashes.append(plot_hash)

        chain_hash = _compute_hash({
            "input_hashes": input_hashes,
            "report_type": results.get("report_type", ""),
            "assessment_date": results.get("assessment_date", ""),
        })

        return {
            "input_count": len(input_hashes),
            "input_hashes": input_hashes,
            "chain_hash": chain_hash,
            "module_version": _MODULE_VERSION,
            "timestamp": utcnow().isoformat(),
        }

    # ------------------------------------------------------------------
    # Internal: Visualization Helpers
    # ------------------------------------------------------------------

    def _generate_before_after_map(
        self,
        cutoff_class: str,
        current_class: str,
    ) -> Dict[str, Any]:
        """Generate before/after land use map data.

        Args:
            cutoff_class: Land use class at EUDR cutoff date.
            current_class: Current land use class.

        Returns:
            Map data dictionary.
        """
        changed = cutoff_class.lower() != current_class.lower()
        return {
            "cutoff_date": EUDR_CUTOFF_DATE.isoformat(),
            "cutoff_class": cutoff_class,
            "current_class": current_class,
            "change_detected": changed,
            "map_type": "before_after",
            "legend": {
                "cutoff": {"label": cutoff_class, "color": "#228B22"},
                "current": {
                    "label": current_class,
                    "color": "#8B0000" if changed else "#228B22",
                },
            },
        }

    def _generate_transition_matrix_viz(
        self,
        matrix: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Generate transition matrix visualization data.

        Args:
            matrix: Transition matrix dictionary.

        Returns:
            Visualization data dictionary.
        """
        classes = sorted(set(
            list(matrix.keys()) +
            [k for v in matrix.values() if isinstance(v, dict) for k in v.keys()]
        )) if matrix else []

        rows: List[Dict[str, Any]] = []
        for from_class in classes:
            row = {"from_class": from_class}
            transitions = matrix.get(from_class, {})
            if isinstance(transitions, dict):
                for to_class in classes:
                    row[to_class] = transitions.get(to_class, 0)
            rows.append(row)

        return {
            "matrix_type": "land_use_transition",
            "classes": classes,
            "rows": rows,
            "total_classes": len(classes),
        }

    def _generate_trajectory_chart(
        self,
        trajectory: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Generate trajectory chart visualization data.

        Args:
            trajectory: Trajectory data dictionary.

        Returns:
            Chart data dictionary.
        """
        return {
            "chart_type": "temporal_trajectory",
            "x_axis": "time",
            "y_axis": "land_use_fraction",
            "data_points": trajectory.get("data_points", []),
            "trend_line": trajectory.get("trend", {}),
        }

    # ------------------------------------------------------------------
    # Internal: Non-Compliance Flagging
    # ------------------------------------------------------------------

    def _flag_non_compliant(
        self,
        verdicts: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """Flag non-compliant plots from verdict list.

        Args:
            verdicts: List of verdict dictionaries.

        Returns:
            List of non-compliant plot flag dictionaries.
        """
        flags: List[Dict[str, Any]] = []
        for verdict in verdicts:
            v = verdict.get("verdict", "").lower()
            if v in ("non_compliant", "deforested", "degraded"):
                flags.append({
                    "plot_id": verdict.get("plot_id", ""),
                    "verdict": v,
                    "confidence": verdict.get("confidence", 0.0),
                    "flag_type": "NON_COMPLIANT",
                    "action_required": (
                        "Exclude from supply chain or obtain "
                        "remediation evidence per EUDR Article 10."
                    ),
                })
        return flags

    # ------------------------------------------------------------------
    # Internal: Summary Generation
    # ------------------------------------------------------------------

    def _generate_summary(
        self,
        report_type: str,
        total_plots: int,
        compliant: int,
        non_compliant: int,
        inconclusive: int,
    ) -> str:
        """Generate a template-based narrative summary.

        No LLM is used; summary is composed from computed values
        using deterministic templates.

        Args:
            report_type: Type of report.
            total_plots: Total number of plots.
            compliant: Compliant count.
            non_compliant: Non-compliant count.
            inconclusive: Inconclusive count.

        Returns:
            Narrative summary string.
        """
        compliance_rate = (
            compliant / max(total_plots, 1) * 100.0
        )

        lines = [
            f"EUDR Compliance Report ({report_type})",
            f"Assessment Date: {_today_iso()}",
            f"Regulatory Framework: {REGULATORY_FRAMEWORK}",
            f"EUDR Cutoff Date: {EUDR_CUTOFF_DATE.isoformat()}",
            "",
            f"Total Plots Assessed: {total_plots}",
            f"Compliant: {compliant} ({compliance_rate:.1f}%)",
            f"Non-Compliant: {non_compliant}",
            f"Inconclusive: {inconclusive}",
        ]

        if non_compliant > 0:
            lines.append("")
            lines.append(
                f"WARNING: {non_compliant} plot(s) flagged as "
                f"non-compliant with EUDR deforestation-free "
                f"requirements. Immediate supply chain review "
                f"recommended per Article 10."
            )

        if inconclusive > 0:
            lines.append("")
            lines.append(
                f"NOTE: {inconclusive} plot(s) have inconclusive "
                f"results due to insufficient data quality. "
                f"Additional evidence collection recommended."
            )

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Internal: Report Hash
    # ------------------------------------------------------------------

    def _compute_report_hash(
        self,
        report_data: Dict[str, Any],
    ) -> str:
        """Compute SHA-256 hash of the complete report data.

        Args:
            report_data: Report data dictionary.

        Returns:
            SHA-256 hex digest.
        """
        return _compute_hash(report_data)

    # ------------------------------------------------------------------
    # Internal: Validation
    # ------------------------------------------------------------------

    def _validate_report_type(self, report_type: str) -> None:
        """Validate report type.

        Raises:
            ValueError: If report_type is not recognized.
        """
        if report_type not in VALID_REPORT_TYPES:
            raise ValueError(
                f"Invalid report_type '{report_type}'. "
                f"Valid types: {sorted(VALID_REPORT_TYPES)}"
            )

    def _validate_format(self, fmt: str) -> None:
        """Validate output format.

        Raises:
            ValueError: If format is not recognized.
        """
        if fmt not in VALID_FORMATS:
            raise ValueError(
                f"Invalid format '{fmt}'. "
                f"Valid formats: {sorted(VALID_FORMATS)}"
            )

    # ------------------------------------------------------------------
    # Internal: Error Report
    # ------------------------------------------------------------------

    def _create_error_report(
        self,
        config: ReportConfig,
        error_msg: str,
    ) -> ComplianceReport:
        """Create an error report for a failed generation.

        Args:
            config: Report configuration that failed.
            error_msg: Error message.

        Returns:
            ComplianceReport with error metadata.
        """
        report = ComplianceReport(
            report_id=_generate_id(),
            report_type=config.report_type,
            format=config.format,
            plot_ids=list(config.plot_ids),
            total_plots=len(config.plot_ids),
            summary=f"Report generation failed: {error_msg}",
            created_at=utcnow().isoformat(),
            metadata={"error": error_msg},
        )
        report.report_hash = _compute_hash({"error": error_msg})
        return report

# ---------------------------------------------------------------------------
# Module Exports
# ---------------------------------------------------------------------------

__all__ = [
    # Enumerations
    "ReportType",
    "ReportFormat",
    # Constants
    "EUDR_CUTOFF_DATE",
    "REGULATORY_FRAMEWORK",
    "VALID_REPORT_TYPES",
    "VALID_FORMATS",
    "SINGLE_PLOT_CSV_COLUMNS",
    "BATCH_CSV_COLUMNS",
    # Data classes
    "ReportConfig",
    "ComplianceReport",
    # Engine
    "ComplianceReporter",
]
