{{/*
Expand the name of the chart.
*/}}
{{- define "pgbouncer.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "pgbouncer.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "pgbouncer.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "pgbouncer.labels" -}}
helm.sh/chart: {{ include "pgbouncer.chart" . }}
{{ include "pgbouncer.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/component: connection-pooler
{{- with .Values.commonLabels }}
{{ toYaml . }}
{{- end }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "pgbouncer.selectorLabels" -}}
app.kubernetes.io/name: {{ include "pgbouncer.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "pgbouncer.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "pgbouncer.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
Create the name of the secret to use for PostgreSQL credentials
*/}}
{{- define "pgbouncer.secretName" -}}
{{- if .Values.postgresql.existingSecret }}
{{- .Values.postgresql.existingSecret }}
{{- else }}
{{- include "pgbouncer.fullname" . }}-secrets
{{- end }}
{{- end }}

{{/*
Create the namespace
*/}}
{{- define "pgbouncer.namespace" -}}
{{- default .Release.Namespace .Values.namespace }}
{{- end }}

{{/*
Return the proper image name
*/}}
{{- define "pgbouncer.image" -}}
{{- $registryName := .Values.image.registry | default "" -}}
{{- $repositoryName := .Values.image.repository -}}
{{- $tag := .Values.image.tag | default .Chart.AppVersion | toString -}}
{{- if $registryName }}
{{- printf "%s/%s:%s" $registryName $repositoryName $tag -}}
{{- else }}
{{- printf "%s:%s" $repositoryName $tag -}}
{{- end }}
{{- end }}

{{/*
Return the proper exporter image name
*/}}
{{- define "pgbouncer.exporter.image" -}}
{{- $registryName := .Values.exporter.image.registry | default "" -}}
{{- $repositoryName := .Values.exporter.image.repository -}}
{{- $tag := .Values.exporter.image.tag | toString -}}
{{- if $registryName }}
{{- printf "%s/%s:%s" $registryName $repositoryName $tag -}}
{{- else }}
{{- printf "%s:%s" $repositoryName $tag -}}
{{- end }}
{{- end }}

{{/*
Create the pgbouncer.ini content
*/}}
{{- define "pgbouncer.ini" -}}
;; PgBouncer Configuration for GreenLang
;; Generated by Helm chart {{ include "pgbouncer.chart" . }}

[databases]
{{ .Values.postgresql.database }} = host=$(POSTGRESQL_HOST) port={{ .Values.postgresql.port }} dbname={{ .Values.postgresql.database }} auth_user=$(PGBOUNCER_AUTH_USER)
* = host=$(POSTGRESQL_HOST) port={{ .Values.postgresql.port }} auth_user=$(PGBOUNCER_AUTH_USER)

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 5432
unix_socket_dir = /var/run/pgbouncer
unix_socket_mode = 0777

auth_type = {{ .Values.pgbouncer.authType }}
auth_file = /bitnami/pgbouncer/conf/userlist.txt
auth_user = $(PGBOUNCER_AUTH_USER)
auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1

pool_mode = {{ .Values.pgbouncer.poolMode }}
max_client_conn = {{ .Values.pgbouncer.maxClientConn }}
default_pool_size = {{ .Values.pgbouncer.defaultPoolSize }}
min_pool_size = {{ .Values.pgbouncer.minPoolSize }}
reserve_pool_size = {{ .Values.pgbouncer.reservePoolSize }}
reserve_pool_timeout = {{ .Values.pgbouncer.reservePoolTimeout }}
max_db_connections = {{ .Values.pgbouncer.maxDbConnections }}
max_user_connections = {{ .Values.pgbouncer.maxUserConnections }}

query_timeout = {{ .Values.pgbouncer.queryTimeout }}
query_wait_timeout = {{ .Values.pgbouncer.queryWaitTimeout }}
client_idle_timeout = {{ .Values.pgbouncer.clientIdleTimeout }}
client_login_timeout = {{ .Values.pgbouncer.clientLoginTimeout }}

server_connect_timeout = 15
server_login_retry = 15
server_idle_timeout = {{ .Values.pgbouncer.serverIdleTimeout }}
server_lifetime = {{ .Values.pgbouncer.serverLifetime }}
server_check_delay = {{ .Values.pgbouncer.serverCheckDelay }}
server_check_query = {{ .Values.pgbouncer.serverCheckQuery }}
server_reset_query = {{ .Values.pgbouncer.serverResetQuery }}
server_reset_query_always = 0

log_connections = {{ if .Values.pgbouncer.logConnections }}1{{ else }}0{{ end }}
log_disconnections = {{ if .Values.pgbouncer.logDisconnections }}1{{ else }}0{{ end }}
log_pooler_errors = {{ if .Values.pgbouncer.logPoolerErrors }}1{{ else }}0{{ end }}
log_stats = {{ if .Values.pgbouncer.logStats }}1{{ else }}0{{ end }}
stats_period = {{ .Values.pgbouncer.statsPeriod }}
verbose = {{ .Values.pgbouncer.verbose }}

application_name_add_host = {{ if .Values.pgbouncer.applicationNameAddHost }}1{{ else }}0{{ end }}
admin_users = {{ .Values.pgbouncer.adminUsers }}
stats_users = {{ .Values.pgbouncer.statsUsers }}

ignore_startup_parameters = {{ .Values.pgbouncer.ignoreStartupParameters }}
tcp_keepalive = {{ if .Values.pgbouncer.tcpKeepalive }}1{{ else }}0{{ end }}
dns_max_ttl = {{ .Values.pgbouncer.dnsMaxTtl }}
dns_nxdomain_ttl = {{ .Values.pgbouncer.dnsMaxTtl }}
so_reuseport = {{ if .Values.pgbouncer.soReuseport }}1{{ else }}0{{ end }}

{{- if .Values.tls.enabled }}
client_tls_sslmode = {{ .Values.tls.clientTlsMode }}
client_tls_cert_file = /etc/pgbouncer/tls/tls.crt
client_tls_key_file = /etc/pgbouncer/tls/tls.key
client_tls_ca_file = /etc/pgbouncer/tls/ca.crt
server_tls_sslmode = {{ .Values.tls.serverTlsMode }}
server_tls_ca_file = /etc/pgbouncer/tls/ca.crt
{{- end }}

{{- if .Values.pgbouncer.extraConfig }}
{{ .Values.pgbouncer.extraConfig }}
{{- end }}
{{- end }}

{{/*
Create userlist.txt content
*/}}
{{- define "pgbouncer.userlist" -}}
; PgBouncer User List
; Admin users
"pgbouncer_admin" ""
"pgbouncer_stats" ""
"prometheus" ""
{{- end }}

{{/*
Pod annotations with config checksum
*/}}
{{- define "pgbouncer.podAnnotations" -}}
{{- with .Values.podAnnotations }}
{{ toYaml . }}
{{- end }}
checksum/config: {{ include "pgbouncer.ini" . | sha256sum }}
{{- end }}
