# -*- coding: utf-8 -*-
"""
Documentation Generator Models - AGENT-EUDR-030

Pydantic v2 models for Due Diligence Statement (DDS) generation,
Article 9 compliance assembly, risk assessment documentation,
mitigation reporting, compliance package compilation, document
versioning, submission tracking, and validation.

All models use Decimal for numeric scores to ensure deterministic,
bit-perfect reproducibility in compliance calculations.

Author: GreenLang Platform Team
Date: March 2026
PRD: PRD-AGENT-EUDR-030 Documentation Generator (GL-EUDR-DGN-030)
Regulation: EU 2023/1115 (EUDR) Articles 4, 5, 6, 9, 10, 31, 33
Status: Production Ready
"""
from __future__ import annotations

import enum
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Dict, List, Optional

from pydantic import Field
from greenlang.schemas import GreenLangBase


# ---------------------------------------------------------------------------
# Enums (12)
# ---------------------------------------------------------------------------


class EUDRCommodity(str, enum.Enum):
    """EUDR regulated commodities (Article 1)."""

    CATTLE = "cattle"
    COCOA = "cocoa"
    COFFEE = "coffee"
    PALM_OIL = "palm_oil"
    RUBBER = "rubber"
    SOYA = "soya"
    WOOD = "wood"


class RiskLevel(str, enum.Enum):
    """Risk classification levels per EUDR Article 10(2)."""

    NEGLIGIBLE = "negligible"
    LOW = "low"
    STANDARD = "standard"
    HIGH = "high"
    CRITICAL = "critical"


class DDSStatus(str, enum.Enum):
    """Lifecycle status of a Due Diligence Statement."""

    DRAFT = "draft"
    VALIDATED = "validated"
    SUBMITTED = "submitted"
    ACKNOWLEDGED = "acknowledged"
    REJECTED = "rejected"
    AMENDED = "amended"


class DocumentType(str, enum.Enum):
    """Types of documents generated by this agent."""

    DDS = "dds"
    ARTICLE9_PACKAGE = "article9_package"
    RISK_ASSESSMENT = "risk_assessment"
    MITIGATION_REPORT = "mitigation_report"
    COMPLIANCE_PACKAGE = "compliance_package"
    AUDIT_REPORT = "audit_report"


class SubmissionStatus(str, enum.Enum):
    """Status of a DDS submission to the EU Information System."""

    PENDING = "pending"
    VALIDATING = "validating"
    SUBMITTED = "submitted"
    ACKNOWLEDGED = "acknowledged"
    REJECTED = "rejected"
    RESUBMITTED = "resubmitted"


class PackageFormat(str, enum.Enum):
    """Output format for compliance packages."""

    JSON = "json"
    XML = "xml"
    PDF_STRUCTURED = "pdf_structured"


class ValidationSeverity(str, enum.Enum):
    """Severity levels for validation issues."""

    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


class VersionStatus(str, enum.Enum):
    """Lifecycle status of a document version."""

    DRAFT = "draft"
    FINAL = "final"
    SUBMITTED = "submitted"
    AMENDED = "amended"
    SUPERSEDED = "superseded"
    ARCHIVED = "archived"


class Article9Element(str, enum.Enum):
    """Mandatory information elements per EUDR Article 9.

    Article 9 specifies the information that must accompany every
    Due Diligence Statement for EUDR-regulated commodities.
    """

    PRODUCT_DESCRIPTION = "product_description"
    QUANTITY = "quantity"
    COUNTRY_OF_PRODUCTION = "country_of_production"
    GEOLOCATION = "geolocation"
    PRODUCTION_DATE = "production_date"
    SUPPLIER_INFO = "supplier_info"
    BUYER_INFO = "buyer_info"
    CERTIFICATIONS = "certifications"
    TRADE_CODES = "trade_codes"
    SUPPORTING_EVIDENCE = "supporting_evidence"


class ComplianceSection(str, enum.Enum):
    """Sections within a compliance package per EUDR due diligence steps."""

    INFORMATION_GATHERING = "information_gathering"
    RISK_ASSESSMENT = "risk_assessment"
    RISK_MITIGATION = "risk_mitigation"
    COMPLIANCE_CONCLUSION = "compliance_conclusion"


class RetentionStatus(str, enum.Enum):
    """Document retention lifecycle status per Article 31."""

    ACTIVE = "active"
    EXPIRING_SOON = "expiring_soon"
    EXPIRED = "expired"
    ARCHIVED = "archived"


class AuditAction(str, enum.Enum):
    """Audit trail action types for document lifecycle events."""

    CREATE = "create"
    UPDATE = "update"
    VALIDATE = "validate"
    SUBMIT = "submit"
    REJECT = "reject"
    AMEND = "amend"
    ARCHIVE = "archive"
    DELETE = "delete"


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

AGENT_ID = "GL-EUDR-DGN-030"
AGENT_VERSION = "1.0.0"

ARTICLE9_MANDATORY_ELEMENTS: List[Article9Element] = [
    Article9Element.PRODUCT_DESCRIPTION,
    Article9Element.QUANTITY,
    Article9Element.COUNTRY_OF_PRODUCTION,
    Article9Element.GEOLOCATION,
    Article9Element.PRODUCTION_DATE,
    Article9Element.SUPPLIER_INFO,
    Article9Element.BUYER_INFO,
    Article9Element.CERTIFICATIONS,
    Article9Element.TRADE_CODES,
    Article9Element.SUPPORTING_EVIDENCE,
]

DDS_MANDATORY_FIELDS: List[str] = [
    "operator_id",
    "commodity",
    "products",
    "article9_ref",
    "risk_assessment_ref",
    "compliance_conclusion",
]

SUPPORTED_COMMODITIES: List[str] = [c.value for c in EUDRCommodity]


# ---------------------------------------------------------------------------
# Pydantic Models (15+)
# ---------------------------------------------------------------------------


class ProductEntry(GreenLangBase):
    """A single product entry within a DDS.

    Represents one commodity product with its trade classification,
    quantity, and unit of measurement.
    """

    product_id: str = Field(..., description="Unique product identifier")
    description: str = Field(..., description="Human-readable product description")
    hs_code: str = Field(default="", description="Harmonized System code")
    cn_code: str = Field(default="", description="Combined Nomenclature code")
    quantity: Decimal = Field(
        ..., ge=0, description="Product quantity"
    )
    unit: str = Field(..., description="Unit of measurement (kg, tonnes, m3, etc.)")

    model_config = {"frozen": False, "extra": "ignore"}


class GeolocationReference(GreenLangBase):
    """Geolocation data for a production plot per Article 9.

    For plots over 4 hectares, polygon coordinates are required.
    For smaller plots, a single latitude/longitude point suffices.
    """

    plot_id: str = Field(..., description="Unique plot identifier")
    latitude: Decimal = Field(
        ..., ge=-90, le=90, description="Latitude in decimal degrees"
    )
    longitude: Decimal = Field(
        ..., ge=-180, le=180, description="Longitude in decimal degrees"
    )
    polygon: Optional[List[List[Decimal]]] = Field(
        default=None,
        description="Polygon coordinates [[lat, lon], ...] for plots > 4 hectares",
    )
    area_hectares: Decimal = Field(
        ..., ge=0, description="Plot area in hectares"
    )
    country_code: str = Field(
        ..., min_length=2, max_length=3, description="ISO 3166-1 country code"
    )

    model_config = {"frozen": False, "extra": "ignore"}


class SupplierReference(GreenLangBase):
    """Reference to a supplier within the supply chain."""

    supplier_id: str = Field(..., description="Unique supplier identifier")
    name: str = Field(..., description="Supplier legal name")
    country: str = Field(
        ..., min_length=2, max_length=3, description="ISO 3166-1 country code"
    )
    registration_number: str = Field(
        default="", description="Business registration number"
    )

    model_config = {"frozen": False, "extra": "ignore"}


class MeasureSummary(GreenLangBase):
    """Summary of a single mitigation measure for documentation."""

    measure_id: str = Field(..., description="Unique measure identifier")
    title: str = Field(..., description="Measure title")
    category: str = Field(..., description="Article 11 mitigation category")
    status: str = Field(..., description="Current measure status")
    reduction: Decimal = Field(
        default=Decimal("0"),
        ge=0,
        le=100,
        description="Risk reduction achieved or projected",
    )

    model_config = {"frozen": False, "extra": "ignore"}


class ValidationIssue(GreenLangBase):
    """A single validation issue found during document validation."""

    field: str = Field(..., description="Field path where the issue was found")
    severity: ValidationSeverity
    message: str = Field(..., description="Human-readable issue description")
    article_reference: str = Field(
        default="", description="EUDR article reference (e.g., 'Article 9(1)(a)')"
    )

    model_config = {"frozen": False, "extra": "ignore"}


class DDSContent(GreenLangBase):
    """Structured content payload for a Due Diligence Statement.

    Combines operator information, product data, Article 9 elements,
    risk assessment summary, mitigation summary, and compliance conclusion
    into a single document content structure.
    """

    operator_info: Dict[str, Any] = Field(
        default_factory=dict,
        description="Operator identity and registration details",
    )
    products: List[ProductEntry] = Field(
        default_factory=list,
        description="Products covered by this DDS",
    )
    article9_data: Dict[str, Any] = Field(
        default_factory=dict,
        description="Article 9 information elements",
    )
    risk_summary: Dict[str, Any] = Field(
        default_factory=dict,
        description="Risk assessment summary",
    )
    mitigation_summary: Dict[str, Any] = Field(
        default_factory=dict,
        description="Risk mitigation summary",
    )
    conclusion: str = Field(
        default="", description="Compliance conclusion statement"
    )

    model_config = {"frozen": False, "extra": "ignore"}


class DDSDocument(GreenLangBase):
    """Due Diligence Statement document per EUDR Article 4.

    The primary regulatory document that operators must submit
    before placing EUDR-regulated commodities on the EU market
    or exporting them.
    """

    dds_id: str = Field(..., description="Unique DDS identifier")
    reference_number: str = Field(
        ..., description="DDS reference number (e.g., DDS-2026-00001)"
    )
    operator_id: str = Field(..., description="Operator identifier")
    commodity: EUDRCommodity
    products: List[ProductEntry] = Field(
        default_factory=list,
        description="Products covered by this DDS",
    )
    article9_ref: str = Field(
        default="", description="Reference to Article 9 package"
    )
    risk_assessment_ref: str = Field(
        default="", description="Reference to risk assessment document"
    )
    mitigation_ref: str = Field(
        default="", description="Reference to mitigation report (if applicable)"
    )
    status: DDSStatus = DDSStatus.DRAFT
    compliance_conclusion: str = Field(
        default="",
        description="Compliance conclusion (compliant/non-compliant/pending)",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    submitted_at: Optional[datetime] = None
    provenance_hash: str = ""

    model_config = {"frozen": False, "extra": "ignore"}


class Article9Package(GreenLangBase):
    """Article 9 information package assembly.

    Collects and validates all mandatory information elements
    required by EUDR Article 9 for the DDS submission.
    """

    package_id: str = Field(..., description="Unique package identifier")
    operator_id: str = Field(..., description="Operator identifier")
    commodity: EUDRCommodity
    elements: Dict[str, Any] = Field(
        default_factory=dict,
        description="Article 9 elements keyed by Article9Element value",
    )
    completeness_score: Decimal = Field(
        default=Decimal("0"),
        ge=0,
        le=1,
        description="Fraction of mandatory elements present (0.0 to 1.0)",
    )
    missing_elements: List[str] = Field(
        default_factory=list,
        description="List of missing Article 9 element names",
    )
    assembled_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    model_config = {"frozen": False, "extra": "ignore"}


class RiskAssessmentDoc(GreenLangBase):
    """Risk assessment documentation for inclusion in DDS.

    Captures the structured risk assessment output from upstream
    risk agents (EUDR-016 through EUDR-020, EUDR-028) for
    regulatory documentation purposes.
    """

    doc_id: str = Field(..., description="Unique document identifier")
    assessment_id: str = Field(..., description="Source risk assessment ID")
    operator_id: str = Field(..., description="Operator identifier")
    commodity: EUDRCommodity
    composite_score: Decimal = Field(
        ..., ge=0, le=100, description="Composite risk score 0-100"
    )
    risk_level: RiskLevel
    criterion_evaluations: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Per-criterion evaluation details",
    )
    country_benchmark: str = Field(
        default="", description="Country risk benchmark classification"
    )
    simplified_dd_eligible: bool = Field(
        default=False,
        description="Whether simplified due diligence applies (low risk country)",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    model_config = {"frozen": False, "extra": "ignore"}


class MitigationDoc(GreenLangBase):
    """Mitigation documentation for inclusion in DDS.

    Summarizes the risk mitigation strategy outcome from
    EUDR-029 Mitigation Measure Designer for regulatory records.
    """

    doc_id: str = Field(..., description="Unique document identifier")
    strategy_id: str = Field(..., description="Source mitigation strategy ID")
    operator_id: str = Field(..., description="Operator identifier")
    commodity: EUDRCommodity
    pre_score: Decimal = Field(
        ..., ge=0, le=100, description="Pre-mitigation risk score"
    )
    post_score: Decimal = Field(
        ..., ge=0, le=100, description="Post-mitigation risk score"
    )
    measures_summary: List[MeasureSummary] = Field(
        default_factory=list,
        description="Summary of mitigation measures applied",
    )
    verification_result: Optional[str] = Field(
        default=None,
        description="Verification result (sufficient/partial/insufficient)",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    model_config = {"frozen": False, "extra": "ignore"}


class CompliancePackage(GreenLangBase):
    """Complete compliance package assembling all DDS components.

    Bundles the DDS, Article 9 data, risk assessment, mitigation
    report, and supporting evidence into a single submission-ready
    package with table of contents and cross-references.
    """

    package_id: str = Field(..., description="Unique package identifier")
    dds_id: str = Field(..., description="Associated DDS identifier")
    operator_id: str = Field(..., description="Operator identifier")
    commodity: EUDRCommodity
    sections: Dict[str, Any] = Field(
        default_factory=dict,
        description="Package sections keyed by ComplianceSection value",
    )
    table_of_contents: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Ordered table of contents entries",
    )
    cross_references: Dict[str, str] = Field(
        default_factory=dict,
        description="Cross-reference map between document sections",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    provenance_hash: str = ""

    model_config = {"frozen": False, "extra": "ignore"}


class DocumentVersion(GreenLangBase):
    """Version record for a managed document.

    Tracks document revisions with content hashes for integrity
    verification and amendment audit trails per Article 31.
    """

    version_id: str = Field(..., description="Unique version identifier")
    document_id: str = Field(..., description="Parent document identifier")
    document_type: DocumentType
    version_number: int = Field(
        ..., ge=1, description="Sequential version number"
    )
    status: VersionStatus = VersionStatus.DRAFT
    content_hash: str = Field(
        ..., description="SHA-256 hash of the version content"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    created_by: str = Field(
        default=AGENT_ID, description="Creator identity"
    )
    amendment_reason: Optional[str] = Field(
        default=None, description="Reason for amendment (if amended)"
    )

    model_config = {"frozen": False, "extra": "ignore"}


class SubmissionRecord(GreenLangBase):
    """Record of a DDS submission to the EU Information System.

    Tracks the submission lifecycle including acknowledgement,
    rejection, and resubmission states per Article 33.
    """

    submission_id: str = Field(..., description="Unique submission identifier")
    dds_id: str = Field(..., description="Associated DDS identifier")
    operator_id: Optional[str] = Field(
        default=None, description="Operator ID from the DDS"
    )
    status: SubmissionStatus = SubmissionStatus.PENDING
    submitted_at: Optional[datetime] = None
    acknowledged_at: Optional[datetime] = None
    rejected_at: Optional[datetime] = None
    rejection_reason: Optional[str] = None
    receipt_number: Optional[str] = Field(
        default=None, description="EU IS receipt number upon acknowledgement"
    )
    eu_receipt_number: Optional[str] = Field(
        default=None, description="Alias for receipt_number"
    )
    resubmission_count: int = Field(
        default=0, ge=0, description="Number of resubmissions"
    )

    model_config = {"frozen": False, "extra": "ignore"}


class ValidationResult(GreenLangBase):
    """Result of validating a document prior to submission.

    Contains a list of errors and warnings discovered during
    validation against EUDR requirements.
    """

    validation_id: str = Field(..., description="Unique validation identifier")
    document_id: str = Field(..., description="Document being validated")
    document_type: DocumentType
    is_valid: bool = Field(
        ..., description="True if no ERROR-level issues found"
    )
    errors: List[ValidationIssue] = Field(
        default_factory=list,
        description="ERROR-level validation issues",
    )
    warnings: List[ValidationIssue] = Field(
        default_factory=list,
        description="WARNING-level validation issues",
    )
    validated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    model_config = {"frozen": False, "extra": "ignore"}


class HealthStatus(GreenLangBase):
    """Health check response for the Documentation Generator."""

    agent_id: str = AGENT_ID
    status: str = "healthy"
    version: str = AGENT_VERSION
    engines: Dict[str, str] = Field(default_factory=dict)
    database: bool = False
    redis: bool = False
    uptime_seconds: float = 0.0

    model_config = {"frozen": False, "extra": "ignore"}
