# -*- coding: utf-8 -*-
"""
Prometheus Metrics - AGENT-DATA-020: Climate Hazard Connector

12 Prometheus metrics for climate hazard connector service monitoring with
graceful fallback when prometheus_client is not installed.

Standard metrics (via MetricsFactory):
    1.  gl_chc_operations_total (Counter, labels: type, tenant_id)
    2.  gl_chc_processing_duration_seconds (Histogram, 12 buckets)
    3.  gl_chc_validation_errors_total (Counter, labels: severity, type)
    4.  gl_chc_batch_jobs_total (Counter, labels: status)
    5.  gl_chc_active_jobs (Gauge)
    6.  gl_chc_queue_size (Gauge)

Agent-specific metrics:
    7.  gl_chc_hazard_data_ingested_total (Counter, labels: hazard_type, source)
    8.  gl_chc_risk_indices_calculated_total (Counter, labels: hazard_type, scenario)
    9.  gl_chc_scenario_projections_total (Counter, labels: scenario, time_horizon)
    10. gl_chc_exposure_assessments_total (Counter, labels: asset_type, hazard_type)
    11. gl_chc_ingestion_duration_seconds (Histogram, labels: source)
    12. gl_chc_pipeline_duration_seconds (Histogram, labels: pipeline_stage)

Author: GreenLang Platform Team
Date: February 2026
PRD: AGENT-DATA-020 Climate Hazard Connector (GL-DATA-GEO-002)
Status: Production Ready
"""

from __future__ import annotations

from greenlang.data_commons.metrics import (
    PROMETHEUS_AVAILABLE,
    MetricsFactory,
)

# ---------------------------------------------------------------------------
# Standard metrics (6 of 12) via factory
# ---------------------------------------------------------------------------

m = MetricsFactory(
    "gl_chc",
    "Climate Hazard Connector",
    duration_buckets=(0.1, 0.5, 1, 2, 5, 10, 30, 60, 120),
)

# ---------------------------------------------------------------------------
# Agent-specific metrics (6 of 12)
# ---------------------------------------------------------------------------

chc_hazard_data_ingested_total = m.create_custom_counter(
    "hazard_data_ingested_total",
    "Total climate hazard data records ingested by the connector",
    labelnames=["hazard_type", "source"],
)

chc_risk_indices_calculated_total = m.create_custom_counter(
    "risk_indices_calculated_total",
    "Total climate risk indices calculated by the connector",
    labelnames=["hazard_type", "scenario"],
)

chc_scenario_projections_total = m.create_custom_counter(
    "scenario_projections_total",
    "Total climate scenario projections performed by the connector",
    labelnames=["scenario", "time_horizon"],
)

chc_exposure_assessments_total = m.create_custom_counter(
    "exposure_assessments_total",
    "Total exposure assessments performed by the connector",
    labelnames=["asset_type", "hazard_type"],
)

chc_vulnerability_scores_total = m.create_custom_counter(
    "vulnerability_scores_total",
    "Total vulnerability scores computed by the connector",
    labelnames=["sector", "hazard_type"],
)

chc_reports_generated_total = m.create_custom_counter(
    "reports_generated_total",
    "Total compliance and analysis reports generated by the connector",
    labelnames=["report_type", "format"],
)

chc_pipeline_runs_total = m.create_custom_counter(
    "pipeline_runs_total",
    "Total pipeline stage executions by the climate hazard connector",
    labelnames=["pipeline_stage", "status"],
)

chc_active_sources = m.create_custom_gauge(
    "active_sources",
    "Current number of active climate hazard data sources registered",
)

chc_active_assets = m.create_custom_gauge(
    "active_assets",
    "Current number of active assets registered for climate hazard monitoring",
)

chc_high_risk_locations = m.create_custom_gauge(
    "high_risk_locations",
    "Current number of locations classified as high climate risk",
)

chc_ingestion_duration_seconds = m.create_custom_histogram(
    "ingestion_duration_seconds",
    "Duration of climate hazard data ingestion operations in seconds",
    buckets=(0.1, 0.5, 1, 2, 5, 10, 30, 60, 120),
    labelnames=["source"],
)

chc_pipeline_duration_seconds = m.create_custom_histogram(
    "pipeline_duration_seconds",
    "Duration of climate hazard pipeline stage executions in seconds",
    buckets=(0.1, 0.5, 1, 5, 10, 30, 60, 120, 300),
    labelnames=["pipeline_stage"],
)


# ---------------------------------------------------------------------------
# Helper functions (safe to call even without prometheus_client)
# ---------------------------------------------------------------------------


def record_ingestion(hazard_type: str, source: str) -> None:
    """Record a climate hazard data ingestion event.

    Args:
        hazard_type: Type of climate hazard ingested
            (flood, drought, wildfire, heat_wave, cold_wave, storm,
            sea_level_rise, tropical_cyclone, landslide, water_stress,
            precipitation_change, temperature_change, compound).
        source: Data source provider
            (noaa, copernicus, world_bank, nasa, ipcc, national_agency,
            satellite, ground_station, model_output, custom).
    """
    m.safe_inc(
        chc_hazard_data_ingested_total, 1,
        hazard_type=hazard_type, source=source,
    )


def record_risk_calculation(hazard_type: str, scenario: str) -> None:
    """Record a climate risk index calculation event.

    Args:
        hazard_type: Type of climate hazard for which risk was calculated.
        scenario: Climate scenario pathway used for calculation
            (rcp26, rcp45, rcp60, rcp85, ssp126, ssp245, ssp370,
            ssp585, historical, baseline).
    """
    m.safe_inc(
        chc_risk_indices_calculated_total, 1,
        hazard_type=hazard_type, scenario=scenario,
    )


def record_projection(scenario: str, time_horizon: str) -> None:
    """Record a climate scenario projection event.

    Args:
        scenario: Climate scenario pathway used for projection.
        time_horizon: Target time horizon of the projection
            (2030, 2040, 2050, 2070, 2100, short_term, medium_term,
            long_term).
    """
    m.safe_inc(
        chc_scenario_projections_total, 1,
        scenario=scenario, time_horizon=time_horizon,
    )


def record_exposure(asset_type: str, hazard_type: str) -> None:
    """Record an exposure assessment event.

    Args:
        asset_type: Type of asset assessed for exposure
            (facility, warehouse, office, data_center, factory,
            supply_chain_node, transport_hub, port, mine, farm,
            renewable_installation, portfolio).
        hazard_type: Type of climate hazard assessed against.
    """
    m.safe_inc(
        chc_exposure_assessments_total, 1,
        asset_type=asset_type, hazard_type=hazard_type,
    )


def record_vulnerability(sector: str, hazard_type: str) -> None:
    """Record a vulnerability scoring event.

    Args:
        sector: Economic sector for which vulnerability was scored
            (energy, manufacturing, agriculture, real_estate, transport,
            water, financial, healthcare, technology, mining, forestry).
        hazard_type: Type of climate hazard assessed.
    """
    m.safe_inc(
        chc_vulnerability_scores_total, 1,
        sector=sector, hazard_type=hazard_type,
    )


def record_report(report_type: str, format: str) -> None:
    """Record a compliance or analysis report generation event.

    Args:
        report_type: Type of report generated
            (tcfd, csrd, eu_taxonomy, physical_risk, transition_risk,
            portfolio_summary, hotspot_analysis, compliance_summary).
        format: Output format of the generated report
            (json, html, pdf, csv, markdown, xml).
    """
    m.safe_inc(
        chc_reports_generated_total, 1,
        report_type=report_type, format=format,
    )


def record_pipeline(pipeline_stage: str, status: str) -> None:
    """Record a pipeline stage execution event.

    Args:
        pipeline_stage: Stage of the pipeline that executed
            (ingestion, risk_calculation, scenario_projection,
            exposure_assessment, vulnerability_scoring, reporting,
            full_pipeline).
        status: Completion status of the pipeline stage
            (success, failure, partial, timeout).
    """
    m.safe_inc(
        chc_pipeline_runs_total, 1,
        pipeline_stage=pipeline_stage, status=status,
    )


def set_active_sources(count: int) -> None:
    """Set the gauge for current number of active hazard data sources.

    Args:
        count: Number of active climate hazard data sources currently
            registered. Must be >= 0.
    """
    m.safe_set(chc_active_sources, count)


def set_active_assets(count: int) -> None:
    """Set the gauge for current number of active monitored assets.

    Args:
        count: Number of active assets currently registered for
            climate hazard monitoring. Must be >= 0.
    """
    m.safe_set(chc_active_assets, count)


def set_high_risk(count: int) -> None:
    """Set the gauge for current number of high-risk locations.

    Args:
        count: Number of locations currently classified as high
            climate risk. Must be >= 0.
    """
    m.safe_set(chc_high_risk_locations, count)


def observe_ingestion_duration(source: str, seconds: float) -> None:
    """Record the duration of a hazard data ingestion operation.

    Args:
        source: Data source provider for the ingestion.
        seconds: Ingestion wall-clock time in seconds.
    """
    m.safe_observe(chc_ingestion_duration_seconds, seconds, source=source)


def observe_pipeline_duration(pipeline_stage: str, seconds: float) -> None:
    """Record the duration of a pipeline stage execution.

    Args:
        pipeline_stage: Stage of the pipeline that was measured.
        seconds: Pipeline stage wall-clock time in seconds.
    """
    m.safe_observe(
        chc_pipeline_duration_seconds, seconds,
        pipeline_stage=pipeline_stage,
    )


__all__ = [
    "PROMETHEUS_AVAILABLE",
    "m",
    # Metric objects
    "chc_hazard_data_ingested_total",
    "chc_risk_indices_calculated_total",
    "chc_scenario_projections_total",
    "chc_exposure_assessments_total",
    "chc_vulnerability_scores_total",
    "chc_reports_generated_total",
    "chc_pipeline_runs_total",
    "chc_active_sources",
    "chc_active_assets",
    "chc_high_risk_locations",
    "chc_ingestion_duration_seconds",
    "chc_pipeline_duration_seconds",
    # Helper functions
    "record_ingestion",
    "record_risk_calculation",
    "record_projection",
    "record_exposure",
    "record_vulnerability",
    "record_report",
    "record_pipeline",
    "set_active_sources",
    "set_active_assets",
    "set_high_risk",
    "observe_ingestion_duration",
    "observe_pipeline_duration",
]
