"""
PACK-028 Sector Pathway Pack - Configuration Module

This module exports all configuration classes, enums, constants, and utility
functions for the Sector Pathway Pack. Import from this module to access
the full configuration API.

Usage:
    >>> from packs.net_zero.PACK_028_sector_pathway.config import (
    ...     PackConfig,
    ...     SectorPathwayConfig,
    ...     PrimarySector,
    ...     SBTiPathway,
    ...     get_sector_defaults,
    ...     load_preset,
    ... )
    >>> config = PackConfig.from_preset("heavy_industry")
    >>> print(config.pack.primary_sector)
    PrimarySector.STEEL
"""

from .pack_config import (
    # Enums
    AssuranceLevel,
    CapExPhasing,
    ConvergenceModel,
    IEAScenario,
    IntensityBoundary,
    IPCCOvershoot,
    PeerSelection,
    PrimarySector,
    ReportingFrequency,
    SBTiPathway,
    # Sub-config models
    BenchmarkConfig,
    ConvergenceConfig,
    IEANZEConfig,
    IntensityConfig,
    IPCCConfig,
    MACCConfig,
    PerformanceConfig,
    ReportingConfig,
    SBTiSDAConfig,
    ScenarioAnalysisConfig,
    TechnologyRoadmapConfig,
    # Main config models
    SectorPathwayConfig,
    PackConfig,
    # Constants
    ALL_INTENSITY_METRICS,
    DEFAULT_ABATEMENT_TARGET,
    DEFAULT_BASE_YEAR,
    DEFAULT_CARBON_PRICE_CEILING,
    DEFAULT_CARBON_PRICE_FLOOR,
    DEFAULT_CATCH_UP_PERIOD,
    DEFAULT_CONVERGENCE_RATE,
    DEFAULT_LEADER_PERCENTILE,
    DEFAULT_TARGET_YEAR_LONG,
    DEFAULT_TARGET_YEAR_NEAR,
    DEFAULT_TRL_THRESHOLD,
    EXTENDED_INTENSITY_METRICS,
    IEA_SCENARIOS,
    IPCC_AR6_GWP100,
    IPCC_PATHWAYS,
    SBTI_COVERAGE_THRESHOLDS,
    SBTI_REDUCTION_RATES,
    SDA_2050_TARGETS,
    SDA_INTENSITY_METRICS,
    SDA_SECTORS,
    SECTOR_DECARBONIZATION_LEVERS,
    SECTOR_INFO,
    SUPPORTED_PRESETS,
    # Directories
    CONFIG_DIR,
    PACK_BASE_DIR,
    # Utility functions
    get_env_overrides,
    get_gwp100,
    get_iea_scenario_info,
    get_ipcc_pathway_info,
    get_sbti_reduction_rate,
    get_sda_2050_target,
    get_sda_intensity_metric,
    get_sector_defaults,
    get_sector_info,
    get_sector_levers,
    list_available_presets,
    list_iea_scenarios,
    list_primary_sectors,
    list_sda_sectors,
    load_config,
    load_preset,
    merge_config,
    validate_config,
)

__all__ = [
    # Enums
    "AssuranceLevel",
    "CapExPhasing",
    "ConvergenceModel",
    "IEAScenario",
    "IntensityBoundary",
    "IPCCOvershoot",
    "PeerSelection",
    "PrimarySector",
    "ReportingFrequency",
    "SBTiPathway",
    # Sub-config models
    "BenchmarkConfig",
    "ConvergenceConfig",
    "IEANZEConfig",
    "IntensityConfig",
    "IPCCConfig",
    "MACCConfig",
    "PerformanceConfig",
    "ReportingConfig",
    "SBTiSDAConfig",
    "ScenarioAnalysisConfig",
    "TechnologyRoadmapConfig",
    # Main config models
    "SectorPathwayConfig",
    "PackConfig",
    # Constants
    "ALL_INTENSITY_METRICS",
    "DEFAULT_ABATEMENT_TARGET",
    "DEFAULT_BASE_YEAR",
    "DEFAULT_CARBON_PRICE_CEILING",
    "DEFAULT_CARBON_PRICE_FLOOR",
    "DEFAULT_CATCH_UP_PERIOD",
    "DEFAULT_CONVERGENCE_RATE",
    "DEFAULT_LEADER_PERCENTILE",
    "DEFAULT_TARGET_YEAR_LONG",
    "DEFAULT_TARGET_YEAR_NEAR",
    "DEFAULT_TRL_THRESHOLD",
    "EXTENDED_INTENSITY_METRICS",
    "IEA_SCENARIOS",
    "IPCC_AR6_GWP100",
    "IPCC_PATHWAYS",
    "SBTI_COVERAGE_THRESHOLDS",
    "SBTI_REDUCTION_RATES",
    "SDA_2050_TARGETS",
    "SDA_INTENSITY_METRICS",
    "SDA_SECTORS",
    "SECTOR_DECARBONIZATION_LEVERS",
    "SECTOR_INFO",
    "SUPPORTED_PRESETS",
    # Directories
    "CONFIG_DIR",
    "PACK_BASE_DIR",
    # Utility functions
    "get_env_overrides",
    "get_gwp100",
    "get_iea_scenario_info",
    "get_ipcc_pathway_info",
    "get_sbti_reduction_rate",
    "get_sda_2050_target",
    "get_sda_intensity_metric",
    "get_sector_defaults",
    "get_sector_info",
    "get_sector_levers",
    "list_available_presets",
    "list_iea_scenarios",
    "list_primary_sectors",
    "list_sda_sectors",
    "load_config",
    "load_preset",
    "merge_config",
    "validate_config",
]
