apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gl-comply-hub
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gl-comply-hub
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
