# -*- coding: utf-8 -*-
"""
SetupWizard - 10-Step Inventory Management Configuration Wizard for PACK-044
==============================================================================

This module implements a 10-step configuration wizard for setting up GHG
inventory management projects. It guides users through organizational
structure, inventory period, scopes, data sources, quality thresholds,
review workflow, version policy, consolidation, compliance, and reporting.

Wizard Steps (10):
    1.  ORG_STRUCTURE          -- Organization name, boundaries, entities
    2.  INVENTORY_PERIOD       -- Reporting year, period, frequency
    3.  SCOPE_SELECTION        -- Which scopes/categories to include
    4.  DATA_SOURCES           -- ERP, utility, fleet, supplier connections
    5.  QUALITY_THRESHOLDS     -- DQI targets, pass/fail criteria
    6.  REVIEW_WORKFLOW        -- Review levels, reviewers, sign-off rules
    7.  VERSION_POLICY         -- Versioning scheme, snapshot frequency
    8.  CONSOLIDATION          -- Approach, entity structure, eliminations
    9.  COMPLIANCE_TARGETS     -- Target frameworks, disclosure requirements
    10. REPORTING_PREFS        -- Report formats, templates, distribution

Zero-Hallucination:
    All preset values and default configurations use deterministic
    lookup tables. No LLM calls in the configuration path.

Author: GreenLang Platform Team
Date: March 2026
Pack: PACK-044 GHG Inventory Management
Status: Production Ready
"""

import hashlib
import json
import logging
import time
import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from greenlang.schemas import utcnow

logger = logging.getLogger(__name__)

_MODULE_VERSION: str = "1.0.0"

def _new_uuid() -> str:
    """Generate a new UUID4 string."""
    return str(uuid.uuid4())

def _compute_hash(data: Any) -> str:
    """Compute SHA-256 hash for provenance tracking."""
    if hasattr(data, "model_dump"):
        serializable = data.model_dump(mode="json")
    elif isinstance(data, dict):
        serializable = data
    else:
        serializable = str(data)
    raw = json.dumps(serializable, sort_keys=True, default=str)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()

class SetupStep(str, Enum):
    """Names of setup wizard steps."""

    ORG_STRUCTURE = "org_structure"
    INVENTORY_PERIOD = "inventory_period"
    SCOPE_SELECTION = "scope_selection"
    DATA_SOURCES = "data_sources"
    QUALITY_THRESHOLDS = "quality_thresholds"
    REVIEW_WORKFLOW = "review_workflow"
    VERSION_POLICY = "version_policy"
    CONSOLIDATION = "consolidation"
    COMPLIANCE_TARGETS = "compliance_targets"
    REPORTING_PREFS = "reporting_prefs"

class StepStatus(str, Enum):
    """Status of a wizard step."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    SKIPPED = "skipped"

class StepState(BaseModel):
    """State of a single wizard step."""

    step: SetupStep = Field(...)
    status: StepStatus = Field(default=StepStatus.PENDING)
    data: Dict[str, Any] = Field(default_factory=dict)
    validation_errors: List[str] = Field(default_factory=list)
    completed_at: Optional[datetime] = Field(None)

class WizardState(BaseModel):
    """Complete wizard state."""

    wizard_id: str = Field(default_factory=_new_uuid)
    current_step: Optional[SetupStep] = Field(None)
    completed_steps: List[SetupStep] = Field(default_factory=list)
    skipped_steps: List[SetupStep] = Field(default_factory=list)
    configuration: Dict[str, Any] = Field(default_factory=dict)
    progress_pct: float = Field(default=0.0, ge=0.0, le=100.0)

class ValidationResult(BaseModel):
    """Validation result for a wizard step."""

    valid: bool = Field(default=True)
    errors: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)

class PackConfig(BaseModel):
    """Final pack configuration generated by the wizard."""

    config_id: str = Field(default_factory=_new_uuid)
    organization_name: str = Field(default="")
    reporting_year: int = Field(default=2025)
    inventory_frequency: str = Field(default="annual")
    scopes_included: List[str] = Field(default_factory=list)
    data_sources: List[str] = Field(default_factory=list)
    quality_threshold: float = Field(default=80.0)
    review_levels: int = Field(default=2)
    version_scheme: str = Field(default="year.quarter")
    consolidation_approach: str = Field(default="operational_control")
    entities_count: int = Field(default=0)
    target_frameworks: List[str] = Field(default_factory=list)
    report_formats: List[str] = Field(default_factory=list)
    report_frequency: str = Field(default="annual")
    provenance_hash: str = Field(default="")
    timestamp: datetime = Field(default_factory=utcnow)

STEP_ORDER: List[SetupStep] = [
    SetupStep.ORG_STRUCTURE,
    SetupStep.INVENTORY_PERIOD,
    SetupStep.SCOPE_SELECTION,
    SetupStep.DATA_SOURCES,
    SetupStep.QUALITY_THRESHOLDS,
    SetupStep.REVIEW_WORKFLOW,
    SetupStep.VERSION_POLICY,
    SetupStep.CONSOLIDATION,
    SetupStep.COMPLIANCE_TARGETS,
    SetupStep.REPORTING_PREFS,
]

SKIPPABLE_STEPS: set = {
    SetupStep.QUALITY_THRESHOLDS,
    SetupStep.VERSION_POLICY,
    SetupStep.REPORTING_PREFS,
}

class SetupWizard:
    """10-step GHG inventory management configuration wizard.

    Guides users through complete inventory management setup including
    organizational structure, inventory period, scope selection, data
    sources, quality thresholds, review workflow, versioning, consolidation,
    compliance targets, and reporting preferences.

    Attributes:
        _steps: Current step states.
        _config: Accumulated configuration.

    Example:
        >>> wizard = SetupWizard()
        >>> state = wizard.start()
        >>> state = wizard.advance(SetupStep.ORG_STRUCTURE, org_data)
        >>> config = wizard.generate_config()
    """

    def __init__(self) -> None:
        """Initialize SetupWizard with 10 pending steps."""
        self.logger = logging.getLogger(self.__class__.__name__)
        self._steps: Dict[SetupStep, StepState] = {
            step: StepState(step=step) for step in STEP_ORDER
        }
        self._config: Dict[str, Any] = {}
        self.logger.info("SetupWizard initialized: %d steps", len(STEP_ORDER))

    def start(self) -> WizardState:
        """Start the setup wizard.

        Returns:
            WizardState with first step active.
        """
        self._steps = {step: StepState(step=step) for step in STEP_ORDER}
        self._config = {}
        state = WizardState(current_step=STEP_ORDER[0], configuration=self._config)
        self.logger.info("Wizard started: first step=%s", STEP_ORDER[0].value)
        return state

    def advance(self, step: SetupStep, input_data: Dict[str, Any]) -> WizardState:
        """Advance the wizard by completing a step.

        Args:
            step: Step to complete.
            input_data: Data for the step.

        Returns:
            Updated WizardState.
        """
        validation = self.validate_step(step, input_data)
        step_state = self._steps[step]

        if not validation.valid:
            step_state.status = StepStatus.IN_PROGRESS
            step_state.validation_errors = validation.errors
        else:
            step_state.status = StepStatus.COMPLETED
            step_state.data = input_data
            step_state.validation_errors = []
            step_state.completed_at = utcnow()
            self._apply_step_data(step, input_data)
            self.logger.info("Step %s completed", step.value)

        return self._build_state()

    def validate_step(self, step: SetupStep, data: Dict[str, Any]) -> ValidationResult:
        """Validate data for a wizard step.

        Args:
            step: Step being validated.
            data: Data to validate.

        Returns:
            ValidationResult with errors and warnings.
        """
        errors: List[str] = []
        warnings: List[str] = []

        if step == SetupStep.ORG_STRUCTURE:
            if not data.get("organization_name"):
                errors.append("Organization name is required")
        elif step == SetupStep.INVENTORY_PERIOD:
            year = data.get("reporting_year", 0)
            if year < 2000 or year > 2100:
                errors.append(f"Reporting year must be 2000-2100, got {year}")
        elif step == SetupStep.SCOPE_SELECTION:
            if not data.get("scopes"):
                errors.append("At least one scope must be selected")
        elif step == SetupStep.CONSOLIDATION:
            approach = data.get("consolidation_approach", "")
            valid = ["equity_share", "financial_control", "operational_control"]
            if approach and approach not in valid:
                errors.append(f"Invalid consolidation approach: {approach}")
        elif step == SetupStep.COMPLIANCE_TARGETS:
            if not data.get("frameworks"):
                warnings.append("No compliance frameworks selected")

        return ValidationResult(valid=len(errors) == 0, errors=errors, warnings=warnings)

    def can_skip(self, step: SetupStep) -> bool:
        """Check if a step can be skipped.

        Args:
            step: Step to check.

        Returns:
            True if the step is skippable.
        """
        return step in SKIPPABLE_STEPS

    def skip_step(self, step: SetupStep) -> WizardState:
        """Skip a wizard step.

        Args:
            step: Step to skip.

        Returns:
            Updated WizardState.

        Raises:
            ValueError: If step is not skippable.
        """
        if not self.can_skip(step):
            raise ValueError(f"Step '{step.value}' cannot be skipped")
        self._steps[step].status = StepStatus.SKIPPED
        self.logger.info("Step %s skipped", step.value)
        return self._build_state()

    def generate_config(self) -> PackConfig:
        """Generate final pack configuration from wizard state.

        Returns:
            PackConfig with complete configuration.
        """
        config = PackConfig(
            organization_name=self._config.get("organization_name", ""),
            reporting_year=self._config.get("reporting_year", 2025),
            inventory_frequency=self._config.get("inventory_frequency", "annual"),
            scopes_included=self._config.get("scopes", ["scope1", "scope2"]),
            data_sources=self._config.get("data_sources", []),
            quality_threshold=self._config.get("quality_threshold", 80.0),
            review_levels=self._config.get("review_levels", 2),
            version_scheme=self._config.get("version_scheme", "year.quarter"),
            consolidation_approach=self._config.get("consolidation_approach", "operational_control"),
            entities_count=len(self._config.get("entities", [])),
            target_frameworks=self._config.get("frameworks", ["ghg_protocol"]),
            report_formats=self._config.get("report_formats", ["pdf", "excel"]),
            report_frequency=self._config.get("report_frequency", "annual"),
        )
        config.provenance_hash = _compute_hash(config)
        self.logger.info("Config generated: org=%s, year=%d", config.organization_name, config.reporting_year)
        return config

    def get_progress(self) -> Dict[str, Any]:
        """Get overall wizard progress.

        Returns:
            Dict with progress information.
        """
        completed = sum(1 for s in self._steps.values() if s.status == StepStatus.COMPLETED)
        skipped = sum(1 for s in self._steps.values() if s.status == StepStatus.SKIPPED)
        total = len(STEP_ORDER)
        pct = ((completed + skipped) / total * 100.0) if total > 0 else 0.0
        return {
            "completed": completed, "skipped": skipped,
            "pending": total - completed - skipped, "total": total,
            "progress_pct": round(pct, 1),
        }

    def _build_state(self) -> WizardState:
        """Build current wizard state."""
        completed = [s.step for s in self._steps.values() if s.status == StepStatus.COMPLETED]
        skipped = [s.step for s in self._steps.values() if s.status == StepStatus.SKIPPED]
        total = len(STEP_ORDER)
        pct = ((len(completed) + len(skipped)) / total * 100.0) if total > 0 else 0.0
        current = None
        for step in STEP_ORDER:
            if self._steps[step].status in (StepStatus.PENDING, StepStatus.IN_PROGRESS):
                current = step
                break
        return WizardState(
            current_step=current, completed_steps=completed,
            skipped_steps=skipped, configuration=dict(self._config),
            progress_pct=round(pct, 1),
        )

    def _apply_step_data(self, step: SetupStep, data: Dict[str, Any]) -> None:
        """Apply step data to accumulated configuration."""
        if step == SetupStep.ORG_STRUCTURE:
            self._config["organization_name"] = data.get("organization_name", "")
            self._config["entities"] = data.get("entities", [])
        elif step == SetupStep.INVENTORY_PERIOD:
            self._config["reporting_year"] = data.get("reporting_year", 2025)
            self._config["inventory_frequency"] = data.get("frequency", "annual")
        elif step == SetupStep.SCOPE_SELECTION:
            self._config["scopes"] = data.get("scopes", [])
        elif step == SetupStep.DATA_SOURCES:
            self._config["data_sources"] = data.get("data_sources", [])
        elif step == SetupStep.QUALITY_THRESHOLDS:
            self._config["quality_threshold"] = data.get("quality_threshold", 80.0)
        elif step == SetupStep.REVIEW_WORKFLOW:
            self._config["review_levels"] = data.get("review_levels", 2)
        elif step == SetupStep.VERSION_POLICY:
            self._config["version_scheme"] = data.get("version_scheme", "year.quarter")
        elif step == SetupStep.CONSOLIDATION:
            self._config["consolidation_approach"] = data.get("consolidation_approach", "operational_control")
        elif step == SetupStep.COMPLIANCE_TARGETS:
            self._config["frameworks"] = data.get("frameworks", ["ghg_protocol"])
        elif step == SetupStep.REPORTING_PREFS:
            self._config["report_formats"] = data.get("report_formats", ["pdf"])
            self._config["report_frequency"] = data.get("report_frequency", "annual")
