# -*- coding: utf-8 -*-
"""
Stakeholder Engagement Models - AGENT-EUDR-031

Pydantic v2 models for stakeholder registry, FPIC workflow management,
grievance mechanism operations, consultation record keeping, multi-channel
communication, engagement assessment, and compliance reporting.

All models use Decimal for numeric scores to ensure deterministic,
bit-perfect reproducibility in compliance calculations.

Author: GreenLang Platform Team
Date: March 2026
PRD: PRD-AGENT-EUDR-031 Stakeholder Engagement Tool (GL-EUDR-SET-031)
Regulation: EU 2023/1115 (EUDR) Articles 2, 4, 8, 9, 10, 11, 12, 29, 31
Status: Production Ready
"""
from __future__ import annotations

import enum
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Dict, List, Optional

from pydantic import Field
from greenlang.schemas import GreenLangBase


# ---------------------------------------------------------------------------
# Enums (12)
# ---------------------------------------------------------------------------


class StakeholderType(str, enum.Enum):
    """Stakeholder category classification per EUDR and CSDDD."""

    INDIGENOUS_PEOPLES = "indigenous_peoples"
    LOCAL_COMMUNITIES = "local_communities"
    SMALLHOLDER_COOPERATIVES = "smallholder_cooperatives"
    NGOS = "ngos"
    WORKERS_UNIONS = "workers_unions"
    GOVERNMENT_AUTHORITIES = "government_authorities"
    CERTIFICATION_BODIES = "certification_bodies"
    CIVIL_SOCIETY = "civil_society"
    ACADEMIC_INSTITUTIONS = "academic_institutions"
    MEDIA = "media"


class RelationshipStatus(str, enum.Enum):
    """Lifecycle status of the operator-stakeholder relationship."""

    IDENTIFIED = "identified"
    CONTACTED = "contacted"
    ENGAGED = "engaged"
    ACTIVE = "active"
    DORMANT = "dormant"
    DISENGAGED = "disengaged"


class FPICStage(str, enum.Enum):
    """FPIC workflow stages per ILO Convention 169 and UNDRIP."""

    NOTIFICATION = "notification"
    INFORMATION_SHARING = "information_sharing"
    CONSULTATION = "consultation"
    DELIBERATION = "deliberation"
    DECISION = "decision"
    AGREEMENT = "agreement"
    MONITORING = "monitoring"


class ConsentStatus(str, enum.Enum):
    """Consent status outcomes for FPIC workflows."""

    PENDING = "pending"
    GRANTED = "granted"
    WITHHELD = "withheld"
    CONDITIONAL = "conditional"
    WITHDRAWN = "withdrawn"
    EXPIRED = "expired"


class GrievanceSeverity(str, enum.Enum):
    """Grievance severity classification for triage."""

    CRITICAL = "critical"
    HIGH = "high"
    STANDARD = "standard"
    MINOR = "minor"


class GrievanceCategory(str, enum.Enum):
    """Grievance thematic category classification."""

    ENVIRONMENTAL = "environmental"
    HUMAN_RIGHTS = "human_rights"
    LABOR = "labor"
    LAND_RIGHTS = "land_rights"
    COMMUNITY_IMPACT = "community_impact"
    PROCESS = "process"


class GrievanceStatus(str, enum.Enum):
    """Lifecycle status of a grievance record."""

    SUBMITTED = "submitted"
    TRIAGED = "triaged"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"
    CLOSED = "closed"
    APPEALED = "appealed"
    REOPENED = "reopened"


class IntakeChannel(str, enum.Enum):
    """Channels through which grievances can be submitted."""

    WEB_PORTAL = "web_portal"
    MOBILE_APP = "mobile_app"
    SMS = "sms"
    EMAIL = "email"
    COMMUNITY_SUBMISSION = "community_submission"


class ConsultationType(str, enum.Enum):
    """Types of consultation meetings and engagements."""

    COMMUNITY_MEETING = "community_meeting"
    BILATERAL = "bilateral"
    FOCUS_GROUP = "focus_group"
    PUBLIC_HEARING = "public_hearing"
    WORKSHOP = "workshop"
    FIELD_VISIT = "field_visit"


class CommunicationChannel(str, enum.Enum):
    """Supported communication channels for stakeholder outreach."""

    EMAIL = "email"
    SMS = "sms"
    LETTER = "letter"
    RADIO = "radio"
    IN_PERSON = "in_person"
    PHONE = "phone"
    DIGITAL_PLATFORM = "digital_platform"


class ReportType(str, enum.Enum):
    """Types of compliance reports generated by this agent."""

    DDS_SUMMARY = "dds_summary"
    FPIC_COMPLIANCE = "fpic_compliance"
    GRIEVANCE_REPORT = "grievance_report"
    CONSULTATION_REGISTER = "consultation_register"
    ENGAGEMENT_SUMMARY = "engagement_summary"
    COMMUNICATION_LOG = "communication_log"


class AuditAction(str, enum.Enum):
    """Audit trail action types for engagement lifecycle events."""

    CREATE = "create"
    UPDATE = "update"
    DELETE = "delete"
    SUBMIT = "submit"
    RESOLVE = "resolve"
    ESCALATE = "escalate"
    APPROVE = "approve"
    REJECT = "reject"
    ARCHIVE = "archive"


class EUDRCommodity(str, enum.Enum):
    """EUDR-regulated commodities per Regulation (EU) 2023/1115."""

    CATTLE = "cattle"
    COCOA = "cocoa"
    COFFEE = "coffee"
    PALM_OIL = "palm_oil"
    RUBBER = "rubber"
    SOYA = "soya"
    WOOD = "wood"


class StakeholderCategory(str, enum.Enum):
    """Stakeholder category classification (test-compatible)."""

    INDIGENOUS_COMMUNITY = "indigenous_community"
    LOCAL_COMMUNITY = "local_community"
    COOPERATIVE = "cooperative"
    SMALLHOLDER = "smallholder"
    NGO = "ngo"
    GOVERNMENT_AGENCY = "government_agency"
    CERTIFICATION_BODY = "certification_body"
    WORKER_UNION = "worker_union"
    OTHER = "other"


class StakeholderStatus(str, enum.Enum):
    """Stakeholder relationship status (test-compatible)."""

    ACTIVE = "active"
    INACTIVE = "inactive"
    PENDING = "pending"
    ARCHIVED = "archived"


class CommunicationStatus(str, enum.Enum):
    """Communication status for tracking."""

    DRAFT = "draft"
    SCHEDULED = "scheduled"
    SENT = "sent"
    DELIVERED = "delivered"
    READ = "read"
    FAILED = "failed"


class DeliveryStatus(str, enum.Enum):
    """Delivery status for communications."""

    PENDING = "pending"
    SCHEDULED = "scheduled"
    SENT = "sent"
    DELIVERED = "delivered"
    FAILED = "failed"
    BOUNCED = "bounced"
    READ = "read"


class EngagementDimension(str, enum.Enum):
    """Dimensions for engagement quality assessment."""

    INCLUSIVENESS = "inclusiveness"
    TRANSPARENCY = "transparency"
    RESPONSIVENESS = "responsiveness"
    ACCOUNTABILITY = "accountability"
    CULTURAL_SENSITIVITY = "cultural_sensitivity"
    RIGHTS_RESPECT = "rights_respect"


class ReportFormat(str, enum.Enum):
    """Supported report output formats."""

    JSON = "json"
    PDF = "pdf"
    XML = "xml"
    CSV = "csv"


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

AGENT_ID = "GL-EUDR-SET-031"
AGENT_VERSION = "1.0.0"

# FPIC workflow stage ordering
FPIC_STAGES_ORDERED: List[FPICStage] = [
    FPICStage.NOTIFICATION,
    FPICStage.INFORMATION_SHARING,
    FPICStage.CONSULTATION,
    FPICStage.DELIBERATION,
    FPICStage.DECISION,
    FPICStage.AGREEMENT,
    FPICStage.MONITORING,
]

# Grievance severity levels in priority order
GRIEVANCE_SEVERITY_LEVELS: List[GrievanceSeverity] = [
    GrievanceSeverity.CRITICAL,
    GrievanceSeverity.HIGH,
    GrievanceSeverity.STANDARD,
    GrievanceSeverity.MINOR,
]

# EUDR-regulated commodities
SUPPORTED_COMMODITIES: List[str] = [
    "cattle",
    "cocoa",
    "coffee",
    "palm_oil",
    "rubber",
    "soya",
    "wood",
]

SUPPORTED_LANGUAGES: List[str] = [
    "en", "fr", "de", "es", "pt", "id", "sw",
    "ar", "zh", "hi", "ms", "th",
]

FPIC_MANDATORY_STAGES: List[FPICStage] = [
    FPICStage.NOTIFICATION,
    FPICStage.INFORMATION_SHARING,
    FPICStage.DELIBERATION,
    FPICStage.CONSULTATION,
    FPICStage.DECISION,
    FPICStage.AGREEMENT,
    FPICStage.MONITORING,
]

STAKEHOLDER_TYPES_WITH_FPIC_RIGHTS: List[StakeholderType] = [
    StakeholderType.INDIGENOUS_PEOPLES,
    StakeholderType.LOCAL_COMMUNITIES,
]


# ---------------------------------------------------------------------------
# Pydantic Models (15+)
# ---------------------------------------------------------------------------


class ContactInfo(GreenLangBase):
    """Contact information for a stakeholder."""

    primary_contact_name: str = Field(
        default="", description="Primary contact person name"
    )
    email: str = Field(default="", description="Email address")
    phone: str = Field(default="", description="Phone number")
    preferred_channel: CommunicationChannel = Field(
        default=CommunicationChannel.EMAIL,
        description="Preferred communication channel",
    )
    preferred_language: str = Field(
        default="en", description="Preferred language (ISO 639-1)"
    )
    address: str = Field(default="", description="Physical address")

    model_config = {"frozen": False, "extra": "ignore"}


class RightsClassification(GreenLangBase):
    """Rights classification for a stakeholder under applicable law.

    Identifies which legal frameworks and protections apply to the
    stakeholder based on their type and location.
    """

    has_land_rights: bool = Field(
        default=False,
        description="Whether land rights apply",
    )
    has_customary_rights: bool = Field(
        default=False,
        description="Whether customary rights apply",
    )
    has_indigenous_status: bool = Field(
        default=False,
        description="Whether indigenous status applies",
    )
    fpic_required: bool = Field(
        default=False,
        description="Whether FPIC is required (ILO 169 / UNDRIP)",
    )
    applicable_conventions: List[str] = Field(
        default_factory=list,
        description="Applicable conventions (ILO 169, UNDRIP)",
    )
    legal_framework: str = Field(
        default="",
        description="Relevant legal framework references",
    )

    model_config = {"frozen": False, "extra": "ignore"}


class FPICStageConfig(GreenLangBase):
    """Configuration for a single FPIC workflow stage."""

    stage: FPICStage
    sla_days: int = Field(
        ..., ge=1, description="SLA deadline in days for this stage"
    )
    evidence_required: bool = Field(
        default=True, description="Whether evidence must be attached"
    )
    approval_required: bool = Field(
        default=False, description="Whether explicit approval gate applies"
    )
    description: str = Field(default="", description="Stage description")

    model_config = {"frozen": False, "extra": "ignore"}


class StakeholderRecord(GreenLangBase):
    """A stakeholder in the EUDR supply chain engagement registry.

    Represents an individual or organization with whom the operator
    must engage as part of their EUDR due diligence obligations.
    """

    stakeholder_id: str = Field(
        ..., description="Unique stakeholder identifier"
    )
    operator_id: str = Field(
        ..., description="Operator who registered this stakeholder"
    )
    name: str = Field(..., description="Stakeholder name or community name")
    category: StakeholderCategory = Field(
        ..., description="Stakeholder category"
    )
    status: StakeholderStatus = Field(
        default=StakeholderStatus.PENDING,
        description="Stakeholder status",
    )
    country_code: str = Field(
        ..., description="ISO 3166-1 country code",
    )
    region: str = Field(default="", description="Geographic region")
    commodity: EUDRCommodity = Field(
        ..., description="Associated EUDR commodity"
    )
    contact_info: Dict[str, Any] = Field(
        ..., description="Contact information dictionary",
    )
    rights_classification: RightsClassification = Field(
        ..., description="Rights classification under applicable law",
    )
    population_estimate: Optional[int] = Field(
        default=None, ge=0,
        description="Estimated population if community",
    )
    affected_area_hectares: Optional[Decimal] = Field(
        default=None, ge=0,
        description="Affected area in hectares",
    )
    engagement_history: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Chronological engagement event log",
    )
    notes: str = Field(
        default="",
        description="Additional notes",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    provenance_hash: str = ""

    model_config = {"frozen": False, "extra": "ignore"}


class FPICWorkflow(GreenLangBase):
    """Free, Prior and Informed Consent workflow record.

    Tracks the multi-stage FPIC process for engagement with
    indigenous peoples and local communities per ILO Convention 169
    and UNDRIP.
    """

    workflow_id: str = Field(..., description="Unique FPIC workflow identifier")
    stakeholder_id: str = Field(
        ..., description="Stakeholder being consulted"
    )
    operator_id: str = Field(..., description="Operator identifier")
    commodity: EUDRCommodity = Field(
        ..., description="Associated EUDR commodity"
    )
    current_stage: FPICStage = Field(
        default=FPICStage.NOTIFICATION,
        description="Current FPIC stage",
    )
    consent_status: ConsentStatus = Field(
        default=ConsentStatus.PENDING,
        description="Consent status",
    )
    stage_config: Dict[str, Any] = Field(
        default_factory=dict,
        description="Stage configuration parameters",
    )
    initiated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    stage_history: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Chronological stage transition log",
    )
    consultation_records: List[str] = Field(
        default_factory=list,
        description="Linked consultation record IDs",
    )
    evidence_documents: List[str] = Field(
        default_factory=list,
        description="Evidence document references",
    )
    consent_recorded_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when consent was recorded",
    )
    consent_evidence: str = Field(
        default="",
        description="Evidence of consent decision",
    )
    completed_at: Optional[datetime] = None
    provenance_hash: str = ""

    model_config = {"frozen": False, "extra": "ignore"}


class InvestigationNotes(GreenLangBase):
    """Investigation notes for a grievance."""

    investigator: str = Field(
        default="", description="Investigator identifier"
    )
    findings: str = Field(default="", description="Investigation findings")
    evidence_collected: List[str] = Field(
        default_factory=list,
        description="Evidence file references",
    )
    root_cause: str = Field(
        default="", description="Root cause analysis"
    )
    interviews_conducted: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Stakeholder interviews conducted",
    )
    investigated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    model_config = {"frozen": False, "extra": "ignore"}


class ResolutionActions(GreenLangBase):
    """Resolution actions taken for a grievance."""

    resolution_type: str = Field(
        default="", description="Type of resolution applied"
    )
    actions_taken: List[str] = Field(
        default_factory=list,
        description="List of actions taken to resolve",
    )
    remediation: str = Field(
        default="", description="Remediation provided to complainant"
    )
    preventive_measures: List[str] = Field(
        default_factory=list,
        description="Preventive measures to avoid recurrence",
    )
    resolved_by: str = Field(
        default="", description="Person/team who resolved the grievance"
    )
    resolved_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    model_config = {"frozen": False, "extra": "ignore"}


class GrievanceRecord(GreenLangBase):
    """A grievance/complaint record in the mechanism.

    Tracks the lifecycle of a complaint from submission through
    resolution per UN Guiding Principles Principle 31 criteria.
    """

    grievance_id: str = Field(
        ..., description="Unique grievance identifier"
    )
    stakeholder_id: str = Field(
        ..., description="Stakeholder who submitted grievance"
    )
    operator_id: str = Field(
        ..., description="Operator against whom complaint is filed"
    )
    title: str = Field(
        ..., description="Grievance title"
    )
    description: str = Field(
        ..., description="Complaint description"
    )
    severity: GrievanceSeverity = Field(
        ..., description="Grievance severity level"
    )
    status: GrievanceStatus = Field(
        default=GrievanceStatus.SUBMITTED,
        description="Grievance status",
    )
    category: str = Field(
        default="",
        description="Grievance category",
    )
    channel: Optional[str] = Field(
        default=None,
        description="Intake channel",
    )
    submitted_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    sla_deadline: Optional[datetime] = Field(
        default=None,
        description="SLA deadline for response",
    )
    investigation_notes: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Investigation notes",
    )
    resolution_actions: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Resolution actions taken",
    )
    assigned_to: Optional[str] = Field(
        default=None, description="Assigned investigator"
    )
    resolution_summary: str = Field(
        default="", description="Resolution summary text"
    )
    appeal_reason: str = Field(
        default="", description="Reason for appeal if appealed"
    )
    satisfaction_score: Optional[Decimal] = Field(
        default=None, description="Post-resolution satisfaction score 0-100"
    )
    satisfaction_feedback: str = Field(
        default="", description="Post-resolution feedback text"
    )
    acknowledged_at: Optional[datetime] = None
    triaged_at: Optional[datetime] = None
    resolved_at: Optional[datetime] = None
    provenance_hash: str = ""

    model_config = {"frozen": False, "extra": "allow"}


class FollowUpAction(GreenLangBase):
    """A follow-up action from a consultation."""

    action_id: str = Field(..., description="Unique action identifier")
    description: str = Field(..., description="Action description")
    responsible_party: str = Field(
        ..., description="Party responsible for the action"
    )
    deadline: Optional[datetime] = None
    status: str = Field(default="pending", description="Action status")

    model_config = {"frozen": False, "extra": "ignore"}


class ConsultationRecord(GreenLangBase):
    """A consultation record per EUDR Article 10(2)(e).

    Documents the objectives, participants, methodology, discussions,
    outcomes, and commitments from stakeholder consultations.
    """

    consultation_id: str = Field(
        ..., description="Unique consultation identifier"
    )
    operator_id: str = Field(
        ..., description="Operator conducting the consultation"
    )
    consultation_type: ConsultationType = Field(
        ..., description="Type of consultation"
    )
    title: str = Field(
        ..., description="Consultation title or purpose"
    )
    description: str = Field(
        default="", description="Consultation description"
    )
    scheduled_at: Optional[datetime] = Field(
        default=None, description="Scheduled time"
    )
    conducted_at: Optional[datetime] = Field(
        default=None, description="Actual conducted time"
    )
    location: str = Field(default="", description="Consultation location")
    stakeholder_ids: List[str] = Field(
        default_factory=list,
        description="Stakeholder IDs participating",
    )
    participants: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Participant list with role and affiliation",
    )
    outcomes: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Outcomes and decisions reached",
    )
    evidence_refs: List[str] = Field(
        default_factory=list,
        description="Evidence file references (minutes, photos, recordings)",
    )
    language: str = Field(
        default="en", description="Primary language of the consultation"
    )
    facilitator: str = Field(
        default="", description="Facilitator name"
    )
    status: str = Field(
        default="scheduled", description="Consultation status"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    provenance_hash: str = ""

    model_config = {"frozen": False, "extra": "ignore"}


class CommunicationRecord(GreenLangBase):
    """A communication record for stakeholder outreach."""

    communication_id: str = Field(
        ..., description="Unique communication identifier"
    )
    operator_id: str = Field(
        ..., description="Operator sending the communication"
    )
    stakeholder_ids: List[str] = Field(
        ..., min_length=1,
        description="Target stakeholder identifiers",
    )
    channel: CommunicationChannel = Field(
        ..., description="Communication channel"
    )
    subject: str = Field(..., description="Communication subject")
    body: str = Field(..., description="Communication content")
    language: str = Field(
        default="en", description="Language of communication"
    )
    template_id: Optional[str] = Field(
        default=None, description="Template identifier if template-based"
    )
    delivery_status: DeliveryStatus = Field(
        default=DeliveryStatus.PENDING,
        description="Delivery status",
    )
    scheduled_at: Optional[datetime] = None
    sent_at: Optional[datetime] = None
    delivered_at: Optional[datetime] = None
    campaign_id: Optional[str] = Field(
        default=None, description="Campaign identifier if part of campaign"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    provenance_hash: str = ""

    model_config = {"frozen": False, "extra": "ignore"}


class CommunicationTemplate(GreenLangBase):
    """A reusable template for stakeholder communications.

    Supports variable substitution for personalized messaging across
    multiple channels and languages.
    """

    template_id: str = Field(
        ..., description="Unique template identifier"
    )
    name: str = Field(..., description="Template name")
    channel: CommunicationChannel = CommunicationChannel.EMAIL
    subject_template: str = Field(
        default="", description="Subject template with {{variable}} placeholders"
    )
    body_template: str = Field(
        ..., description="Body template with {{variable}} placeholders"
    )
    language: str = Field(
        default="en", description="Template language (ISO 639-1)"
    )
    variables: List[str] = Field(
        default_factory=list,
        description="List of variable names used in this template",
    )
    active: bool = Field(
        default=True, description="Whether template is active"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    model_config = {"frozen": False, "extra": "ignore"}


class EngagementAssessment(GreenLangBase):
    """Engagement quality assessment per ILO 169 and UNDRIP criteria.

    Evaluates engagement quality across 6 dimensions with a composite
    score for regulatory compliance verification.
    """

    assessment_id: str = Field(
        ..., description="Unique assessment identifier"
    )
    operator_id: str = Field(
        ..., description="Operator being assessed"
    )
    stakeholder_id: str = Field(
        ..., description="Stakeholder whose engagement is assessed"
    )
    assessment_date: datetime = Field(
        ..., description="Assessment date"
    )
    dimension_scores: Dict[EngagementDimension, Decimal] = Field(
        ..., description="Dimension scores (0-100)"
    )
    composite_score: Decimal = Field(
        ..., ge=0, le=100,
        description="Weighted composite engagement score",
    )
    recommendations: List[str] = Field(
        default_factory=list,
        description="Improvement recommendations",
    )
    evidence_refs: List[str] = Field(
        default_factory=list,
        description="Evidence references",
    )
    provenance_hash: str = ""

    model_config = {"frozen": False, "extra": "ignore"}


class ComplianceReport(GreenLangBase):
    """A compliance report for stakeholder engagement.

    Audit-ready documentation for DDS submission, competent authority
    inspection, and certification scheme audits.
    """

    report_id: str = Field(..., description="Unique report identifier")
    operator_id: str = Field(
        ..., description="Operator the report covers"
    )
    report_type: ReportType = Field(
        ..., description="Type of report"
    )
    title: str = Field(..., description="Report title")
    period_start: datetime = Field(
        ..., description="Report period start"
    )
    period_end: datetime = Field(
        ..., description="Report period end"
    )
    generated_at: datetime = Field(
        ..., description="Report generation timestamp"
    )
    format: ReportFormat = Field(
        ..., description="Output format"
    )
    sections: Dict[str, Any] = Field(
        default_factory=dict,
        description="Report sections with content",
    )
    provenance_hash: str = ""

    model_config = {"frozen": False, "extra": "ignore"}


class AuditEntry(GreenLangBase):
    """An audit trail entry for stakeholder engagement events."""

    entry_id: str = Field(..., description="Unique audit entry identifier")
    action: AuditAction = Field(
        ..., description="Audit action type"
    )
    entity_type: str = Field(
        ..., description="Entity type (stakeholder, fpic, grievance, etc.)"
    )
    entity_id: str = Field(
        ..., description="Entity identifier being audited"
    )
    actor: str = Field(
        ..., description="User or system performing the action"
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    details: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional context for the action",
    )
    provenance_hash: str = ""

    model_config = {"frozen": False, "extra": "ignore"}


class HealthStatus(GreenLangBase):
    """Health check response for the Stakeholder Engagement Tool."""

    agent_id: str = AGENT_ID
    status: str = "healthy"
    version: str = AGENT_VERSION
    engines: Dict[str, str] = Field(default_factory=dict)
    database: bool = False
    redis: bool = False
    uptime_seconds: float = 0.0

    model_config = {"frozen": False, "extra": "ignore"}
